FreeRTOS/FreeRTOS-Kernel

- LICENSE
With this PR, people will see "MIT" displayed as license right next to "Contributors".
Explanation is updated since we had difference licenses under ```./FreeRTOS``` folder, and now with kernel only code this is not necessary. Year is also changed to 2020.
> Removing License/license.txt and add LICENSE under root.

- queue.c
Correction of small typographical error. Added a missing ')' in a comment on line 1287 of ./queue.c
> Small typo on L1287

- portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_loadstore_handler.S
xtensa_loadstore_handler.S uses _iram_end to prevent modification of IRAM
code. With the LoadStore exception handler in place, IRAM can also be
used for .bss and .data section. Hence the sanity check should be based
upon _iram_text_end and not _iram_end
> Xtensa_ESP32: Change _iram_end to _iram_text_end

- portable/GCC/ARM_CA9/portASM.S
Hello,
Cortex-A9 port should have eabi_attribute TAG_ABI_Align_preserved set in order to enable smooth object linking between different toolchains.
I believe that [explanation written on this link](http://www.support.code-red-tech.com/CodeRedWiki/Preserve8) summaries the problem well enough. In most cases linker only generates a warning if this attribute is not present but there can also be link errors when using strict project settings.
Assembly code from portASM.S maintains alignment so this attribute is safe to add.
Vladimir
> Cortex-A9 port: Adding stack alignment directive to assembly code

- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Fix Coverity warnings:  In most cases the return value of xTaskResumeAll() is cast to void when it is not needed.  This PR fixes a couple of instances in the heap_n.c implementations where that was not the case.
> Fix Coverity warnings where to xTaskResumeAll() calls don't use the returned value.

- GitHub-FreeRTOS-Kernel-Home.url
Description
-----------
Adding URL to direct user to GitHub FreeRTOS-Kernel home page. 
Test Steps
-----------
Tried with Safari, works fine. Keeping the same format from other .url, so should be good.
Related Issue
-----------
N/A
> Adding url to direct users to FreeRTOS-Kernel github page.

- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/portmacro.h
This is similar to the Windows port, allowing FreeRTOS kernel
applications to run as regular applications on Posix (Linux) systems.
You can use this in a 32-bit or 64-bit application (although there are
dynamic memory allocation trace points that do not support 64-bit
addresses).
Many of the same caveats of running an RTOS on a non-real-time system
apply, but this is still very useful for easy debugging/testing
applications in a simulated environment. In particular, it allows easy
use of tools such as valgrind.
You can call standard library functions from tasks but care must be
taken with any that internally take mutexes or block. This includes
malloc()/free() and many stdio functions (e.g., printf()).
Replacement malloc(), free(), realloc(), and calloc() functions are
provided which are …
> portable/GCC/Posix: add new port for Posix (Linux) applications

- tasks.c
Description
-----------
Since PR #22 has removed the need of local variable pxTCB, cleaning up. 
Test Steps
-----------
Tested in combine with PR #22 on hw. 
Related Issue
-----------
N/A
> Remove unused local variable in prvResetNextTaskUnblockTime(). 

- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
The current flash organization in ARMv7-M MPU ports looks as follows:
```
__FLASH_segment_start__ ------->+-----------+<----- __FLASH_segment_start__
|  Vector   |
|   Table   |
|     +     |
|   Kernel  |
|    Code   |
+-----------+<-----  __privileged_functions_end__
|           |
|           |
|           |
|   Other   |
|   Code    |
|           |
|           |
|           |
__FLASH_segment_end__ ------>+-----------+
```
The FreeRTOS kernel sets up the following MPU regions:
* Unprivileged Code - \_\_FLASH\_segment\_start\_\_ to \_\_FLASH\_segment\_end\_\_.
* Privileged Code - \_\_FLASH\_segment\_start\_\_ to \_\_privileged\_functions\_end\_\_.
The above setup assumes that the FreeRTOS kernel code (i.e. privileged_functions) is placed at the beginning of the flash and, therefore, uses …
> Enable ARMv7-M MPU ports to place FreeRTOS kernel code outside of flash

- portable/GCC/ARM_CM0/portmacro.h
- portable/GCC/ARM_CM3/portmacro.h
- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4F/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM7/r0p1/portmacro.h
Description
-----------
Enabling Link Time Optimization (LTO) causes some of the functions used in assembly to be incorrectly stripped off, resulting in linker error. To avoid this, these functions are marked with ```portDONT_DISCARD``` macro, definition of which is port specific. This commit adds the definition
of ```portDONT_DISCARD``` for ARMv7-M ports.
Signed-off-by: Gaurav Aggarwal <aggarg@amazon.com>
> Add definition of portDONT_DISCARD to ARMv7-M ports

- portable/ThirdParty/GCC/Posix/port.c
Fix Valgrind uninitialized variable errors
Description
-----------
==7996== Syscall param setitimer(&value->it_interval) points to uninitialised byte(s)
and
==7996== Syscall param rt_sigaction(act->sa_mask) points to uninitialised byte(s)
Test Steps
-----------
Run the port from FreeRTOS Demo similar to the one described in issue 1876
Related Issue
-----------
https://github.com/aws/amazon-freertos/issues/1876
> Fix Valgrind errors

- portable/ThirdParty/GCC/ATmega/port.c
Description
-----------
Removing ```vPortEndScheduler()``` implementation, since it's not implemented to spec. 
Also, there's little chance we need to return to the point of bare metal environment. Thus removing instead of implementing. 
Refer to https://www.freertos.org/a00133.html for kernel API ```vTaskEndScheduler()``` requirements.  The none port specific part of the logic is here https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/master/tasks.c#L2099-L2106. 
The issue with ```vPortEndScheduler()``` implementation is that, if only stop kernel tick the program will keep executing current task. The desired behavior is to at least return/jump to the next instruction after vTaskStartScheduler(). And if it's required to call ```vTaskStartScheduler()``` again, we need to clean up all tasks …
> Removing vPortEndScheduler() implementation in ATmega port

- include/FreeRTOS.h
Fix for failure to build tasks.c at f2081af03066a41cc218435a3c61d4ed90c87c77
Description
-----------
I don't have an implementation of `traceTASK_NOTIFY_TAKE` or `traceTASK_NOTIFY_WAIT`, so they are implemented by `FreeRTOS.h` -- under gcc 9 (at least), tasks.c fails.
Presumably this is because the toolchain thinks the call to `traceTASK_NOTIFY_WAIT( uxIndexToWait );` is an undeclared function, rather than our `traceTASK_NOTIFY_WAIT` macro implementation.
Test Steps
-----------
Clone at f2081af03066a41cc218435a3c61d4ed90c87c77, build under arm-none-eabi-gcc 9.2.1
Related Issue
-----------
#63 
> updates FreeRTOS.h to handle new usages of task notify

- include/mpu_prototypes.h
- include/mpu_wrappers.h
- portable/Common/mpu_wrappers.c
The recent task notification changes add a notification array to every task as opposed to a single notification value before. This results in every API taking an additional index parameter telling which notification to update. This PR  makes the corresponding changes in mpu wrappers.
> Update mpu_wrappers with task notification changes

- queue.c
Enhanced overflow protection. 
Description
-----------
- Prevent mismatching metadata after attempt to dynamically create a queue with size > 2^32 bytes.
- Prevent invalid state change that could occur from int8 overflow if ISR is being fired unreasonably fast, while a queue is locked.
Test Steps
-----------
- Attempt to create queue with > 2^32. Observe assertion.
- Second one is harder to exercise. Implemented preventively, as it is theoretically possible per CBMC. Could likely be exercised by NOT clearing interrupt flag and allowing ISR to continuously fire back-to-back with calls to `xQueueGenericSendFromISR` 
Related Issue
-----------
> Improvement to O.F. protections

- list.c
- portable/ARMv8M/non_secure/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/MemMang/heap_4.c
- tasks.c
- timers.c
Description
-----------
Some of the privileged symbols were not being placed in their respective sections. This commit addresses those and places them in privileged_functions or privileged_data section.
> Place privileged symbols correctly

- portable/ARMv8M/non_secure/port.c
- portable/CCS/ARM_CM3/port.c
- portable/CCS/ARM_CM4F/port.c
- portable/GCC/ARM_CM0/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM3/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4F/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM7/r0p1/port.c
- portable/IAR/ARM_CM0/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM3/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM4F/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM7/r0p1/port.c
- portable/MikroC/ARM_CM4F/port.c
- portable/RVDS/ARM_CM0/port.c
- portable/RVDS/ARM_CM3/port.c
- portable/RVDS/ARM_CM4F/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM7/r0p1/port.c
- portable/Tasking/ARM_CM4F/port.c
The reason for the change is that the register is called System Handler Priority Register 3 (SHPR3).
> Update portNVIC_SYSPRI2_REG to portNVIC_SHPR3_REG

- portable/Common/mpu_wrappers.c
These definitions were not useful because the corresponding mapping was removed from `mpu_wrappers.h` earlier.
> Rmove MPU_pvPortMalloc and MPU_vPortFree from mpu_wrappers.c

- portable/GCC/AVR_AVRDx/port.c
- portable/GCC/AVR_AVRDx/porthardware.h
- portable/GCC/AVR_AVRDx/portmacro.h
- portable/GCC/AVR_Mega0/port.c
- portable/GCC/AVR_Mega0/porthardware.h
- portable/GCC/AVR_Mega0/portmacro.h
Portable files for AVR Mega0 and AVR Dx families using GCC compiler
Description
-----------
Mainly implements the context switching and tick generation. Several tick sources are available.
Test Steps
-----------
Use the related Atmel Studio projects that will be added to the FreeRTOS repo by another PR. These projects include a blinky example and a "minimal" and "full" test scenarios
> Added GCC port files for AVR Mega0 and AVR Dx.

- portable/ThirdParty/GCC/ARC_EM_HS/freertos_tls.c
- portable/ThirdParty/GCC/ARC_EM_HS/port.c
- portable/ThirdParty/GCC/ARC_EM_HS/portmacro.h
Description
-----------
embARC BSP has been updated, so the code here need a update too. 
Also remove an unused macro which could have caused warnings.
Something new to discuss
-----------------------------
- We have prepared two demos for customers to get hands on but not sure where to put the code. Please kindly advise. 
- We also have new supports for ARC v1 series processors, which are not in this PR. 
----------------
> Synopsys ARC update, with updated BSP support

- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/portasm.s
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
ARMv7-M supports 8 or 16 MPU regions. FreeRTOS Cortex-M4 MPU ports so far assumed 8 regions. This change adds support for 16 MPU regions. The hardware with 16 MPU regions must define `configTOTAL_MPU_REGIONS` to 16 in their FreeRTOSConfig.h.
If left undefined, `configTOTAL_MPU_REGIONS` defaults to 8 for backward compatibility.
> Add support for 16 MPU regions to Cortex-M4 MPU ports

- portable/ARMv8M/non_secure/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
Description
-----------
`configSYSTICK_CLOCK_HZ` should be used to configure SysTick to support the use case when the clock for SysTick timer is scaled from the main CPU clock.
`configSYSTICK_CLOCK_HZ` is defined to `configCPU_CLOCK_HZ` when it is not defined in `FreeRTOSConfig.h`.
> Use configSYSTICK_CLOCK_HZ to configure SysTick

- portable/Common/mpu_wrappers.c
Description
-----------
The expected behavior of `portIS_PRIVILEGED` is:
* return 0 if the processor is not running privileged.
* return 1 if the processor is running privileged.
Some TI ports do not return 1 when the processor is running privileged causing the following check to fail: `if( xRunningPrivileged != pdTRUE )`.
This commit change the check to: `if( xRunningPrivileged == pdFALSE )`. It ensures that the check is successful even on the ports which return incorrect value from `portIS_PRIVILEGED` when the processor is running privileged.
See https://forums.freertos.org/t/kernel-bug-nested-mpu-wrapper-calls-generate-an-exception/10391
> Change the xRunningPrivileged check from "!=true" to "==false"

- portable/IAR/ARM_CM0/port.c
IAR EW in release 8.50.5 modified behaviour of weak declaration "#pragma weak".
Description
-----------
IAR EW release 8.50.5 causing build error in case of FreeRTOS  IAR ARM_CM0 port.
Error[Li006]: duplicate definitions for "vPortSetupTimerInterrupt"; in "c:test\boards\<someM0board>\rtos_examples\freertos_tickless\cm0plus\iar\debug\obj\fsl_tickless_lptmr.o", and "c:test\boards\someM0board\rtos_examples\freertos_tickless\cm0plus\iar\debug\obj\port.o"
To fix the issue use __weak in function definition instead.
Test Steps
-----------
Build FreeRTOS with ARM_CM0 port in IAR 8.50.5 with custom non-weak declaration of vPortSetupTimerInterrupt in application.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Error in ARM_CM0 port compiled with IAR 8.50.5.

- portable/GCC/AVR_AVRDx/port.c
- portable/GCC/AVR_AVRDx/porthardware.h
- portable/GCC/AVR_AVRDx/portmacro.h
- portable/GCC/AVR_Mega0/port.c
- portable/GCC/AVR_Mega0/porthardware.h
- portable/GCC/AVR_Mega0/portmacro.h
- portable/IAR/AVR_AVRDx/port.c
- portable/IAR/AVR_AVRDx/porthardware.h
- portable/IAR/AVR_AVRDx/portmacro.h
- portable/IAR/AVR_AVRDx/portmacro.s90
- portable/IAR/AVR_Mega0/port.c
- portable/IAR/AVR_Mega0/porthardware.h
- portable/IAR/AVR_Mega0/portmacro.h
- portable/IAR/AVR_Mega0/portmacro.s90
Update to AVR_Mega0 and AVR_Dx GCC ports + addition of their IAR equivalents
Description
-----------
Update to AVR_Mega0 and AVR_Dx GCC ports: indentation and removal of TICK_stop() macro (not used anywhere)
Addition of their IAR equivalents
> Update to AVR_Mega0 and AVR_Dx GCC ports + addition of their IAR equivalents

- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
The TEX,  Shareable (S), Cacheable (C) and Bufferable (B) bits define the memory type, and where necessary the cacheable and shareable properties of the memory region.
The default values for these bits, as configured in our MPU ports, are sometimes not suitable for application. One such example is when the MCU has a cache, the application writer may not want to mark the memory as shareable to avoid disabling the cache. This change allows the application writer to override default vales for TEX, S C and B bits for Flash and RAM in their `FreeRTOSConfig.h`. The following two new configurations are introduced:
* `configTEX_S_C_B_FLASH`
* `configTEX_S_C_B_SRAM`
If undefined, the default values for the above configurations are TEX=000, S=1, C=1, B=1. This ensures …
> Allow application to override TEX,S,C and B bits for Flash and RAM

- tasks.c
First 1-line fix:
ulTaskGenericNotifyValueClear() returned the notification value of the
currently running task, not the target task.  Now it returns the
notification value of the target task.
second 1-line fix:
Some users expected xTaskCheckForTimeOut() to clear the 'last wake time'
value each time a timeout occurred, whereas it only did that in one path.
It now clears the last wake time in all paths that return that a timeout
occurred.
> Fix: 2 1-line fixes, xTaskCheckForTimeOut() and ulTaskGenericNotifyStateClear()

- portable/GCC/ARM_CR5/port.c
I discovered a very snicky and tricky race condition scenario when integrating tracealyzer code into our project.
I suspect it might be a problem with other ports as well that behave like the CortexR5
A little background  on CortexR5 : When the IRQ line (comming from the interrupt controller, to which every peripheral IRQ lines connect) of the processor rises and the IRQ Enable bit in the status register of the CPU permits it, the CPU traps into interrupt mode. Several things happen. First, the CPU finishes the instruction it was performing. Second, it places the content of the CPSR register into the SPSR_irq register. And third, the mode of the CPU is changed to IRQ_Mode and /!\ THE IRQ ENABLE BIT IN CPSR_irq IS AUTOMATICALLY CLEARED /!\ . The reason is to ensure that upon landing into …
> Fix race condition when tracing is enabled

- stream_buffer.c
xStreamBufferSend deadlock avoidance when sending too much data
Description
-----------
Add necessary checks when sending data to the stream/message buffer in order to avoid a task deadlock when attempting to write a longer stream/message than the underlying buffer can write.
In the case of the stream buffer, if the user tries to write more bytes than supported, the added code will truncate the stream and adapt the 'xRequiredSpace' variable to the size of the buffer. The user will be able to deal with this scenario by wrapping the call to 'xStreamBufferSend' in appropriate looping code. 
In the case of the message buffer, as opposed to stream buffer, there is no choice but to write the whole message (plus a uint32_t for it's length). In this case, the added code will do that 0 will be …
> Fix deadlock when writing more bytes to stream buffer than it's size

- stream_buffer.c
Description
-----------
In response to the comment https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/61fc74f0c5c50a7d8ac7fa7f4a2f6deb3a215036 "can you fix TRUE/FALSE to pdTRUE/pdFALSE - this broke things for me, thanks"
Test Steps
-----------
Rebased one of my local projects, and it's now compiling.
Related Issue
-----------
PR #94 
> Use pdTRUE/pdFALSE instead of TRUE/FALSE in xStreamBufferSend().

- portable/GCC/RX700v3_DPFPU/port.c
- portable/GCC/RX700v3_DPFPU/portmacro.h
- portable/IAR/RX700v3_DPFPU/port.c
- portable/IAR/RX700v3_DPFPU/portmacro.h
- portable/Renesas/RX700v3_DPFPU/port.c
- portable/Renesas/RX700v3_DPFPU/port_asm.src
- portable/Renesas/RX700v3_DPFPU/portmacro.h
Description
As I told to Richard in the following thread, I'd like to post a pull request to add Renesas RXv3 port layer supporting RXv3's double precision FPU. I'll post one more pull request to add RTOS Demo using this port layer.
Any plan of Renesas RXv3 port layer supporting RXv3's double precision FPU?
[https://forums.freertos.org/t/any-plan-of-renesas-rxv3-port-layer-supporting-rxv3s-double-precision-fpu/9931](https://forums.freertos.org/t/any-plan-of-renesas-rxv3-port-layer-supporting-rxv3s-double-precision-fpu/9931)
This port layer is derived from Renesas RXv2 port layer by adding Cortex-A9's FPU support code of GCC port layer. Added code is not the same as Corteax-A9's FPU support code because CPU is not Cortex-A9 but RXv3 and more efficient code was discussed in the above …
> Add Renesas RXv3 port layer supporting RXv3's double precision FPU

- include/croutine.h
- include/event_groups.h
- include/message_buffer.h
- include/queue.h
- include/semphr.h
- include/task.h
No code changes. Only in-comment changes.
Cleanup of PR #67. Modified to retain leading asterisk in `<pre>` blocks. In that PR, it was reported leading asterisk affected generated html. I was unable to reproduce those issues, and the generated html appeared OK. This may be a doxygen versioning/settings issue. See `Test Steps` section below.
Description
-----------
- Some functions were missing `<pre><\pre>` wrappers. These wrappers were added
- `<pre>` blocks can be placed on separate lines, rather than inline. Improves doxygen code readability while retaining presentation
- Some functions were missing a `;` at the end of the doxygen function signature. The semicolons were added for consistency with other signatures  
**Note:** Neither PR #67 nor this PR contain changes to `<PRE>` tags. …
> Doxygen touch-ups

- portable/GCC/RX100/port.c
- portable/GCC/RX100/portmacro.h
- portable/GCC/RX200/port.c
- portable/GCC/RX200/portmacro.h
- portable/GCC/RX600/port.c
- portable/GCC/RX600/portmacro.h
- portable/GCC/RX600v2/port.c
- portable/GCC/RX600v2/portmacro.h
Update Renesas GCC compiler ports
Description
-----------
This contains the changes for Renesas GCC compiler ports, authored in PR #89, rebased to latest master branch.  Also it fixes the ports as per the [proposal](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/89#issuecomment-660153971) in the PR
Test Steps
-----------
Demos for Renesas GCC compiler ports fails without the fix mentioned above.
https://github.com/FreeRTOS/FreeRTOS/tree/master/FreeRTOS/Demo/RX200_RX231-RSK_GCC_e2studio_IAR
https://github.com/FreeRTOS/FreeRTOS/tree/master/FreeRTOS/Demo/RX600_RX64M_RSK_GCC_e2studio
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/89
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Update Renesas GCC compiler ports

- portable/GCC/ARM_CM4F/portmacro.h
Add Parenthesis around if-statement in macro
Description
-----------
Add Parenthesis around if-statement in macro
Related Issue
-----------
#66 
> Fix: Add Parenthesis around if-statement in macro

- portable/MSVC-MingW/port.c
Root cause: Sleep() in Windows is not guaranteed to be realtime. Usage of Sleep()
was causing ticks in Windows port to be incorrect.
Solution: Use Waitable Timer in Windows for more accuracy.
Contribution by leegeth
> Fix inaccurate ticks in windows port

- portable/MSVC-MingW/port.c
Backing this out to merge it after the next Kernel release
> Revert "Fix inaccurate ticks in windows port (#142)"

- include/projdefs.h
Description
-----------
Code which uses `pdMS_TO_TICKS()` will receive a MISRA 10.4 violation since it uses a signed constant.  This change makes the constant unsigned.
Test Steps
-----------
Related Issue
-----------
> Use unsigned constant in pdMS_TO_TICKS().

- portable/GCC/ARM_CR5/port.c
This reverts commit 61635d5b8b7ae1e783026f37eb66757509010130.
We have some doubts on this one - it seems like fixing a symptom not a cause - and uses invalid data types .  We will revert this one for now and plan to investigate fully.
> Revert "Fix race condition when tracing is enabled (#95)"

- portable/GCC/ARM_CM4F/portmacro.h
Reverts FreeRTOS/FreeRTOS-Kernel#138
> Revert "Fix: Add Parenthesis around if-statement in macro"

- portable/MSVC-MingW/portmacro.h
Use lower case filename for MinGW port to make is compatiable with GNU/Linux.
The Windows.h file provided with Microsoft's tools have used a variety of cases.
old VC++ installations (VC++98 and earlier) use WINDOWS.H 
newer VC++ installations and Windows SDKs use Windows.h
some mobile device SDKs (PocketPC or Windows mobile) use windows.h
The MinGW windows.h header always seems to be lower case. Since windows.h will always work on both Windows and a Linux cross compile, so we make it with all lowercase.
REF:  https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/119
----
> Use lower case filename for MinGW port

- History.txt
- tasks.c
The following code was used to force an assert but resulted in
compiler warnings on 64-bit architectures:
configASSERT( pxTCB->ulNotifiedValue[ uxIndexToNotify ] == ~0UL );
Hence it was replaced with the following, which also forces an assert,
but ensure the data types being compared are the same on all
architectures:
configASSERT( xTickCount == ( TickType_t ) 0 );
> Fix compiler warning in config assert() on 64 bit architecture

- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/utils/wait_for_event.c
- portable/ThirdParty/GCC/Posix/utils/wait_for_event.h
Change the Linux Port to use condition variables instead of Signals
Description
-----------
Change the Linux Port to use condition variables instead of Signals
For some reason signals were found not to work as expected on MacOS, so we have decided to use condition variables instead of signals to resume and pause threads to simulate FreeRTOS Tasks
Test Steps
-----------
Ran the Demos on Linux, Mac and Windows under WSL
> Change the Linux Port to use condition variables instead of Signals

- portable/GCC/RISC-V/port.c
- portable/GCC/RISC-V/portASM.S
- add support for RV32E core for GCC compiler
- add support  for FPU (simple and double precision) for GCC compiler
Description
-----------
Change vPortSetupTimerInterrupt in order to support 64bits RISC-V and modify mtime writing on 32bits RISC-V
Change portASM.s in order to support RV32E (16 registers instead of 32 registers on RV32I)
Change portASM.s in order to save/restore FPU registers on simple/double precision
Test Steps
-----------
tested on ARTY board with SIFIVE standard core E31, U54, S54 plus custom core with FPU (simple/double precision)
use "example-freertos-blinky" from freedom-e-sdk from SIFIVE (This change have not been yet committed into our public release, do not hesitate to communicate with me if you want to test it).
Related Issue
-----------
NONE
By submitting this …
> RISC-V: Add RV32E / FPU support for GCC

- portable/ThirdParty/GCC/Posix/FreeRTOS-simulator-for-Linux.url
Adding a URL link to the Linux Port documentation
> Add url link for Linux Port documentation

- portable/ThirdParty/GCC/Posix/port.c
Comment - xTaskIncrementTick loop - to adhere to demo requirement
Description
-----------
Commenting xTaskIncrementTick loop to adhere to the demo requirement
Test Steps
-----------
full demo run
```
[Posix_GCC]$ ./build/posix_demo
Trace started.
The trace will be dumped to disk if a call to configASSERT() fails.
The trace will be dumped to disk if Enter is hit.
Starting full demo
OK: No errors - tick count 10000
OK: No errors - tick count 20000
OK: No errors - tick count 30000
```
> Fix: Comment - xTaskIncrementTick loop - to adhere to demo requirement

- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
This PR fixes broken #warning message in ARM_CMx_MPU/portmacro.h which was broken between 10.3.1 and 10.4.0.
Before this PR
#warning "~~~. https: /*www.FreeRTOS.org/FreeRTOS-V10.3.x.html" */
After this PR
#warning "~~~. https://www.FreeRTOS.org/FreeRTOS-V10.3.x.html"
The souce code were as follows:
#warning message in 10.4.0
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/85768bb3e02440f1432fb3ae913d84a72e982736/portable/GCC/ARM_CM3_MPU/portmacro.h#L300
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/85768bb3e02440f1432fb3ae913d84a72e982736/portable/GCC/ARM_CM4_MPU/portmacro.h#L389
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/85768bb3e02440f1432fb3ae913d84a72e982736/portable/IAR/ARM_CM4F_MPU/portmacro.h#L337 …
> Fix broken #warning message in ARM_CMx_MPU/portmacro.h between 10.3.1 and 10.4.0

- include/task.h
Rename parameter  `uxIndexToNotify` to `uxIndexToWaitOn`
Description
-----------
This fixes the bug that, the  parameter passed from the macro `ulTaskNotifyTakeIndexed` to `ulTaskGenericNotifyTake()` was incorrectly named as `uxIndexToNotify`.
Test Steps
-----------
Enable task notifications array feature in `FreeRTOSConfig.h` as follows:
```
#define configUSE_TASK_NOTIFICATIONS 1
#define configTASK_NOTIFICATION_ARRAY_ENTRIES 5
```
Calling the API `ulTaskNotifyTakeIndexed()` from the code, will  give a compilation error:
```
error: ‘uxIndexToNotify’ undeclared (first use in this function)
```
Related Issue
-----------
Issue was referenced in this forum post: https://forums.freertos.org/t/task-h-error-uxindextonotify-undeclared/10689
By submitting this pull request, I confirm that you can …
> Fix: Rename parameter  uxIndexToNotify to uxIndexToWaitOn

- History.txt
Updated wording of ulTaskNotifyTakeIndexed fix
> Updated wording of ulTaskNotifyTakeIndexed fix

- portable/GCC/RX100/readme.txt
- portable/GCC/RX600/readme.txt
- portable/GCC/RX600v2/readme.txt
- portable/GCC/RX700v3_DPFPU/readme.txt
- portable/IAR/RX100/readme.txt
- portable/IAR/RX600/readme.txt
- portable/IAR/RX700v3_DPFPU/readme.txt
- portable/IAR/RXv2/readme.txt
- portable/Renesas/RX100/readme.txt
- portable/Renesas/RX200/readme.txt
- portable/Renesas/RX600/readme.txt
- portable/Renesas/RX600v2/readme.txt
- portable/Renesas/RX700v3_DPFPU/readme.txt
Description
-----------
This PR adds readme.txt in each Renesas RX folder containing a table to show which port is recommended to be used.  All readme.txt are the same file.
Test Steps
-----------
None.
Related Issue
-----------
[BUG] The newly added GCC/RX200 port is wrong. https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/139
> Maintenance: Add readme.txt in each Renesas RX folder to show recommended port

- portable/MPLAB/PIC32MX/port.c
Description
-----------
The stack of a task was not 8 byte aligned. Adding one more unused space at the beginning of task stack (before simulated context) ensures that the stack is 8 byte aligned. The stack (with simulated context) of a newly created task looks like the following:
```
+------------+
| UNUSED     |
+------------+
| UNUSED     |
+------------+
| 0xDEADBEEF |
+------------+
| 0x12345678 |
+------------+
| CAUSE      | <-- SP After Context Restore
+------------+
^   | STATUS     |
|   +------------+
|   | EPC        |
|   +------------+
|   | ra         |
|   +------------+
|   | s8         |
|   +------------+
|   | t9         |
|   +------------+
|   | t8         |
|   +------------+
|   | t7         |
|   +------------+
|   | t6         |
|   +------------+
|   | t5 …
```
> Fix Stack alignment for Microchip PIC32MX port

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
In Posix Simulator on Linux, the memory allocated by idle and first task is not freed properly after ending the scheduler. Also the memory allocated for the condition variable is not freed in case of deleting a task from another task. This is needed to avoid memory leaks errors when memory checkers (Valgrind, address sanitizer, ..) are used. This pull request is solving this issue.
Test Steps
-----------
Use the FreeRTOS Posix Simulator on Linux and run it under Valgrind or use address sanitizer. Make sure no memory leaks errors after deleting a task from another task (not just a task deletes itself) and after ending the scheduler.
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
> Posix: Free the allocated memory after deleting a task or ending the scheduler

- tasks.c
Description
-----------
Re-introduce `uxTopUsedPriority` for use by OpenOCD. 
The kernel tracks _Ready_ tasks via priority lists. For tracking the state of remote threads, OpenOCD uses `uxTopUsedPriority` to determine the number of priority lists to read back from the remote target. 
See OpenOCD's [FreeRTOS.c](https://sourceforge.net/p/openocd/code/ci/master/tree/src/rtos/FreeRTOS.c)
Test Steps
-----------
Build any project and verify the presence of `uxTopUsedPriority` in the executable's symbol table. 
To exercise OpenOCD awareness of FreeRTOS threads, add `-rtos FreeRTOS` in your call to `configure` within your `openocd.cfg` config file. 
**example-openocd.cfg** (snippet):
```cfg
$_TARGETNAME.0 configure -rtos FreeRTOS -work-area-phys 0x80000000 -work-area-size 0x4000 -work-area-backup …
```
> OpenOCD Support: Re-introduce uxTopUsedPriority

- stream_buffer.c
Shorted overly verbose and opinionated comments in xStreamBufferSend().
Remove the unnecessary xIsFeasible variable from xStreamBufferSend().
> Tidy up xStreamBufferSend() - no function changes

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
When the main function of a task exits, no task switching happened.
This is because all the remaining tasks are waiting on the condition
variable. The fix is to trigger a task switch and mark the exiting
task as "Dying" to be suspened and exited properly from the scheduler.
Test Steps
-----------
Create an application with multi tasks. Make one task to exit normally from its main function. Then no task switching will happen.
Related Issue
-----------
> Posix: Fix no task switching issue if a task ended its main function

- portable/Common/mpu_wrappers.c
xTaskGetCurrentTaskHandle() had an additional conditional controlling its inclusion in the source code.
This change adds the same conditional to the MPU version of that function.
> matching the preprocessor conditionals for xTaskGetCurrentTaskHandle()

- include/task.h
This PR has no functional changes.  It just tidies up the formatting (mixed tabs and spaces, etc.) and MISRA compliance of the PR used to update vTaskDelayUntil() to xTaskDelayUntil().
> Minor updates to formatting and MISRA compliance xTaskDelayUntil

- include/FreeRTOS.h
- include/mpu_prototypes.h
- include/mpu_wrappers.h
- include/task.h
- portable/Common/mpu_wrappers.c
- tasks.c
Description
-----------
Recently vTaskDelayUntil() was updated to xTaskDelayUntil() because the function now returns a value.  The PR didn't make the same change in the MPU port, or update the constants required to include the xTaskDelayUntil() function in the build.
This PR:
Changes the INCLUDE_vTaskDelayUntil compile time constant to INCLUDE_xTaskDelayUntil.
Updates FreeRTOS.h to ensure backward compatibility for projects that already have INCLUDE_vTaskDelayUntil defined.
Updates the MPU prototypes, wrapper and implementation to use the updated xTaskDelayUntil() function.
Related Issues
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/198
Test Steps
-----------
Tests to be checked into the FreeRTOS/FreeRTOS repository after this PR and consist of updates to the standard …
> Make FreeRTOSConfig.h and MPU port changes for xTaskCreateUntil updates.

- include/task.h
Fix C++ compiler warning when compiling task.h
Description
-----------
The Keil C166 EC++ compiler throws an error for each compilation unit that includes the task.h header file
Related Issue
-----------
#35 
> Fix: C++ compiler warning

- tasks.c
Description
-----------
If a higher priority task than the currently running task was resumed using `xTaskResumeFromISR` and the user chose to ignore the return value of `xTaskResumeFromISR` to initiate a context switch using `portYIELD_FROM_ISR`, we were not doing the context switch on the next run of the scheduler. This change fixes this by marking a yield as pending to ensure that the context switch is performed on the next run of the scheduler.
Related Issue
-----------
https://forums.freertos.org/t/issue-resuming-and-sending-a-message-to-a-task-from-an-isr-cortex-m4/10957/14
> Fix missed yield in xTaskResumeFromISR

- .github/workflows/ci.yml
Pass lexicon.txt as a parameter
Description
-----------
Pass lexicon as a parameter so that when it is not in its default optional location, it would fail the ci spell-check job, instead of just printing a list of words
Test Steps
-----------
Ci fails when a bad path is passed: 
```
Error: Process completed with exit code 1.
```
When passed the correct location
```
shell: /bin/bash -e {0}
```
> Fix: Pass lexicon.txt as a parameter

- portable/ThirdParty/GCC/Xtensa_ESP32/port.c
- portable/ThirdParty/GCC/Xtensa_ESP32_IDF3/port.c
- portable/ThirdParty/XCC/Xtensa/port.c
Upstream stack masking fix to GCC ports.
Description
-----------
Fixes a compiler error on XCC port and applies #117 and #118 to GCC ports.
Test Steps
-----------
Related Issue
-----------
> Upstream stack masking fix to GCC ports.

- portable/IAR/AVR_AVRDx/porthardware.h
- portable/IAR/AVR_Mega0/porthardware.h
porthardware.h file update for AVR Mega0 and Dx
Description
-----------
Solved warnings caused by multiple ioavr.h includes.
Test Steps
-----------
When compiling there are no warnings related to double inclusion of ioavr.h file.
> porthardware.h file update for AVR Mega0 and Dx

- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portasm.c
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33/portasm.s
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33_NTZ/portasm.s
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/portasm.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/portasm.s
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/portasm.s
Description
-----------
Critical sections in FreeRTOS are implemented using the following two functions:
```c
void vPortEnterCritical( void )
{
portDISABLE_INTERRUPTS();
uxCriticalNesting++;
}
void vPortExitCritical( void )
{
uxCriticalNesting--;
if( uxCriticalNesting == 0 )
{
portENABLE_INTERRUPTS();
}
}
```
`uxCriticalNesting` is initialized to a large value at the start and set to zero when the scheduler is started (`xPortStartScheduler`). As a result, before the scheduler is started, a pair of enter/exit critical section will leave the interrupts disabled because `uxCriticalNesting` will not reach zero in the `vPortExitCritical` function. This is done to ensure that the interrupts remain disabled from the time first FreeRTOS API is called to the time when the scheduler is started. The …
> Ensure interrupts are enabled at first task start

- .github/workflows/header-checks.yml
Similar to https://github.com/FreeRTOS/FreeRTOS/pull/408.
Except no need to add script as it's sourced from `FreeRTOS/FreeRTOS`.
The workflow is only _slightly_ different in that it adds `--kernel` option to header checker (Different headers for kernel)
> Add kernel header check workflow

- include/mpu_prototypes.h
- include/mpu_wrappers.h
- portable/Common/mpu_wrappers.c
Description
-----------
This change removes the FreeRTOS System Calls (aka MPU wrappers) for the following kernel APIs:
- xTaskCreateRestricted
- xTaskCreateRestrictedStatic
- vTaskAllocateMPURegions
A system call allows an unprivileged task to execute a kernel API which is otherwise accessible to privileged software only. The above 3 APIs can create a new task with a different MPU configuration or alter the MPU configuration of an existing task. This an be (mis)used by an unprivileged task to grant itself access to a region which it does not have access to.
Removing the system calls for these APIs ensures that an unprivileged task cannot execute this APIs. If an unprivileged task attempts to execute any of these API, it will result in a Memory Fault.
By submitting this pull request, I …
> Prevent unprivileged task from altering MPU configuration

- portable/MemMang/heap_1.c
- portable/MemMang/heap_2.c
- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
This PR improves the heap2 bounds checking. There was a mostly theoretical case where an overflow could occur if the size of the requested memory block is between 4,294,967,288 and 4,294,967,296 bytes.
> Improve heap2 bounds checking

- stream_buffer.c
Add addition overflow check for stream buffer for the mostly theoretical case where you are allocating close to 4,294,967,296 bytes and the size_t rolls over.
> Add addition overflow check for stream buffer

- queue.c
Add assert to guard against addition overflow in queue create
> add assert for addition overflow on queue creation

- portable/ThirdParty/GCC/Posix/port.c
Comment and remove unused variables
Description
-----------
Removing an unused variable
Commenting 2 others as they are part of a commented code that was made in a certain way to be compatible with the demo timing requirements.
Do not cancel the idle task if FreeRTOS is compiled without an idle task
Related Issue
-----------
https://forums.freertos.org/t/posix-port-compile-issues/11323/4
> Posix Port: Comment and remove unused variables

- portable/ThirdParty/GCC/ARM_CM33_TFM/README.md
Align the TF-M version of the integration with kernel to version TF-Mv1.2.0
TF-M released the tag: TF-Mv1.2.0 version. This pull request is to align the TF-M to that version in the integration of TF-M and Kernel which is located at ./portable/ThirdParty/GCC/ARM_CM33_TFM.
> Align the TF-M version of the integration with kernel to version TF-Mv1.2.0

- .github/workflows/ci.yml
- .github/workflows/kernel-checks.yml
Fix Github checks after move from master to main
Description
-----------
Fix Github checks after move from master to main
Test Steps
-----------
github checks should run and pass
> Fix Github checks after move from master to main

- include/message_buffer.h
Description
-----------
This change fixes some minor cosmetic typos with extra unmatched braces in the `<pre>` tags of comments.
Related Issue
-----------
Somewhat related to the clean-up efforts in #130
> Remove unmatched braces in MessageBuffer pre tags

- .github/lexicon.txt
- include/FreeRTOS.h
- include/portable.h
- tasks.c
Description
-----------
The change adds support for allocating task stacks from separate heap. When  `configSTACK_ALLOCATION_FROM_SEPARATE_HEAP` is defined as 1 in `FreeRTOSConfig.h`, task stacks are allocated and freed using `pvPortMallocStack` and `vPortFreeStack` functions. This allows the application writer to provide a separate allocator for task stacks.
When `configSTACK_ALLOCATION_FROM_SEPARATE_HEAP` is defined as 0, task stacks are allocated and freed using FreeRTOS heap functions `pvPortMalloc` and `vPortFree`.
For backward compatibility, `configSTACK_ALLOCATION_FROM_SEPARATE_HEAP` defaults to 0.
This change was originally submitted in this PR: https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/262
> Support allocating stack from separate heap

- include/task.h
This change fixes the documentation for ulTaskNotifyTake() and ulTaskNotifyTakeIndexed().
This issue was discovered by Jim Yuill in [this](https://forums.freertos.org/t/possible-bug-in-ultasknotifytake-it-can-return-incorrectly-when-the-notification-value-is-0/11774) forum post.
> fixed documentation for ulTaskNotifyTake() and ulTaskNotifyTakeIndexed()

- .github/workflows/ci.yml
Added git-secrets check to Github Actions
Description
-----------
The added Github action will check and report PR check failure if a credential is committed into the repository.
Test Steps
-----------
Check the Github Actions to see the git-secrets check result
Related Issue
-----------
> Added git-secrets check to Github Actions

- tasks.c
Fix code comment for xTaskAbortDelay
Description
-----------
The comment does not reflect the code being performed, fixing the comment
> Comment: fix code comment for xTaskAbortDelay

- .github/workflows/ci.yml
- .github/workflows/git-secrets.yml
Moved git-secrets check to a different workflow
Description
-----------
Now git-secrets check will be performed on push and pull-request on all branches.
Test Steps
-----------
Check the latest Github Action for the latest results
Related Issue
-----------
> Moved git-secrets check to a different workflow

- .github/lexicon.txt
- queue.c
- tasks.c
Add some assertions and coverage exceptions to queue.c
Description
-----------
* Correct some typos in queue.c
* Assert that the semaphore handle passed into xQueueGetMutexHolder is not NULL.
* Add assertions to check when invalid parameters are passed into Queue Registry related functions.
* Add a configASSERT when vQueueAddToRegistry is called but the queue registry is full.
* Add LCOV_BRANCH coverage exception for a configASSERT on pxQueueSetContainer with a condition that is unreachable.
* Add an LCOV_BRANCH exception for the check that sizeof( StaticQueue_t ) == sizeof( Queue_t )
* Run uncrustify
Test Steps
-----------
Only assertions and comments have been changed. This should be verified by inspection.
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Add some assertions and coverage exceptions to queue.c

- list.c
Description
-----------
The tick interrupt priority must be configured to ensure that it cannot interrupt a critical section. This change updates the comment to help the application writer while debugging.
This change was originally contributed by @lagerholm in https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/215.
> Update comment in list.c

- stream_buffer.c
Description
-----------
PR includes following changes:
* Update comments in stream buffer code.
* Removes redundant check within stream buffer create static function.
* Fixes an edge case when trigger level is set equal to stream buffer size + 1
* Fixes a read before null check in stream buffer send API.
> Improve comments and assertions in stream buffer

- .github/workflows/unit-tests.yml
Run CMock unit tests on each pull request with a github action.
Description
-----------
This PR adds a github workflow that runs the kernel CMock unit tests located in the FreeRTOS/FreeRTOS repository on each push to FreeRTOS / FreeRTOS-Kernel.
This workflow also uploads test coverage data to codecov.io so that it can be easily reviewed. Optionally, codecov.io can add a comment to the PR outlining the changes in coverage before and after the changes in the PR.
Test Steps
-----------
N/A
> Run CMock unit tests on each pull request with a github action.

- tasks.c
xTaskResumeAll: comment: doesn't match the code
Description
-----------
xTaskResumeAll: comment: doesn't match the code
comment says greater than
while code says greater than or equal
> Comment: xTaskResumeAll: comment: doesn't match the code

- portable/GCC/ATMega323/portmacro.h
portPOINTER_SIZE_TYPE wasn't yet set correctly to be 16 bit
Description
Adjusted portmacro for ATMega323 port to contain the correct pointer size.
Test Steps
-----------
Build a demo for this port and observe that there are no warnings anymore regarding some casts in heap_1.c and tasks.c.
Related Issue
-----------
none found
> Adjust portPOINTER_SIZE_TYPE to correct size

- include/mpu_wrappers.h
testing for mpu wrapers to be equal to 1
Description
-----------
Testing for mpu wrapers to be equal to 1 similar to how portable.h is testing for the definition
as it might cause some issues with CPPFLAGS including it if defined to be zero
> Fix: testing for mpu wrapers to be equal to 1

- include/FreeRTOS.h
The FreeRTOS/FreeRTOS hub repo, which submodules the kernel from this repo, got updated to include a new compile time constant configRUN_ADDITIONAL_TESTS.  The constant allows new tests to be optionally inserted into pre-existing tests.  The purpose is to ensure exist port specific test and demo projects do not include the new tests until they are next executed - at which time it can be validate that the additional resources required to run the tests can be allocated without resource exhaustion.  This PR defaults configRUN_ADDITIONAL_TESTS to 0 for all projects that do not yet use the constant.
Test Steps
-----------
Not applicable.
Related Issue
-----------
Not applicable.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Add default for the new constant configRUN_ADDITIONAL_TESTS into FreeRTOS.h

- stream_buffer.c
Description of original issue
-----------
There are a few sections of message buffer code that are vulnerable to race conditions. The underlying cause is that length and data bytes are written and read as two distinct operations, which both modify the size of the buffer. If a context switch occurs after adding or removing the length bytes, but before adding or removing the data bytes, then another task may observe the message buffer in this invalid state, and could further corrupt the contents with another buffer-modifying operation.
Here are some specific examples of how things can go wrong:
**Corruption due to Send in the middle of a Receive:**
```c
// Initial condition:
// 50-byte buffer contains a 20-byte message, plus 4-byte length overhead
// Task 1:
xStreamBufferReceive // to …
```
> Fix race condition bugs when reading and writing to message buffers

- stream_buffer.c
Description
-----------
PR #264 changed the way prvWriteMessageToBuffer() tested to see if the stream buffer was being used as a message buffer.  That update was incorrect and should not have been merged.  This change reverts to the original method.
Test Steps
-----------
Run the standard stream buffer tests in FreeRTOS/Demo/Common/Minimal/StreamBufferDemo.c.
Related Issue
-----------
#264 
> Fix error introduced when merging #264.

- timers.c
Remove redundant check
Description
-----------
every caller of prvInitialiseNewTimer is already checking if the value of  pxNewTimer is NULL before calling
prvInitialiseNewTimer is doing the same check.. removing
Test Steps
-----------
UT Coverage, cannot cover both branches of  
```c
if( pxNewTimer != NULL )
{
}
```
as it always evaluates  to true
> Code: Remove redundant check

- .github/workflows/kernel-checks.yml
- .github/workflows/unit-tests.yml
Build the posix port on pushes and PRs to the Kernel repository
Description
-----------
Build the posix port on pushes and PRs to the Kernel repository.
Also, run the kernel unit tests on a "push" and "pull_request".
> Build the posix port on pushes and PRs to the Kernel repository

- tasks.c
Description
-----------
Add assert to catch invalid task priority at the time of task creation.
> Add assert to catch invalid task priority

- include/list.h
- tasks.c
Fix comments in list.h and clarify list usage in xTaskRemoveFromEventList
Description
-----------
The vListInsert function in list.c implements an Insert operation for a linked list in ascending order rather than descending order as is stated in the comments in list.h. This PR fixes these comments.
Also clarify that an event list is sorted in ascending xItemValue order, but descending priority order as expected by xTaskRemoveFromEventList.
> Fix comments in list.h and clarify list usage in xTaskRemoveFromEventList

- event_groups.c
> Check NULL pointer input for vEventGroupDelete.

- include/FreeRTOS.h
- include/mpu_wrappers.h
- include/portable.h
Description
-----------
`configSTACK_ALLOCATION_FROM_SEPARATE_HEAP` was added recently in https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/267. This macro was used in `portable.h` before its default value was defined in `FreeRTOS.h`, resulting in a warning when built with `-Wundef`. This change moves the default value definition for `configSTACK_ALLOCATION_FROM_SEPARATE_HEAP` to `portable.h` to ensure that it is defined before first use.
`portUSING_MPU_WRAPPERS` check in `mpu_wrappers.h` was updated in https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/285. The new check results in a warning when built with `-Wundef` because `portUSING_MPU_WRAPPERS` is not defined yet. This change adds the default value definition for `portUSING_MPU_WRAPPERS` to `portable.h` to ensure that it is defined …
> Define default values of macros before first use

- .github/CONTRIBUTING.md
- .github/workflows/kernel-checks.yml
- .github/workflows/unit-tests.yml
- README.md
Update parent repository primary branch name from "master" to "main".
Description
-----------
The FreeRTOS/FreeRTOS repository changed its primary branch name from "master" to "main". This repository is needed for running Kernel Unit Tests on each PR. Update the reference to this branch name in the kernel unit tests github action configuration so that these tests can run successfully again.
> Update parent repository primary branch name from "master" to "main".

- include/queue.h
- queue.c
Description
-----------
Overwrite an existing entry for a given xQueue handle when vQueueAddToRegistry is called with an xQueue handle of a queue that is already in the Queue Registry.
Test Steps
-----------
Test will be updated in https://github.com/FreeRTOS/FreeRTOS/pull/552.
> Overwrite existing QueueRegistry entries when a handle is added multiple times.

- timers.c
Description
-----------
This PR is a potential replacement for #303 and fixes the same issues but using a more direct approach.
>Prior to this PR, if an application attempts to stop or delete an auto-reload timer while it is backlogged, the timer unexpectedly restarts. A timer is "backlogged" when at the time of the auto-reload, the new timer period has already elapsed. In the case of a deleted timer, the timer continues running using freed memory which may eventually lead to a crash or failure of other unrelated timers when the memory is reallocated.
This PR also fixes one-shot timers that were not being marked as inactive:
- when they expired before the start command could be processed
- when the expiration was processed during the timer list switch
and also improves consistency:
- …
> Remove support for tmrCOMMAND_START_DONT_TRACE

- queue.c
Replace configASSERT( pcQueueName ) in vQueueAddToRegistry with a NULL pointer check.
Description
-----------
Replace the configASSERT added to vQueueAddToRegistry with a NULL pointer check so that it does not break usage in https://github.com/ARM-software/CMSIS-FreeRTOS.
Test Steps
-----------
Unit test currently in a Pull Request will be updated.
Related Issue
-----------
Fixes #311
> Replace configASSERT( pcQueueName ) in vQueueAddToRegistry with a NULL pointer check.

- queue.c
Fix regression in vQueueAddToRegistry.
Description
-----------
This regression was introduced in https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/313.
Test Steps
-----------
Cmock test will be updated in https://github.com/FreeRTOS/FreeRTOS/pull/552.
> Fix regression in vQueueAddToRegistry

- .github/scripts/kernel_checker.py
- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/portmacro.h
This fixes compilation error when `configENABLE_BACKWARD_COMPATIBILITY` is 0.
> Posix: fix copyright

- tasks.c
Description
-----------
This change adds static allocation for all tasks.  It also creates an idle task for each core.  The first idle task is the same as the legacy idle task and performs housekeeping and calls the vApplicationIdleHook() function.  The remaining idle tasks are very light and only call taskYield if needed.
If static allocation is enabled, the first idle task will call the task allocator just like it has always done.  But each additional idle task will have the minimum stack memory (configMINIMAL_STACK_SIZE) statically allocated from within the start scheduler function.
Test Steps
-----------
This was tested with the XMOS port with 1, 3 and 7 cores active.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Static allocation and lightweight idle tasks

- History.txt
- include/task.h
Adding history.txt preparatory to releasing v10.4.4.
> Add history.txt for the 10.4.4 release

- .github/lexicon.txt
- include/semphr.h
Adds `uxSemaphoreGetCountFromISR` using `uxQueueMessagesWaitingFromISR`
Description
-----------
Noticed this ISR function was missing but the function it wraps (non-ISR ..GetCount function) does contain an ISR friendly prototype. 
Test Steps
-----------
NA
Related Issue
-----------
NA
> Adds SemphrGetCountFromISR with QMsgWaitingFromISR

- portable/ThirdParty/GCC/Posix/utils/wait_for_event.c
event_wait_timed() was ignoring a timeout of 1000 ms.
Presumably this is because pthread_cond_timedwait() only
considers tv_nsec less than one second.
Convert the timeout in miliseconds to second and nanosecond
components to fix this.
> Posix: fix event_wait_timed()

- .github/lexicon.txt
Description
-----------
To unblock this PR https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/353
Test Steps
-----------
Related Issue
-----------
> Update spell checker exclusion.

- portable/GCC/ARM_CA53_64_BIT_SRE/port.c
- portable/GCC/ARM_CA53_64_BIT_SRE/portASM.S
- portable/GCC/ARM_CA53_64_BIT_SRE/portmacro.h
Description
-----------
The difference between this port and the `portable/GCC/ARM_CA53_64_BIT` is that this port uses System Register interface to access CPU interface while the other one uses Memory-mapped interface.
> Add Cortex-A53 port with system register interface for CPU interface access

- event_groups.c
Description
-----------
This issue was reported here: https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/358
> Fix C90 Compilation Failure

- portable/ThirdParty/xClang/XCORE200/portasm.S
- portable/ThirdParty/xClang/XCOREAI/portasm.S
The kernel code that runs within RTOS ISRs requires that DP and CP not
be changed from their initial values. If a task changes them and is
interrupted while they are changed, then they must be restored for the
ISR. This commit implements this.
This relies on a corresponding change to the xcore lib_rtos_support.
Description
-----------
Test Steps
-----------
Related Issue
-----------
> Fix XCore DP/CP register corruption bug

- .gitmodules
Moves the Community-Supported-Ports and Partner-Supported-Ports modules from ThirdParty to portable/ThirdParty.
> Move the community/partner supported ports to correct location

- include/task.h
Description
-----------
This merely fixes the spelling of `affect` in the API documentation for `vTaskDelay`.
> Fix description of vTaskDelay

- include/event_groups.h
doc: fix function name typo
Description
-----------
Corrected spelling mistake xEventGropuCreate -> xEventGroupCreate
Noticed typo in the ESP IDF docs: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/freertos.html
esp-idf PR:
https://github.com/espressif/esp-idf/pull/7265
Test Steps
-----------
Not tested (very minor change to docs)
Related Issue
-----------
None
> doc: fix function name typo

- portable/ThirdParty/README.md
Add ReadMe for third party port contributions
> Add ReadMe for third party port contributions

- tasks.c
Allows for much easier assembly access to the `uxCoreAffinityMask` field. This allows for the port implementation to pin the task to one or more cores much easier and without relying on hardcoded field offset constants.
One such occasion would be in the ESP32 port. The ESP32 port needs to pin the task to a single core when the FPU is used in a multi-core environment. This is because each core has its own FPU where its contents are lazily saved and restored only upon usage. When a task is switched to another core in the middle of a floating-point calculation, the state remains in the other core. To work around this without pinning the core, one would need to either save the FPU state for every task context switch or use some cross-core interrupt magic.
By submitting this pull request, I …
> Move uxCoreAffinityMask after xMPUSettings

- include/FreeRTOS.h
Also updates the layout of `xSTATIC_TCB` in `FreeRTOS.h` to have the same layout as `tskTCB`, which I previously missed ([comment](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/372#issuecomment-894236193)).
> Update xSTATIC_TCB layout in line with tskTCB

- include/message_buffer.h
Fix in message buffer documentation
Description
-----------
Parameter name in documentation didn't match actual name in declaration
Test Steps
-----------
No additional test needed as it's minor change in comments.
Related Issue
-----------
> Fix in message buffer documentation

- portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h
- portable/ThirdParty/GCC/Xtensa_ESP32/port.c
Description
-----------
This change was not included when migrating to ESP-IDF v4.2
Test Steps
-----------
Enable SPIRAM on ESP32 in amazon-freertos
Related Issue
-----------
Fixes https://github.com/aws/amazon-freertos/issues/3353
> Xtensa_ESP32: Fix build issues when external SPIRAM is enabled

- include/queue.h
Parameter name fixes in queue documentation.
Description
-----------
Some parameter names in queue documentation were different than actual names in code.
Test Steps
-----------
No test needed as it's a minor documentation fix
Related Issue
-----------
> Parameter name fixes in queue documentation

- .github/lexicon.txt
- include/event_groups.h
Following discussion on the forum, this PR replaces \<pre> with @code{c}
Description
-----------
As discussed here:
https://forums.freertos.org/t/doxygen-tags-in-the-documentation/13244/2
This improves handling of code blocks in FreeRTOS documentation.
Test Steps
-----------
Check if internally generated FreeRTOS documentation is correct after this change.
Related Issue
-----------
> Replace <pre> with @code{c}

- include/croutine.h
- include/message_buffer.h
- include/queue.h
- include/semphr.h
- include/stream_buffer.h
- include/task.h
- include/timers.h
Description
-----------
This PR finalizes replacement of \<pre></pre> with doxygen's @code{c} @endcode in remaining files.
Test Steps
-----------
Check generated documentation
Related Issue
-----------
no issue
> Replace <pre> with @code - remaining files

- portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h
Description
-----------
Adding memory barrier fixes crash on Espressif SoC's when compiler optimisations are enabled.
This regression was introduced with https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/6bf3a75c6a46c1b6b38f5b55751ec4cfa6333fdd commit.
Due to optimisations, [assignment of pxTCB](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/1b86b39940c18f2bba6e577b007c430a65839e24/tasks.c#L2246) is moved outside while loop. Due to this, value of pxTCB is not loaded on each iteration of loop.
Related: https://github.com/aws/amazon-freertos/pull/3374
> Xtensa_ESP32: Add definition for portMEMORY_BARRIER

- tasks.c
Fix a typo in a comment in tasks.c
Description
-----------
Just fixed a typo.
Test Steps
-----------
None
Related Issue
-----------
None
> Fix typo in comment

- include/task.h
- tasks.c
Description
-----------
This PR adds the docs for newly added SMP APIs.
> Update SMP docs

- portable/GCC/ARM_CA53_64_BIT_SRE/portASM.S
Description
-----------
Mention that `FreeRTOS_IRQ_Handler` should not be used for FIQs and the reason for assuming Group 1 for Interrupt Acknowledge and End Of Interrupt registers.
> Update comments for the ARM_CA53_64_BIT_SRE port

- stream_buffer.c
prvWriteMessageToBuffer wrote the first sbBYTES_TO_STORE_MESSAGE_LENGTH
bytes of the size_t-typed length to the buffer as the data length. While
this functions on little endian, it copies the wrong bytes on big
endian. This fix converts the length to configMESSAGE_BUFFER_LENGTH_TYPE
first, and then copies the exact amount, thus fixing the issue.
Additionally it adds an assert to verify the size is not greater than
the max value of configMESSAGE_BUFFER_LENGTH_TYPE; previously this would
truncate silently.
Fixes https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/389.
> Fix prvWriteMessageToBuffer on big endian

- portable/MPLAB/PIC24_dsPIC/port.c
Description
-----------
Remove the use of MPLAB_DSPIC_PORT for determining correct stack initialisation, use the XC16 compiler device family macros instead.
Related Issue
-----------
[BUG] Stack initialisation incorrect on dsPIC. #404 
> bugfix: Initialise stack correctly on dsPIC port

- .github/lexicon.txt
- include/task.h
Description
-----------
Fix a mistake in the docs where `ulTaskNotifyTakeIndexed` is referred to as `ulTaskNotificationTakeIndexed`
Test Steps
-----------
None - only comments changed
> Fix documentation mistake

- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/utils/wait_for_event.c
- portable/ThirdParty/GCC/Posix/utils/wait_for_event.h
Build with -Wmissing-prototypes flags vPortYieldFromISR() in the Posix port.
There's already a portYIELD_FROM_ISR() macro that calls vPortYield() which wraps the FromISR code.
It doesn't appear that vPortYieldFromISR() is intended to be publicly accessible in this port so
I've marked it as private to silence the warning.
-----------
Flagged by -Wmissing-prototypes
-----------
> Fix prototype issue for the Posix port.

- include/event_groups.h
Description
-----------
The public function `xEventGroupWaitBits` passes `xTicksToWait` to the function `vTaskPlaceOnUnorderedEventList`, which passes the number of ticks to `prvAddCurrentTaskToDelayedList` and sets `xCanBlockIndefinitely` to `pdTRUE`, causing the latter to block indefinitely if `xTicksToWait == portMAX_DELAY` and `INCLUDE_vTaskSuspend == 1`.
Test Steps
-----------
This documents existing behavior only.
Related Issue
-----------
None.
---
<sub>By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.</sub>
> Mention portMAX_DELAY in xEventGroupWaitBits docs

- .github/lexicon.txt
- tasks.c
Description
-----------
uxTaskNumber member of struct tskTaskControlBlock is not initialized at thread creation.
As the TCB can be dynamically allocated, uxTaskNumber might then get a value from the heap.
As a result, the user might get a seems-valid value when calling uxTaskGetTaskNumber() and then take wrong decisions.
This fix zeroes uxTaskNumber when the task is initialized.
**Related:** ESP-IDF (FreeRTOS) [#4025](https://github.com/espressif/esp-idf/pull/4025)
> bugfix: Initialize uxTaskNumber at task initialization

- include/timers.h
Description
-----------
The example was trying to create a timer with period 0 which is not a valid period.
This was reported here - https://forums.freertos.org/t/multiple-timers/13884
> Fix code example in timers.h

- include/mpu_wrappers.h
- portable/Common/mpu_wrappers.c
- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
Description
-----------
This PR brings the fixes released in 10.4.6 to main:
* Change `xPortRaisePrivilege` and `vPortResetPrivilege` to macros.
* Add option to disable unprivileged critical sections.
> Apply fixes released in 10.4.6

- queue.c
Description
-----------
Move the configASSERT() call to after the variable declaration to prevent the following compiler error using the Keil tools:
..\..\..\Source\queue.c(2762): error:  #268: declaration may not appear after executable statement in block
> Fix keil compilation error

- include/timers.h
- tasks.c
Description
-----------
memset() newly allocated TCB structures to zero, and remove code that set individual structure members to zero.
Test Steps
-----------
Run through each of the four places TCB structures get populated in the debugger.
Run soak tests.
Related Issue
-----------
None.
> Simplify prvInitialiseNewTask()

- tasks.c
Fix #415: Compiling tasks.c with configSUPPORT_DYNAMIC_ALLOCATION = 0
Description
-----------
Add  conditionals to the declaration and definition of `prvWriteNameToBuffer` that match those of its callers.
Test Steps
-----------
Compile FreeRTOS-Kernel with configSUPPORT_DYNAMIC_ALLOCATION  = 0 and -Werror enabled.
Related Issue
-----------
None known.
> Fix #415: Compiling tasks.c with configSUPPORT_DYNAMIC_ALLOCATION = 0

- include/FreeRTOS.h
- include/task.h
- tasks.c
Remove tickless idle feature dependency with `INCLUDE_vTaskSuspend`
Description
-----------
There was a build error in `eTaskConfirmSleepModeStatus()` when `configUSE_TICKLESS_IDLE` is enabled. 
This was forcing user to enable `INCLUDE_vTaskSuspend` (set as 1).
This Pull request removes the need for  `INCLUDE_vTaskSuspend` to be set 1 when `configUSE_TICKLESS_IDLE` is enabled.
All codes accessing `xSuspendedTaskList` is now moved under` #if ( INCLUDE_vTaskSuspend == 1 ) `checks.
Test Steps
-----------
Use any of the FreeRTOS demo project.
Make these changes in `FreeRTOSConfig.h` file -
```
#define configUSE_TICKLESS_IDLE 	1
#define INCLUDE_vTaskSuspend		0
```
Build fails without changes in this PR
Related Issue
-----------
https://forums.freertos.org/t/tickless-idle-mode-and-vtasksuspend-d …
> Remove tickless idle mode dependency with include v task suspend

- portable/ThirdParty/GCC/RP2040/port.c
SMP: Bugfix for race condition on RP2040 in `vPortEnableInterrupts()` and invalid sanity checks
Description
-----------
1. RP2040 SMP port: Since `spin_unlock()` re-enables interrupts, `pxYieldSpinLock` has to be updated first to avoid a possible race condition in [ `vPortEnableInterrupts()` ](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/7d11089624cb18ef0052fd2fc96bb86d0d6d4109/portable/ThirdParty/GCC/RP2040/port.c#L378).
1. RP2040 SMP port: Testing `pxYieldSpinLock` for `NULL` does not work reliable in [ `vPortLockInternalSpinUnlockWithWait()` ](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/7d11089624cb18ef0052fd2fc96bb86d0d6d4109/portable/ThirdParty/GCC/RP2040/port.c#L787) and [ `xPortLockInternalSpinUnlockWithBestEffortWaitOrTimeout()` …
> smp branch: bugfix for race condition on RP2040

- include/event_groups.h
Description
-----------
The function xEventGroupClearBitsFromISR is missing the parameter xHigherPriorityTaskWoken.   This parameter cannot be added without breaking the API for this version of the kernel.  The documentation was updated to provide guidance on how to use this function without that parameter.
Related Issue
-----------
#93 
> Documentation update for xEventGroupClearBitsFromISR

- queue.c
Description
-----------
`cRxLock` and `cTxLock` members of the queue data structure count the number items received and sent to the queue while the queue was locked. These are later used to unblock tasks waiting on the queue when the queue is unlocked. The data type of these members is `int8_t` and this can trigger overflow check assert if an ISR continuously reads/writes to the queue in a loop as reported in [this issue ](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/419).  Note due to the length of the operation is it not recommended to write to the queue that many times from an ISR - stream buffers are a better option, or alternatively, defer the operation to a task by just having the ISR send a direct to task notification to unblock the task.
This PR caps the values of the …
> Add a cap to the queue locks

- .github/uncrustify.cfg
- History.txt
- event_groups.c
- include/FreeRTOS.h
- include/list.h
- include/projdefs.h
- list.c
- queue.c
- stream_buffer.c
- tasks.c
- timers.c
Description
-----------
Add configUSE_MINI_LIST_ITEM configuration option to enable the MiniListItem_t type.
When configUSE_MINI_LIST_ITEM == 0:
MiniListItem_t and ListItem_t are both typedefs of struct xLIST_ITEM.
When configUSE_MINI_LIST_ITEM == 1 (the default in projdefs.h):
MiniListItem_t is a typedef of struct xMINI_LIST_ITEM, which contains 3 fewer fields than a struct xLIST_ITEM.
This configuration saves approximately sizeof(TickType_t) + 2 * sizeof( void * ) bytes of ram, however it also violates strict aliasing rules which some compilers depend on for optimization.
configUSE_MINI_LIST_ITEM defaults to 1 when not defined.
Test Steps
-----------
Run unit tests.
Compile with both settings for configUSE_MINI_LIST_ITEM.
Related Issue
----------- …
> Add configUSE_MINI_LIST_ITEM configuration option to enable the MiniListItem_t type.

- portable/ARMv8M/non_secure/port.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM23/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM23_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33_NTZ/portmacro.h
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23/non_secure/portmacro.h
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/portasm.c
- portable/GCC/ARM_CM33/non_secure/portmacro.h
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM33_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/portmacro.h
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/portmacro.h
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/portmacro.h
Description
-----------
This PR adds support for 16 MPU regions to GCC Cortex-M33 ports.
> Add support for 16 MPU regions to GCC Cortex-M33 ports

- portable/GCC/RISC-V/portASM.S
Use a dedicated symbol for in-function loop to avoid the weak symbol JAL range error when a strong symbol is defined outside.
Description
-----------
Test Steps
-----------
Related Issue
-----------
> Use a dedicated symbol for in-function loop

- portable/MemMang/heap_2.c
- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
We use the MSB of the size member of a BlockLink_t to track whether not a block is allocated. Consequently, the size must not be so large that the MSB is set. The check to see if the MSB in the size is set needs to be done after the final size (metadata + alignment) is calculated.
> Move MSB check after final size calculation

- portable/MemMang/heap_2.c
- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
Update the size calculations such that we only need to check for add overflow only once. Also, change the way we detect add overflow so that we do not need to cause an overflow to detect an overflow.
> Check for add overflow only once

- tasks.c
When compiling with `configNUM_CORES == 1` and `configUSE_CORE_AFFINITY == 1`, `pxPreviousTCB` will generate a "set but unused" warning.
However, it doesn't really make sense for `configUSE_CORE_AFFINITY` to be set to `1` when `configNUM_CORES == 1`, so maybe the better solution is to have a check in `FreeRTOS.h` that forces `configUSE_CORE_AFFINITY` to `0` when `configNUM_CORES == 1`
> Fix pxPreviousTCB compile warning

- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4_MPU/port.c
Description
-----------
When link-time-optimization is enabled, we ran into issues with offset-out-of-range errors. There has been a previous fix for this issue (https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/71), which seems to be insufficient for the MPU ports.
This PR adds the fix of the previous PR, i.e., the `.ltorg` directive, to the remaining places where `LDR Rd, =label` is used (a pseudo instruction which utilizes the literal pool) in the GCC/ARM_CM3_MPU and ARM_CM4_MPU ports.
Test Steps
-----------
Related Issue
-----------
> fix: add additional .ltorg directives to GCC CM3/CM4 mpu ports

- include/task.h
- tasks.c
Description
-----------
We have some instances when a task function must be guaranteed to only ever run on a particular core such as:
- When the task function accesses some shared array indexed by  `xCoreID`
- When the task function accesses some per-cpu specific resources (such as coprocessors) 
The current task creation API expects users to set a task's affinity (using `vTaskCoreAffinitySet()`) after the task is created. For example, if Task A creates Task B using `xTaskCreate()`, Task A should then set the core affinity of Task B using `vTaskCoreAffinitySet()`.
However, as soon as Task B is created, it is possible for Task B to be scheduled on any core (as created tasks have no core affinity by default). Thus, extra logic is required in both Task A and Task B in order to guarantee that …
> SMP: Add task creation with affinity functions

- portable/Common/mpu_wrappers.c
Description
-----------
This prevents linker errors when this file is accidentally compiled in projects using non-MPU ports.
Test Steps
-----------
Tested compiling a both and MPU and non-MPU project.
> Add a guard around mpu_wrappers.c

- tasks.c
Description
-----------
Replace duplicated if branch because empty by a comment to avoid warning/error with option GCC -Wduplicated-branches
Test Steps
-----------
Build file with -Wduplicated-branches and -Werror with GCC
Related Issue
-----------
> tasks.c:2067:11: warning: this condition has identical branches [-Wduplicated-branches]

- portable/GCC/ARM_CM0/port.c
- portable/IAR/ARM_CM0/port.c
Description
-----------
This is needed to support the case when SysTick timer is not clocked from the same source as CPU. This support already exists in other Cortex-M ports.
Related Issue
-----------
https://forums.freertos.org/t/is-there-a-reason-m0-port-doesnt-respect-configsystick-clk-hz/14810
> Add configSYSTICK_CLOCK_HZ to Cortex-M0 ports

- portable/ThirdParty/XCC/Xtensa/xtensa_context.S
- portable/ThirdParty/XCC/Xtensa/xtensa_vectors.S
Patch submitted by customer on forums here: https://forums.freertos.org/t/cannot-compile-xtensa-port-assembly-with-text-section-literals/14838
> Enable use of --text-section-literals in Xtensa port

- include/mpu_prototypes.h
- include/mpu_wrappers.h
Correct spelling mistake in mpu_wrappers.h and mpu_prototypes.h.
Description
-----------
tasks.h doesn't exist.
Test Steps
-----------
N/A
Related Issue
-----------
N/A
> Correct spelling mistake in header files

- portable/MPLAB/PIC24_dsPIC/portmacro.h
Add atomic flag for 16-bit ticks
Description
-----------
This change allows the PIC24 family of
16 bit processors to read the tick count
without a critical section when the tick
count is also 16 bits.
Test Steps
-----------
Related Issue
-----------
Inspired from discussion - https://forums.freertos.org/t/xtaskgettickcount-with-critical-section-on-16-bit-mcu/14860/5
> Add atomic flag for 16-bit ticks PIC24

- include/queue.h
Typo in Documentation
Description
-----------
Replaced cTaskWokenByPost with cTaskWokenByReceive.
Test Steps
-----------
Typo in Doc - read it ;)
Related Issue
-----------
None
> cTaskWokenByPost -> xTaskWokenByReceive

- include/FreeRTOS.h
- tasks.c
Description
-----------
Currently, when `configUSE_NEWLIB_REENTRANT` is enabled, FreeRTOS will update Newlibs `_impure_ptr` on every context switch to point to the current task's `reent` struct. However, this behavior is no longer valid for SMP due to the fact that two or more cores can switch contexts, thus leading to a corrupted `_impure_ptr` (i.e., multiple cores cannot share the same `_impure_ptr`.
Newlib provides a `__DYNAMIC_REENT__` feature where all newlib functions will call a `__getreent()` function to get the required reentrancy structure instead of referring to the `_impure_ptr`. In case of FreeRTOS, it should just return the current core's current task's `reent` struct.
This commit adds the following changes:
- A `configNEWLIB_REENTRANT_IS_DYNAMIC` option to enable Newlib …
> Add Newlib dynamic reentrancy

- portable/ThirdParty/GCC/RP2040/port.c
Some state relating to atomically unlocking of a Raspberry Pi Pico SDK spin lock when suspending a FreeRTOS task was wrongly shared between cores causing undefined behavior if both cores happen to release spin locks at exactly the same time. This fix creates per core copies of the state.
> Fix RP2040 assertion due to yield spin lock info being wrongly shared between multiple cores

- include/semphr.h
Description
-----------
This PR adds the `configUSE_MUTEXES` guard to the function declarations in `semphr.h` which are only available when `configUSE_MUTEXES` is set to `1`.
It was reported here - https://forums.freertos.org/t/mutex-missing-reference-to-configuse-mutexes-on-the-online-documentation/15231
> Add configUSE_MUTEXES to function declarations in header

- tasks.c
Description
-----------
When configNUM_CORES is 1, `prvYieldCore()` generates an array subscript
outofbound error (`-Warray-bounds`) when compiled with GCC with space
optimization enabled (-Os).
This commit updates the code flow in `prvYieldCore()` to compile out
the part where yield is needed on the other core which is unnecessary
for single-core targets.
Test Steps
-----------
To generate the warning, compile FreeRTOS smp branch with GCC and -Os optimization enabled.
```
warning: array subscript [0, 0] is outside array bounds of 'TCB_t * volatile[1]' {aka 'struct tskTaskControlBlock * volatile[1]'} [-Warray-bounds]
716 |             pxCurrentTCBs[ xCoreID ]->xTaskRunState = taskTASK_YIELDING;
```
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> Update prvYieldCore() compile warning for single core targets

- portable/ThirdParty/GCC/RP2040/port.c
After the xEventGroupWaitBits in vProtLockInternalSpinUnlockWithWait there was an assertion about
pxYiledSpinLock being NULL, however when xEventGroupWaitBits returns, IRQs have been re-enabled
and so it is no longer safe to assert on the state which was protected by IRQs being disabled.
I spotted this once during a long running test, and made a simple extreme test app to repro the problem.
> RP2040: Remove incorrect assertion

- portable/ThirdParty/GCC/RP2040/CMakeLists.txt
- portable/ThirdParty/GCC/RP2040/README.md
- portable/ThirdParty/GCC/RP2040/library.cmake
Including FreeRTOS in the top level CMakeLists.txt is not always convenient, so this change allows
FreeRTOS_Kernel_import.cmake or just the CMakeLists.txt to be included wherever in the user's project.
> RP2040: Allow FreeRTOS to be added to the parent CMake project post initialization of the Pico SDK

- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM7/r0p1/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/portasm.s
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
Add ARM Cortex M7 r0p0 / r0p1 Errata 837070 workaround to CM4 MPU ports.
Add a runtime assertion when running on a cortex M7 r0p0 or r0p1 and the workaround is not enabled.
Optionally, enable the errata workaround by defining configTARGET_ARM_CM7_r0p0 or configTARGET_ARM_CM7_r0p1 in FreeRTOSConfig.h.
Related Issue
-----------
FreeRTOS Forum Topic: https://forums.freertos.org/t/freertos-mpu-support-in-arm-cortex-m7/15306/3
> Add Cortex M7 r0p1 Errata 837070 workaround to CM4_MPU ports

- portable/ThirdParty/GCC/RP2040/port.c
This prevents generating a too-large offset and follows the pattern used in other ports, for example [portable/GCC/ARM_CM0/port.c:204](../blob/2dfdfc4ba4d8bb487c8ea6b5428d7d742ce162b8/portable/GCC/ARM_CM0/port.c#L204)
For search engine purposes, this resolves the following error message:
```
/tmp/ccG2Q2Vc.s: Assembler messages:
/tmp/ccG2Q2Vc.s:340: Error: invalid offset, value too big (0x00000630)
/tmp/ccG2Q2Vc.s:671: Error: invalid offset, value too big (0x000004A0)
```
I'm not completely sure why I ran into this issue when presumably this port is generally functional. Maybe something about my build environment?
> RP2040: Use indirect reference for pxCurrentTCB

- portable/ThirdParty/GCC/Posix/port.c
I noticed that a static variable `xResumeSignals` is prepared by the signal functions (`sigemptyset` and `sigaddset`)  but never used. I built the POSIX full demo example with this change and it still worked. Since it's a static variable and never used, I think it can be removed to improve code clarity. As far as I can see, the two aforementioned functions have no side effects besides changing the passed signal set. Please let me know if my assumptions are incorrect or if I'm missing something.
> Posix: Remove unused signal set variable from port

- tasks.c
This fixes link failures with LTO:
```
/tmp/ccJbaKaD.ltrans0.ltrans.o: in function `pxCurrentTCBConst2':
/root/project/FreeRTOS/portable/GCC/ARM_CM4F/port.c:249: undefined reference to `pxCurrentTCB'
/usr/lib/gcc/arm-none-eabi/11.2.0/../../../../arm-none-eabi/bin/ld: /tmp/ccJbaKaD.ltrans0.ltrans.o: in function `pxCurrentTCBConst':
/root/project/FreeRTOS/portable/GCC/ARM_CM4F/port.c:443: undefined reference to `pxCurrentTCB'
```
> add portDONT_DISCARD to pxCurrentTCB

- portable/GCC/MicroBlazeV9/port.c
- portable/GCC/MicroBlazeV9/portasm.S
- portable/GCC/MicroBlazeV9/portmacro.h
Description
-----------
This enables support for hardware-level stack protection on MicroBlazeV9.  There's no inherent reason why it shouldn't also work on older MicroBlaze as well, but this is the only one I tested this specific implementation with.  (I have previously tested similar code on V8, though, so I know it at least can work on that.)
Test Steps
-----------
1. On a Xilinx 7-series FPGA, configure a MicroBlaze core with the stack protection exception enabled.
2. Configure FreeRTOS with `configCHECK_FOR_STACK_OVERFLOW = 0` (optional; it will also work with it enabled, but it's not needed)
3. During normal operation, everything runs normally (which is **not** the case if you enable the exception without using this code).
4. If any task exceeds its stack limits, the CPU will …
> Implement MicroBlazeV9 stack protection

- portable/GCC/MicroBlazeV9/port.c
Description
-----------
This API is added to the MicroBlazeV9 port. It enables the application writer to remove an interrupt handler.
This was originally contributed in this PR - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/523
> Add vPortRemoveInterruptHandler API

- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
When the heap is exhausted (no free block), start and end markers are the only blocks present in the free block list:
```
+---------------+     +-----------> NULL
|               |     |
|               V     |
+ ----- +            + ----- +
|   |   |            |   |   |
|   |   |            |   |   |
+ ----- +            + ----- +
xStart               pxEnd
```
The code block which traverses the list of free blocks to calculate heap stats used a `do..while` loop that moved past the end marker when the heap had no free block resulting in a `NULL` pointer dereference. This commit changes the `do..while` loop to `while` loop thereby ensuring that we never move past the end marker.
This was reported here - https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/534
By …
> Fix NULL pointer dereference in vPortGetHeapStats

- include/message_buffer.h
Change type of message buffer handle
Description
-----------
Previously message buffer handle type was a void pointer whereas stream buffer handle has its own type set to a stream buffer struct definition. Message buffer handle (void*) was type cast to a stream buffer handle for the API calls. 
The change sets the type of message buffer handle as a stream buffer handle since message buffer is essentially built on a stream buffer.
Test Steps
-----------
None
Related Issue
-----------
None
> Change type of message buffer handle

- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portasm.c
- portable/GCC/ARM_CM23/non_secure/portasm.c
- portable/GCC/ARM_CM23_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM33/non_secure/portasm.c
- portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM55/non_secure/portasm.c
- portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c
Description
-----------
This fixes the compilation issue with XC32 compiler.
It was reported here - https://forums.freertos.org/t/xc32-v4-00-error-with-building-freertos-portasm-c/14357/4
> Add .syntax unified to GCC assembly functions

- .github/lexicon.txt
- include/FreeRTOS.h
- tasks.c
Description
-----------
FreeRTOS's Thread Local Storage (TLS) support used variables and functions from newlib, thereby making the TLS support specific to newlib. This commit generalizes the TLS support so that it can be used with other c-runtime libraries also. The default behavior for newlib support is still kept same for backward compatibility.
The application writer would need to set `configUSE_C_RUNTIME_TLS_SUPPORT` to 1 in their FreeRTOSConfig.h and define the following macros to support TLS for a c-runtime library:
1. `configTLS_BLOCK_TYPE` - Type used to define the TLS block in TCB.
2. `configINIT_TLS_BLOCK( xTLSBlock )` - Allocate and initialize memory block for the task's TLS Block.
3. `configSET_TLS_BLOCK( xTLSBlock )` - Switch C-Runtime's TLS Block to point to xTLSBlock.
4. …
> Generalize Thread Local Storage (TLS) support

- include/FreeRTOS.h
Set default value of INCLUDE_xTaskGetCurrentTaskHandle to 1.
Description
-----------
The configuration is used to optionally disable the function `xTaskGetCurrentTaskHandle()`. Since the function is required for  stream buffer, message buffer and mutex, setting the configuration default to always enabled. This will cause a small overhead in code size (since the function `xTaskGetCurrentTaskHandle()` is simple and have very few lines of code) and should not cause an overhead in .bss or .data. Most of the linkers should remove the function if its unused within the code.
Test Steps
-----------
None
Related Issue
-----------
This is a follow up of https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/507
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> Change default value of INCLUDE_xTaskGetCurrentTaskHandle

- portable/GCC/ARM_CA9/port.c
Description
-----------
Include string.h at the top of portable/GCC/ARM_CA9/port.c to prevent memset() generating a warning.
Test Steps
-----------
Build a Cortex-A9 GCC demo to ensure there is no warning.
> Fix a compiler warning in the Cortex-A9 port layer

- include/FreeRTOS.h
- tasks.c
Description
-----------
Move some of the complexity from the pre-processor expression used to conditionally compile in prvWriteNameToBuffer() to compile time checks within FreeRTOS.h.  The compile time checks will prevent the code building if the other FreeRTOSConfig.h settings used in the original code are in an inconsistent state.
Test Steps
-----------
Try building with different combinations of configSUPPORT_DYNAMIC_ALLOCATION, configGENERATE_RUN_TIME_STATS, configUSE_TRACE_FACILITY and configUSE_STATS_FORMATTING_FUNCTIONS.
> Simplify pre-processor guards on prvWriteNameToBuffer()

- portable/ThirdParty/GCC/Posix/port.c
Fix warnings in posix port
Description
-----------
Fixes warnings about unused parameters and variables when built with `-Wall -Wextra`.
Test Steps
-----------
Compile a project using this port with `-Wall -Wextra` on either gcc or clang. There will be four warnings:
```
port.c                      326  44 warning  e-f-b    clang [-Wunused-parameter]: Unused parameter 'xMask'
port.c                      383  40 warning  e-f-b    clang [-Wunused-parameter]: Unused parameter 'sig'
port.c                      424  45 warning  e-f-b    clang [-Wunused-parameter]: Unused parameter 'pxPendYield'
port.c                      529  21 warning  e-f-b    clang [-Wunused-variable]: Unused variable 'sigresume'
```
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Fix warnings in posix port

- .github/workflows/unit-tests.yml
- croutine.c
- include/FreeRTOS.h
- include/event_groups.h
- include/message_buffer.h
- include/mpu_wrappers.h
- include/queue.h
- include/semphr.h
- include/stream_buffer.h
- include/task.h
- stream_buffer.c
- tasks.c
Description
-----------
Misra rule 20.7 adds Parenthesise to all parameter names in macro definitions.
The issue was reported here : https://forums.freertos.org/t/misra-20-7-compatibility/15385 
> Add support for MISRA rule 20.7

- portable/ThirdParty/GCC/RP2040/library.cmake
Description
-----------
This allows the application write to set `FREERTOS_CONFIG_FILE_DIRECTORY` to whichever directory the `FreeRTOSConfig.h` file exists in.
This was reported here - https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/545
> Add FreeRTOS config directory to include dirs

- portable/MemMang/heap_2.c
- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
This PR fixes type of pointer operations
Description
-----------
While I was working with RL78 MCU I caught a problem: heap allocation was putting into fault my device. After investigation the problem I found sizeof(size_t) != sizeof(void*). It can be fixed with replacement size_t in pointer arithmetic to portPOINTER_SIZE_TYPE.
Test Steps
-----------
Just use heap allocation on RL78 MCU
> [Fix] Type for pointers operations

- portable/GCC/RISC-V/portASM.S
- portable/GCC/RISC-V/portContext.h
- portable/GCC/RISC-V/portmacro.h
Add support for RV32E extension in RISC-V GCC port
Description
-----------
RV32E (E for embedded) processors only have 16 registers instead of the 32 a regular RV32 core has. This change allows running FreeRTOS on such cores, by not touching registers `x16`-`x31` when FreeRTOS is built for RV32E.
Test Steps
-----------
Compile the code for RV32E core with EABI. (e.g. `gcc -march=rv32e -mabi=ilp32e` ). The code can be then run also on a regular RV32 core.
> RISC-V: Add support for RV32E extension in GCC port

- tasks.c
Description
-----------
This PR adds a check to the vTaskSetThreadLocalStoragePointer and pvTaskGetThreadLocalStoragePointer functions to ensure that the indices passed as parameters are non-negative values.
Test Steps
-----------
Related Issue
-----------
> Add checks for Index in ThreadLocalStorage APIs

- include/task.h
Description
-----------
The following three macros in `task.h` were written in a way that forced to to omit the terminating semicolon when used in a non-block, single statement, `then` part of a if statement:
```
if(condition)
macro(args, more, args);
else
/* Any block or statement */
```
Compilers would complain of a syntax error, as the terminating semicolon or the block ending was already part of the macro.
- vTaskDelayUntil() was updated to conform to usual pattern do { ... } while(0), making it into an unterminated statement.
- vTaskNotifyGiveFromISR() and
- vTaskGenericNotifyGiveFromISR() were updated to remove the unneeded terminating semicolons.
I scanned the other files in the include directory for similar patterns and found none.
Test Steps
-----------
Attempts to compile any …
> Update of three badly terminated macro definitions

- portable/ThirdParty/GCC/RP2040/README.md
Fix typo in RP2040 port README.md
Description
-----------
Replace "import" with "include" in the RP2040 Readme.md cmake code sample.
Related Issue
-----------
#557 
> portable-RP2040: Fix typo in README.md

- include/task.h
- tasks.c
This commit adds support for retrieving the task's core affinity mask when SMP is used for more than 1 cores and configUSE_CORE_AFFINITY is enabled.
Signed-off-by: Sudeep Mohanty <sudp.mohanty@gmail.com>
> Add support for retrieving a task's uxCoreAffinityMask with the vTaskGetInfo() API

- queue.c
Removed the 'configASSERT( xInheritanceOccurred == pdFALSE )' assertion from xQueueSemaphoreTake as the reasoning behind it is wrong; it can trigger on wrongly on highly-contested semaphores on multicore systems. See [the forum](https://forums.freertos.org/t/15967) for details.
> Removed the 'configASSERT( xInheritanceOccurred == pdFALSE )' assertion from xQueueSemaphoreTake

- portable/GCC/NiosII/port_asm.S
Description
-----------
The NIOS II port contained a "call" instruction with limited jump range.  That can cause issues depending on the amount of RAM available and linking.  Full description here: https://forums.freertos.org/t/nios-ii-r-nios2-call26-noat-linker-error/16028
Test Steps
-----------
Requires a configuration where the offending call needs to jump more than 256Mbytes.
Related Issue
-----------
https://forums.freertos.org/t/nios-ii-r-nios2-call26-noat-linker-error/16028
> Update the NIOSII port to enable longer jumps

- portable/GCC/ARM_CR5/port.c
- portable/GCC/ARM_CR5/portASM.S
- portable/GCC/ARM_CR5/portmacro.h
Add support for the `configUSE_TASK_FPU_SUPPORT` constant in the GCC/ARM_CR5 port
Description
-----------
In this PR, I have added support for the `configUSE_TASK_FPU_SUPPORT` configuration constant to the GCC/ARM_CR5 port. 
The reason for this is, that when one does compile a FreeRTOS application with FPU on for the Cortex-R5 processor with the GCC compiler, then the compiler by default may make code optimizations using the FP-registers. E.g. code that uses standard functions such as `memcpy` , `memset` and similar ones, the chances are very high, that the compiler will make optimizations using the FPU registers. This will lead certainly to corrupted FP-registers, if these won't be handled accordingly.
In the current state of the GCC/ARM_CR5 port, one could use the function …
> Add support for the configUSE_TASK_FPU_SUPPORT constant in the GCC/ARM_CR5 port

- include/FreeRTOS.h
Fixed a lint warning
Description
-----------
Lint complains about the macro `configSET_TLS_BLOCK` not being parenthesized. I fixed that in `FreeRTOS.h`.
The macro is used in two places in `tasks.c` and parenthesizing the macro has no effect at all, but removes one lint warning.
Test Steps
-----------
see above.
Related Issue
-----------
none.
> parenthesize expression-like macro

- include/FreeRTOS.h
- portable/ThirdParty/GCC/RP2040/library.cmake
- tasks.c
- timers.c
Description
-----------
Remove references to co-routines in various FreeRTOS Kernel files
> Remove additional references to coroutines

- include/list.h
Fix array-bounds compiler warning on gcc11+ in list.h
Description
-----------
listGET_OWNER_OF_NEXT_ENTRY computes `( pxConstList )->pxIndex->pxNext` after verifying that `( pxConstList )->pxIndex` points to `xListEnd`, which due to being a MiniListItem_t, can be shorter than a ListItem_t. Thus, `( pxConstList )->pxIndex` is a `ListItem_t *` that extends past the end of the `List_t` whose `xListEnd` it points to. 
On GCC 11+, this triggers an array-bounds warning. This is fixed by accessing `pxNext` through a `MiniListItem_t` instead.
<del>
listGET_OWNER_OF_NEXT_ENTRY uses uninitialized memory if the passed list is empty (only has the list end marker). While all uses of this macro are nested within a list empty check or are after an assert, this trips up GCC post GCC 11 on O3. Worse yet, …
> Fix array-bounds compiler warning on gcc11+ in list.h

- include/task.h
- tasks.c
There is a prototype for `vApplicationIdleHook` that is local to the idle task.
To have the code more unified, the prototype should be moved to `task.h`, similar to `vApplicationStackOverflowHook`.
This is because compilers may generate warnings if the prototype for the `vApplicationIdleHook` is missing. In that case, application software can simply include `task.h` to have the prototype defined.
Description
-----------
Moved the prototype for `vApplicationIdleHook` from `task.c` to `task.h`.
> Move the prototype for vApplicationIdleHook to task.h.

- tasks.c
Update equal priority task preemption
> Unit test is also updated in the FreeRTOS repository [PR](https://github.com/FreeRTOS/FreeRTOS/pull/903)
Description
-----------
Update the following function not to preempt task with equal priority
* vTaskResume
* xTaskResumeFromISR
* vTaskPrioritySet
* vTaskResumeAll
Test Steps
-----------
Related Issue
-----------
> Update equal priority task preemption

- .github/lexicon.txt
- include/task.h
- tasks.c
Allow `ulTaskGetIdleRunTimeCounter` and `ulTaskGetIdleRunTimePercent` to be used whenever `configGENERATE_RUN_TIME_STATS` is enabled, as this is the only requirement for these functions to work.
> Add `ulTaskGetRunTimeCounter` and `ulTaskGetRunTimePercent`

- CMakeLists.txt
- README.md
Description
-----------
The quick start instructions for CMake mention the "master"
git branch which has been replaced by "main" in the current
repo.
The main CMakeLists.txt documents how to integrate a
custom port. Fix a typo in the suggested CMake code.
Test Steps
-----------
Integrate into a simple CMake project setting `set(FREERTOS_PORT "A_CUSTOM_PORT" CACHE STRING "" FORCE)` but don't provide a `freertos_kernel_port` library. Check the error message no longer contains the typo `taget_link_libraries(`
> Fix some CMake documentation typos

- .github/workflows/kernel-checks.yml
- tasks.c
This PR extends the discussion in #607 to prevent uxTopReadyPriority decreased to -1 in the implementation.
Description
-----------
* Every core starts with an idle task in SMP implementation and taskTASK_IS_RUNNING only return ture when the task is idle task before scheduler started. So prvSelectHighestPriorityTask won't be called in vTaskSuspend before scheduler started.
* Update prvSelectHighestPriorityTask and also ensure that this function is called only when scheduler started.
Test Steps
-----------
Related Issue
-----------
> Remove prvSelectHighestPriorityTask call in vTaskSuspend

- tasks.c
Description
-----------
ulTaskSwitchedInTime must be an array, index is core number.
On single core devices this change has no effect, but on multicore devices (mine: RP2040) counting is currently wrong, because ulTaskSwitchedInTime is just a scalar type and counts only half of the actual CPU time.
Test Steps
-----------
Performance counting should count configNUM_CORES * (ticks of portALT_GET_RUN_TIME_COUNTER_VALUE()).
Without this change it only counts (ticks of portALT_GET_RUN_TIME_COUNTER_VALUE()).
Related Issue
-----------
None
> fix performance counting for SMP

- portable/GCC/MicroBlaze/portmacro.h
- portable/GCC/MicroBlazeV8/portmacro.h
- portable/GCC/MicroBlazeV9/portmacro.h
Description
-----------
The introduction of `portMEMORY_BARRIER` will ensure the places in the kernel use a barrier will work. For example, `xTaskResumeAll` has a memory barrier to ensure its correctness when compiled with optimization enabled. Without the barrier `xTaskResumeAll` can fail (e.g. start reading and writing to address 0 and/or infinite looping) when `xPendingReadyList` contains more than one task to restore.
In `xTaskResumeAll` the compiler chooses to cache the `pxTCB` the first time through the loop for use in every subsequent loop. This is incorrect as the removal of `pxTCB->xEventListItem` will actually change the value of `pxTCB` if it was read again
at the top of the loop. The barrier forces the compiler to read `pxTCB` again at the top of the loop.
The compiler is …
> Introduce portMEMORY_BARRIER for Microblaze port.

- portable/MSVC-MingW/port.c
Description
-----------
See description in issue
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/623
Test Steps
-----------
Call vPortEndScheduler() instead of just ending the scheduler the problem is completely stopped
Related Issue
-----------
> Do not call exit() on MSVC Port when calling vPortEndScheduler

- include/FreeRTOS.h
The PR #597 introduced a new config option `configTICK_TYPE_WIDTH_IN_BITS` which can be defined to one of the following:
* `TICK_TYPE_WIDTH_16_BITS` - Tick type is 16 bit wide.
* `TICK_TYPE_WIDTH_32_BITS` - Tick type is 32 bit wide.
* `TICK_TYPE_WIDTH_64_BITS` - Tick type is 64 bit wide.
Earlier we supported 16 and 32 bit width for tick type which was controlled using the config option `configUSE_16_BIT_TICKS.` The PR tried to maintain backward compatibility by honoring `configUSE_16_BIT_TICKS`. The backward compatibility did not work as expected though, as the macro `configTICK_TYPE_WIDTH_IN_BITS` was used before it was defined. This PR addresses it by ensuring that the macro `configTICK_TYPE_WIDTH_IN_BITS` is defined before it is used.
1. `configUSE_16_BIT_TICKS` is defined to 0.
Source …
> Fix build failure introduced in PR #597

- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/portmacro.h
Fix POSIX port
Description
-----------
This change fixes a build failure in the POSIX port on my system (WSL). It also introduces an improvement which helps identifying each of the threads by identifying with a name, which is very useful for debugging.
> POSIX port fixes

- .github/lexicon.txt
- include/FreeRTOS.h
- include/newlib-freertos.h
- include/picolibc-freertos.h
- portable/ThirdParty/GCC/ARC_EM_HS/port.c
- portable/ThirdParty/GCC/ARC_v1/port.c
- tasks.c
Thread Local Storage (TLS) offers a platform-native mechanism for
managing per-task variables that doesn't rely on custom support in
FreeRTOS for things like errno.
Picolibc uses TLS internally for all variables that are intended to be
task-local. Because of the TLS architecture, only variables which are
actually used end up getting allocate space in the TLS block. Contrast
this with the newlib 'struct _reent' block which holds all possible
task-local values, even for APIs not used by the application.
Picolibc also has TLS helper functions that provide the necessary
platform-specific code which makes the FreeRTOS changes platform
independent. This patch uses those hooks instead of providing the
platform specific code in FreeRTOS itself.
The picolibc helper functions rely on elements …
> Add Thread Local Storage (TLS) support using Picolibc functions

- .github/actions/url_verifier.sh
- README.md
Description
-----------
This PR introduces github status badge for code coverage.
Test Steps
-----------
Tested through visual inspection.
Checklist:
----------
- [ x] I have tested my changes. No regression in existing tests.
Related Issue
-----------
> Introduced code coverage status badge

- portable/MPLAB/PIC24_dsPIC/portmacro.h
added portPOINTER_SIZE_TYPE and SIZE_MAX definitions to PIC24/dsPIC port
Description
-----------
pic24/dsPICs are 16-bit MCUs with 16-bit pointers.  The default value of portPOINTER_SIZE_TYPE is uint32_t so the heap's are compiled with a size mismatch warning.  Using size_t as the pointer size fixes the issue and the code compiles without warnings.
SIZE_MAX is not part of the stdint.h on PIC24/dsPIC.  This definition has been added to the portmacros
Test Steps
-----------
Compile the code and notice the warning.  Add the change, recompile.  No warning.
Checklist:
----------
- [-] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------
None
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> added portPOINTER_SIZE_TYPE and SIZE_MAX definition to PIC24/dsPIC port

- include/picolibc-freertos.h
Description
-----------
Both the TLS block and stack must be correctly aligned when using picolibc. The architecture stack alignment is represented by the portBYTE_ALIGNMENT_MASK and the TLS block alignment is provided by the Picolibc _tls_align() inline function for Picolibc version 1.8 and above. For older versions of Picolibc, we'll assume that the TLS block requires the same alignment as the stack.
For downward growing stacks, this requires aligning the start of the TLS block to the maximum of the stack alignment and the TLS alignment. With this, both the TLS block and stack will now be correctly aligned.
For upward growing stacks, the two areas must be aligned independently; the TLS block is aligned from the start of the stack, then the tls space is allocated, and then the stack is …
> Fix TLS and stack alignment when using picolibc

- include/projdefs.h
Add missing FreeRTOS+ defines
Description
-----------
These are currently defined in [FreeRTOS-Plus-TCP](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/blob/b879e29142225bdd0d4b5e5d7bc6bc2c39943a21/source/include/FreeRTOS_IP.h#L279) until they are moved here.
> Add missing FreeRTOS+ defines

- .github/workflows/kernel-checks.yml
- .github/workflows/kernel-demos.yml
- .github/workflows/unit-tests.yml
Description
-----------
Kernel demos check builds multiple demos from FreeRTOS/FreeRTOS repo and unit tests check runs unit tests in `FreeRTOS/FreeRTOS`. Both of these checks used main branch of `FreeRTOS-Kernel`. This PR updates these checks to use the changes in the Pull Request to ensure that the changes in the Pull Request are verified.
Test Steps
-----------
Tested using a test PR to my fork - https://github.com/aggarg/FreeRTOS-Kernel/pull/1
> Run kernel demos and unit tests for PR changes

- .github/lexicon.txt
- event_groups.c
- include/event_groups.h
- include/message_buffer.h
- include/queue.h
- include/semphr.h
- include/stream_buffer.h
- include/task.h
- include/timers.h
- queue.c
- stream_buffer.c
- tasks.c
- timers.c
Description
-----------
This PR adds `...GetStaticBuffers()` functions to get pointers to the buffers used to create a particular static FreeRTOS objects (i.e., objects created using `...CreateStatic()`).
These functions are helpful because some ports (such as ESP-IDF) use the `...CreateStatic()` when an object needs to be allocated from special memory (i.e., not included in the regular `pvPortMalloc()`/`vPortFree()`). "Special Memory" could include things such as memory from a "fast malloc memory pool" or memory from external (i.e., off chip) RAM, and this special memory is allocated/freed using a separate API.
Currently, we need to associate the static object handles and their buffers using some sort of list. For example:
```c
// Create a task from special memory
StackType_t …
```
> Add functions to get the buffers of statically created objects

- CMakeLists.txt
Description
-----------
This is needed as it is breaking projects - https://forums.freertos.org/t/freertos-gcc-cmake/16984
We will re-evaluate and accordingly add this later.
Related Issue: https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/646
> Remove C90 requirement from CMakeLists

- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
Heap 4 and Heap 5 add some padding to ensure that the allocated blocks are always aligned to `portBYTE_ALIGNMENT` bytes. The code until now was adding padding always even if the resulting block was already aligned. This PR updates the code to only add padding if the resulting block is not aligned.
> Only add alignment padding when needed

- include/task.h
Missing comma in a comment located in task.h
Description
-----------
https://forums.freertos.org/t/typo-in-code/17083
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> add a missing comma

- portable/CCS/ARM_CM3/port.c
- portable/CCS/ARM_CM4F/port.c
- portable/GCC/ARM_CA53_64_BIT/port.c
- portable/GCC/ARM_CA9/port.c
- portable/GCC/ARM_CM3/port.c
- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4F/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM7/r0p1/port.c
- portable/GCC/ARM_CR5/port.c
- portable/IAR/ARM_CM3/port.c
- portable/IAR/ARM_CM4F/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM7/r0p1/port.c
- portable/MikroC/ARM_CM4F/port.c
- portable/RVDS/ARM_CM3/port.c
- portable/RVDS/ARM_CM4F/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM7/r0p1/port.c
Description
-----------
FreeRTOS-Kernel/portable/GCC/ARM_CM4F/port.c:399:41: error: conversion from 'uint32_t' {aka 'long unsigned int'} to 'uint8_t' {aka 'unsigned char'} may change value [-Werror=conversion]
399 |         *pucFirstUserPriorityRegister = ulOriginalPriority;
Test Steps
-----------
Enable compile option: -Wconversion
Checklist:
----------
Related Issue
-----------
> fix conversion warning

- portable/CCS/ARM_CM3/port.c
- portable/CCS/ARM_CM4F/port.c
- portable/GCC/ARM_CM3/port.c
- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4F/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM7/r0p1/port.c
- portable/IAR/ARM_CM3/port.c
- portable/IAR/ARM_CM4F/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM7/r0p1/port.c
- portable/MikroC/ARM_CM4F/port.c
- portable/RVDS/ARM_CM3/port.c
- portable/RVDS/ARM_CM4F/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM7/r0p1/port.c
Description
-----------
Adjust assertions related to the CMSIS __NVIC_PRIO_BITS and FreeRTOS configPRIO_BITS configuration macros such that these macros specify the minimum number of implemented priority bits supported by a config build rather than the exact number of implemented priority bits.
Test Steps
-----------
Run the kernel in qemu with the mps2-an385 target with __NVIC_PRIO_BITS and configPRIO_BITS set to all valid values: 3,4,5,6,7,8.
Checklist:
----------
- [ N/A ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------
Related to [Qemu issue #1122](https://gitlab.com/qemu-project/qemu/-/issues/1122). See related discussion on the [qemu mailing list](https://lore.kernel.org/qemu-devel/20220813112559.1974427-1-anton.kochko …
> ARMv7M: Adjust implemented priority bit assertions

- tasks.c
This PR updates the checks for scheduler suspension in `tasks.c` module.
Description
-----------
Currently in the FreeRTOS kernel, the variable `uxSchedulerSuspended` is used to keep track of scheduler suspension. The variable is incremented with every call to `vTaskSuspendAll()`, thereby keeping a track of nested scheduler suspensions. However, in many places in the `tasks.c` module, the check for scheduler suspension is not uniform. At times `uxSchedulerSuspended` is compared to `pdFALSE` giving an impression that `uxSchedulerSuspended` is a boolean.
To avoid non uniform checks of the scheduler state, this PR updates all checks involving `uxSchedulerSuspended` to be tested as follows:
```
uxSchedulerSuspended == ( UBaseType_t ) 0U -> Scheduler not suspended
uxSchedulerSuspended != ( …
```
> Updated tasks.c checks for scheduler suspension

- .github/lexicon.txt
- stream_buffer.c
Description
-----------
Without this change, the code produces the following warning when compiled with `-Wcast-align` flag:
```
cast increases required alignment of target type
```
Test Steps
-----------
1. Build the code and see that it does not produce any warning.
2. Run stream and message buffer soak tests.
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/cast-increases-required-alignment-of-target-type/17319
> Fix cast alignment warning

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
MAC OS pthread_attr_setstack has an extra requirement of stack address and stack size to be suitably aligned. Adding the changes for the alignement of both.
```
int
pthread_attr_setstack(pthread_attr_t *attr, void *stackaddr, size_t stacksize)
{
int ret = EINVAL;
if (attr->sig == _PTHREAD_ATTR_SIG &&
(((mach_vm_address_t)stackaddr & vm_page_mask) == 0) &&
((stacksize & vm_page_mask) == 0) &&
stacksize >= PTHREAD_STACK_MIN) {
attr->stackaddr = (void *)((uintptr_t)stackaddr + stacksize);
attr->stacksize = stacksize;
ret = 0;
}
return ret;
}
```
Test Steps
-----------
Build and run [GCC_POSIX](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Posix_GCC) demo on Linux and MacOS.
Checklist:
----------
- [NA] I have modified and/or added unit-tests to cover …
> Align StackSize and StackAddress for macOs

- portable/CCS/MSP430X/portext.asm
Description
-----------
The following is from the MSP430X instruction set -
```
MOVX.W Move source word to destination word.
The source operand is copied to the destination. The source operand is
not affected. Both operands may be located in the full address space.
```
The movx instruction allows both the operands to be located in the full address space and therefore, works with large data model as well.
Test Steps
-----------
1. Stepped through the assembly and verified that the instruction moves data correctly between 2 bytes memory and register both with large and small data model on MSP-EXP430FR5994.
2. Ran register tests on MSP-EXP430FR5994.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/671
By submitting this pull request, I confirm that you can use, …
> Use the extended movx instruction instead of mov

- tasks.c
Original PR - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/577
Description
-----------
The description of the `eReady` enum is inclusive of tasks that are pending ready
```c
eReady,       /* The task being queried is in a ready or pending ready list. */
```
However, the current implementation of the `eTaskGetState` function only checks a task's state list item, thus will return a non-`eReady` state for tasks that are pending ready.
Test Steps
-----------
1. From a main task, create a task_A.
2. task_A blocks/suspends itself
3. Main task calls `vTaskSuspendAll()`
4. Main task triggers an ISR. The ISR unblocks task_A
5. Main task then calls `eTaskGetState` on task_A which returns `eBlocked`/`eSuspended` even though task_A has been unblocked by the ISR.
Notes:
- We discovered this issue …
> Fix eTaskGetState for pending ready tasks

- event_groups.c
- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/portmacro.h
- queue.c
- stream_buffer.c
- tasks.c
Use UBaseType_t as interrupt mask
Description
-----------
* Use UBaseType_t as interrupt mask
* Update in posix port
Test Steps
-----------
Compile clang posix-demo without warning.
Checklist:
----------
Related Issue
-----------
> Use UBaseType_t as interrupt mask type

- include/croutine.h
- stream_buffer.c
* Fix document warning in croutine
* Fix cast-qual warning in stream buffer
Description
-----------
* Update " /*<" to "/**<" in croutine.h
* Remove const qualifier in get static buffer in stream buffer
Test Steps
-----------
Consume the FreeRTOS-Kernel/CMakeLists.txt with clang compiler.
clang version 10.0.0-4ubuntu1
Adding the following suppression
```
target_compile_options( freertos_kernel
PRIVATE
$<$<COMPILE_LANG_AND_ID:C,Clang>:-Wno-cast-align>
$<$<COMPILE_LANG_AND_ID:C,Clang>:-Wno-covered-switch-default>
$<$<COMPILE_LANG_AND_ID:C,Clang>:-Wno-missing-variable-declarations>
$<$<COMPILE_LANG_AND_ID:C,Clang>:-Wno-padded>
$<$<COMPILE_LANG_AND_ID:C,Clang>:-Wno-unused-macros>
)
target_compile_options( freertos_kernel_port
PRIVATE …
```
> Fix clang warning in croutine and stream buffer

- include/FreeRTOS.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM35P/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM55/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM85/portmacro.h
- portable/GCC/ARM_CM0/portmacro.h
- portable/GCC/ARM_CM23/non_secure/portmacro.h
- portable/GCC/ARM_CM23_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM3/portmacro.h
- portable/GCC/ARM_CM33/non_secure/portmacro.h
- portable/GCC/ARM_CM33_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM35P/non_secure/portmacro.h
- portable/GCC/ARM_CM35P_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4F/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM55/non_secure/portmacro.h
- portable/GCC/ARM_CM55_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM7/r0p1/portmacro.h
- portable/GCC/ARM_CM85/non_secure/portmacro.h
- portable/GCC/ARM_CM85_NTZ/non_secure/portmacro.h
- portable/ThirdParty/GCC/Posix/portmacro.h
- portable/ThirdParty/GCC/RP2040/include/portmacro.h
- portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h
- tasks.c
- timers.c
* Use portTASK_FUNCTION_PROTO to replace portNORETURN for GCC port
Description
-----------
Test Steps
-----------
Consume the FreeRTOS-kernel/CMakeLists.txt with Posix-GCC port. Compile with clang should not have missing-noreturn error.
Checklist:
----------
Related Issue
-----------
> Use portTASK_FUNCTION_PROTO to replace portNORETURN

- portable/GCC/AVR32_UC3/portmacro.h
- portable/GCC/CORTUS_APS3/portmacro.h
- portable/GCC/ColdFire_V2/portmacro.h
- portable/GCC/H8S2329/portmacro.h
- portable/GCC/HCS12/portmacro.h
- portable/GCC/MSP430F449/portmacro.h
- portable/GCC/PPC405_Xilinx/portmacro.h
- portable/GCC/PPC440_Xilinx/portmacro.h
- portable/GCC/RL78/portmacro.h
- portable/GCC/STR75x/portmacro.h
- portable/IAR/78K0R/portmacro.h
- portable/IAR/ATMega323/portmacro.h
- portable/IAR/AVR32_UC3/portmacro.h
- portable/IAR/AVR_AVRDx/portmacro.h
- portable/IAR/AVR_Mega0/portmacro.h
- portable/IAR/AtmelSAM7S64/portmacro.h
- portable/IAR/AtmelSAM9XE/portmacro.h
- portable/IAR/LPC2000/portmacro.h
- portable/IAR/MSP430/portmacro.h
- portable/IAR/MSP430X/portmacro.h
- portable/IAR/RL78/portmacro.h
- portable/WizC/PIC18/portmacro.h
Add constant type for portMAX_DELAY in port
Description
-----------
* Add constant type UL for porMAX_DELAY if tick type is 32bits
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Add constant type for portMAX_DELAY in port

- stream_buffer.c
Update static stream buffer size check
Description
-----------
* Use volatile size instead of sizeof directly to prevent always true/false warning
Test Steps
-----------
Define configASSERT and configSUPPORT_STATIC_ALLOCATION.
Run the application to create static stream buffer should not have any error.
Checklist:
----------
Related Issue
-----------
> Update static stream buffer size check

- portable/GCC/ARM7_AT91SAM7S/port.c
- portable/IAR/AtmelSAM7S64/port.c
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix typos in comments for the AT91SAM7S port

- portable/ThirdParty/GCC/ATmega/portmacro.h
Related Issue
-----------
Fix #697: Missing portPOINTER_SIZE_TYPE definition for ATmega port
> Fix #697: Missing portPOINTER_SIZE_TYPE definition for ATmega port

- croutine.c
- include/croutine.h
- include/semphr.h
- include/stack_macros.h
- stream_buffer.c
- tasks.c
Remove empty expression statement compiler warning.
```
#define MACRO( x ) \
{                                \
...                           \
}
MACRO( x );
will be expanded to =>
{
...
}; /* Compiler's warning about this extra semicolon. */
```
Reference [clang warning doc](https://clang.llvm.org/docs/DiagnosticsReference.html#wextra-semi-stmt) for more information.
Check with the following bash command for all the defined macro
```
grep -n -e "#define.[\{;]" .c include/*.h
```
Description
-----------
* Add do while( 0 ) loop for defined macro
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Remove empty expression statement compiler warning

- tasks.c
Description
-----------
* Sync with eTaskGetState. Task in pending ready list is in eReady state.
* Update in vTaskGetInfo function to return eReady state for task in a pending ready list.
Test Steps
-----------
Create a task with the following function.
```
vTaskSuspendAll();
{
/* Waiting for ISR to resume a task. */
vTaskList( pcPrintBuffer );
printf( pcPrintBuffer );
}
xTaskResumeAll();
```
Before this patch
```
testTask        X       6       67      2
TzCtrl          R       1       1021    1
IDLE            R       0       67      4
testTask2       B       5       67      3        # task is in eBlocked state
Tmr Svc         B       6       137     5
```
After this patch
```
testTask        X       6       67      2
IDLE            R       0       67      4
TzCtrl          B       1 …
```
> Update uxTaskGetSystemState for tasks in pending ready list

- CMakeLists.txt
- include/CMakeLists.txt
- portable/CMakeLists.txt
Fix circular dependency in CMake project
Description
-----------
Move includes into an interface library.
The kernel and port link against this interface.
The port no longer links against the kernel, breaking the cycle.
In order for custom ports to also break the cycle, they must link against `freertos_kernel_include` instead of `freertos_kernel`.
Checklist:
----------
This PR introduces no code changes.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/687
> Fix circular dependency in CMake project

- History.txt
Description
-----------
Update History for Kernel Version 10.6.0
> Update History for Version 10.6.0

- CMakeLists.txt
- croutine.c
- portable/ThirdParty/GCC/Posix/utils/wait_for_event.h
Description
-----------
Fix clang compiler warnings
Test Steps
-----------
Built the `FreeRTOS/Demo/Posix_GCC` demo in the FreeRTOS/FreeRTOS repo with clang-14.
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/701
> Fix clang compiler warnings

- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
This PR updates MPU Region number used for task stack region so that MPU region numbers programmed on every context switch are continuous.
Test Steps
-----------
Run Soak tests on [STM32NUCLEO_H743ZI2](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil)
Checklist:
----------
> Update portSTACK_REGION in Cortex-M3 and M4 ports

- queue.c
- stream_buffer.c
- tasks.c
Description
-----------
This PR gives the fix for the bug reported in PR#[718](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/718)
Test Steps
-----------
Added the warning flag ```-Wconversion``` and run the [demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/AVR_ATMega323_WinAVR)
Before change 
```
../../Source/queue.c: In function 'xQueueGenericCreate':
../../Source/queue.c:489: warning: comparison between signed and unsigned
../../Source/queue.c: In function 'xQueueGiveFromISR':
../../Source/queue.c:1320: warning: conversion to 'UBaseType_t' from 'int' may alter its value
../../Source/queue.c: In function 'xQueueReceive':
../../Source/queue.c:1465: warning: conversion to 'UBaseType_t' from 'int' may alter its value
../../Source/queue.c: In function …
```
> Fix warning issue for warning in arithmetic conversion for UBaseType_t

- stream_buffer.c
Description
-----------
This PR removes the superfluous inclusion of <stdint.h> in streambuffer.c file , as stdint gets included in FreeRTOS.h
Test Steps
-----------
Build and Run [Demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil/Projects/GCC)  on STM32 platform.
Checklist:
----------
> Remove stdint.h in stream buffer file

- portable/GCC/RL78/port.c
- portable/ThirdParty/GCC/Posix/port.c
Align some Linux and RL78 port types with other ports
Description
-----------
POSIX and RL78 port layers still use portSTACK_TYPE and portBASE_TYPE while it was changed to StackType_t and BaseType_t everywhere else.
Test Steps
-----------
no steps
Checklist:
----------
Related Issue
-----------
no issue id
> Align some Linux and RL78 port types with other ports

- portable/ThirdParty/GCC/RP2040/include/portmacro.h
- tasks.c
Fix Pico compile warning
Description
-----------
As #731 reported, there is a compile warning message in Ubuntu/GCC environment.
This change fixes the warning message by removing redundant condition.
Test Steps
-----------
- Compile Pico project
Checklist:
----------
Related Issue
-----------
> Fix Pico compile warning

- portable/MSVC-MingW/port.c
Enable MSVC Port to leave the prvProcessSimulatedInterrupts loop when scheduler is stopped
Description
-----------
At the moment, the prvProcessSimulatedInterrupts is stuck in an endless loop even when the scheduler is stopped. This change pulls the xPortRunning Flag (which is set to false by vPortEndScheduler() within the loop. If set to false the loop is exited.
However this is needed when FreeRTOS based modules are tested using GoogleTest (otherwise the test won't stop)
Checklist:
----------
Related Issue
-----------
> Enable MSVC Port to leave the prvProcessSimulatedInterrupts loop when scheduler is stopped

- .github/workflows/kernel-demos.yml
- tasks.c
Description
-----------
The change addresses the following warning:
```
tasks.c:5549:40: warning: assignment discards 'volatile' qualifier from
pointer target type [-Wdiscarded-qualifiers]
5549 |             pxTaskStatus->pxTopOfStack = pxTCB->pxTopOfStack;
|
```
Also add the "Build Posix_GCC Demo for Coverage Test" in the PR checks as coverage test target treats warnings as errors and therefore, will catch such warnings in PR checks.
Test Steps
-----------
Built the POSIX demo locally with the following command -
```
make -j COVERAGE_TEST=1
```
> Fix warning in vTaskGetInfo

- portable/MemMang/heap_2.c
Fix bug of heap_2 introduced by [pr738](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/738)
Description
-----------
In secure_heap\heap_4\heap_5, the list of free blocks is linked by the block **address**.
In heap_2,  the list of free blocks is linked by the block **size**.
In heap_2, when a large free block is split into a smaller free block and a using block, we have to iterate the list of free blocks to find the right place to insert the smaller free block.
With [pr738 ](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/738), I mistakenly changed heap_2 along with other heap, now I have fixed this bug and added some comment in heap_2. 
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and …
> Fix bug of heap_2 introduced by pr738.

- include/picolibc-freertos.h
- portable/GCC/ARM_CR5/port.c
Description
-----------
The  `pxTopOfStack` calculation in `configINIT_TLS_BLOCK` for picolib needs to decrement  `pxTopOfStack`  in order to meet the expectation of `pxPortInitialiseStack` function. 
Details described in https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/714.
Test Steps
-----------
Described in attached issue. 
Checklist:
----------
Related Issue
-----------
* https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/714
> Fix pxTopOfStack calculation in configINIT_TLS_BLOCK for picolib

- portable/Common/mpu_wrappers_v2.c
Description
-----------
MPU wrapper for `vTaskDelete` called `vTaskDelete` first and then freed the slot in the Kernel Object Handle Pool. When a task deletes itself, any instruction after `vTaskDelete` is not executed. As a result, when a task deleted itself, we were not freeing the corresponding slot in the Kernel Object Handle Pool thereby, exhausting the pool eventually. This PR fixes the issue by freeing the slot in Kernel Object Handle Pool first and then calling  `vTaskDelete`.
Test Steps
-----------
1. Create a Privileged task, Task1, with priority 1. 
2. Task1 creates another privileged task, Task2, with priority 2.
3. Task2 deletes itself by calling vTaskDelete.
```c
/* Task1's priority is 1. */
void Task1( void * pvParam )
{
BaseType xTaskCreationResult;
( void ) pvParam;
for( …
```
> Fix MPU wrapper for vTaskDelete for calling task deletion

- portable/ARMv8M/secure/heap/secure_heap.c
- portable/GCC/ARM_CM23/secure/secure_heap.c
- portable/GCC/ARM_CM33/secure/secure_heap.c
- portable/GCC/ARM_CM35P/secure/secure_heap.c
- portable/GCC/ARM_CM55/secure/secure_heap.c
- portable/GCC/ARM_CM85/secure/secure_heap.c
- portable/IAR/ARM_CM23/secure/secure_heap.c
- portable/IAR/ARM_CM33/secure/secure_heap.c
- portable/IAR/ARM_CM35P/secure/secure_heap.c
- portable/IAR/ARM_CM55/secure/secure_heap.c
- portable/IAR/ARM_CM85/secure/secure_heap.c
Description
-----------
This includes improvements like addition overflow checks, readability improvements. 
Test Steps
-----------
Tested locally.
Checklist:
----------
> Bring the heap_4 improvements to secure_heap

- tasks.c
Description
-----------
Stack alignment adjustment for targets of which stack grows upwards is missing. Added it.
Test Steps
-----------
Not tested as such target should be rare and I don't have such devices.
Checklist:
----------
Related Issue
-----------
> Add missing stack alignment adjustment if stack grows upwards

- .github/lexicon.txt
- event_groups.c
- include/event_groups.h
- include/queue.h
- portable/Common/mpu_wrappers_v2.c
- queue.c
- tasks.c
Description
-----------
This commit adds runtime checks for function parameters to mpu_wrappers_v2 file. The same checks are performed
in the API implementation using asserts.
Test Steps
-----------
Ran the soak tests on STM32H7-NUCLEO board.
Checklist:
----------
> Add runtime parameter checks

- tasks.c
Description
-----------
For `vTaskPrioritySet` with mutex enabled,  there are three situations:
- The task doesn’t hold a mutex, or the mutex doesn’t inherit priority yet.
- The task has inherit priority from mutex, and we are setting a new priority bigger than the inherited priority.
- The task has inherit priority from mutex, and we are setting a new priority not bigger than the inherited priority.
For case 1, we can directly change task’s running priority;
For case 3, we shoudn’t change task’s running priority;
For case 2, I think we should change the task’s running priority to the bigger priority.
Case 1 is already handled in the existing code, this PR is handling case 2.
The previous discussion is in [Here](https://forums.freertos.org/t/question-about-vtaskpriorityset-with-mutex-enabl …
> Use the bigger priority whenever possible.

- portable/ARMv8M/non_secure/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM35P/non_secure/port.c
- portable/GCC/ARM_CM35P_NTZ/non_secure/port.c
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM55/non_secure/port.c
- portable/GCC/ARM_CM55_NTZ/non_secure/port.c
- portable/GCC/ARM_CM85/non_secure/port.c
- portable/GCC/ARM_CM85_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM3/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM35P/non_secure/port.c
- portable/IAR/ARM_CM35P_NTZ/non_secure/port.c
- portable/IAR/ARM_CM4F/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/portasm.s
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/IAR/ARM_CM55/non_secure/port.c
- portable/IAR/ARM_CM55_NTZ/non_secure/port.c
- portable/IAR/ARM_CM7/r0p1/port.c
- portable/IAR/ARM_CM85/non_secure/port.c
- portable/IAR/ARM_CM85_NTZ/non_secure/port.c
- portable/RVDS/ARM_CM4_MPU/portmacro.h
- timers.c
Description
-----------
Fix remarks emitted by IAR compiler
Test Steps
-----------
Built and tested locally.
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/757
> Fix remarks emitted by IAR compiler

- include/FreeRTOS.h
- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Implement configENABLE_HEAP_PROTECTOR.
Description
-----------
* Setting `configENABLE_HEAP_PROTECTOR` to `1` obfuscates heap block pointers by XORing them with an application supplied canary value. This obfuscation helps to catch heap corruption should a heap buffer overflow occur. 
* This PR also adds heap bounds checking to heap_4 and heap_5.
* This PR also adds some additional integer underflow checks. 
Test Steps
-----------
Test harnesses to verify the effect of the change in the POSIX simulator are available here:
* https://github.com/oliverlavery/FreeRTOS/tree/heap-harness
* https://github.com/oliverlavery/FreeRTOS/tree/heap-harness-5
With `configENABLE_HEAP_PROTECTOR` set to 1, overwriting a free list block leads to an assert on an out of bounds heap pointer. I have also manually …
> Heap protect

- portable/MemMang/heap_5.c
Update block validate macro in heap_5
Description
-----------
When configENABLE_HEAP_PROTECTOR is not set in heap_5, `pucHeapHighAddress `and `pucHeapLowAddress` won't be updated.
The following assert is always triggered.
```
#define heapVALIDATE_BLOCK_POINTER( pxBlock )                       \
configASSERT( ( pucHeapHighAddress != NULL ) &&                     \
( pucHeapLowAddress != NULL ) &&                      \
( ( uint8_t * ) ( pxBlock ) >= pucHeapLowAddress ) && \
( ( uint8_t * ) ( pxBlock ) < pucHeapHighAddress ) )
```
This PR upate the `heapVALIDATE_BLOCK_POINTER` macro when configENABLE_HEAP_PROTECTOR is not set to 1.
Test Steps
-----------
Run the WIN32-MSVC demo 
Before this pull request
```
Trace started.
The trace will be dumped to the file "Trace.dump" whenever a call to …
```
> Update block validate macro in heap_5

- tasks.c
Description
-----------
* Use for loop instead of while loop for INFINITE_LOOP control
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
Address #750 comment in line [290](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/750/files#diff-c396ff4650e7f6957c0fd758574eb5d39b71761458868c1053a1c979d8563276R290)
> Update INFINITE_LOOP control

- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
Without this change, the code produces the following warning when compiled with ```-Wcast-align``` flag:
```
cast increases required alignment of target type
```
Test Steps
-----------
1. Build the code and see that it does not produce any warning.
2. Run soak tests on GCC ARM CM3 and CM4 platforms.
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/freertos-heap-4-c-cast-error/18105
> Fix cast alignment warning in heap_4.c and heap_5.c

- portable/MemMang/heap_4.c
Description
-----------
This heap calculation issue was introduced in PR 771.
Test Steps
-----------
Before - Malloc failed hook fires on first invocation of pvPortMalloc.
After - pvPortMalloc works as expected.
Checklist:
----------
> Fix heap address calculation issue

- stream_buffer.c
Description
-----------
This PR addresses the bug in xStreamBufferCreateStatic() API when xBufferSizeBytes is less than sbBYTES_TO_STORE_MESSAGE_LENGTH .
Static creation of StreamBuffer of BufferSize <= sbBYTES_TO_STORE_MESSAGE_LENGTH can be allowed , in case it is not a MessageBuffer.
Test Steps
-----------
Executing this code 
```
void pvTask1( void *pvParameters )
{
( void ) pvParameters;
StreamBufferHandle_t xStreamBuffer;
uint8_t ucBufferStrorage;
StaticStreamBuffer_t xStaticStreamBuffer;
xStreamBuffer = xStreamBufferCreateStatic( 1, 1, &ucBufferStrorage, &xStaticStreamBuffer );
configASSERT( xStreamBuffer != NULL );
}
```
**Before applying the patch :** 
StreamBuffer creation fails and assert occurs at
```
configASSERT( xBufferSizeBytes > sbBYTES_TO_STORE_MESSAGE_LENGTH );
``` …
> Fix xStreamBufferCreateStatic() API for buffer size <= 4

- include/mpu_prototypes.h
Description
-----------
MPU_vTaskAllocateMPURegions was declared incorrectly as vTaskAllocateMPURegions in mpu_prototypes.h.
Related Issue
-----------
https://forums.freertos.org/t/warning-redundant-redeclaration-of-vtaskallocatempuregions/18216/2
> Fix prototype in mpu_prototypes.h

- include/FreeRTOS.h
- tasks.c
Description
-----------
This PR introduces `configKERNEL_PROVIDED_STATIC_MEMORY` option which the application can set to 1 to use the default implementations of `vApplicationGetIdleTaskMemory` and `vApplicationGetTimerTaskMemory` functions.
If the application enables static allocation (i.e. sets `configUSE_STATIC_ALLOCATION` to 1) and does not provide the above 2
functions, it will result in linker error. The application has two options:
1. Set `configKERNEL_PROVIDED_STATIC_MEMORY` to 1 to use the default implementations of these functions.
2. Provide implementations of these 2 functions.
Note that default definitions are only available for non-MPU ports. The reason is that the stack alignment requirements vary for different architectures. 
Test Steps
-----------
Build a FreeRTOS project …
> Add default implementations of vApplicationGetIdleTaskMemory and vApplicationGetTimerTaskMemory

- .github/workflows/kernel-demos.yml
Description
-----------
This PR removes the dependency to build the CORTEX_M3_MPS2_QEMU_GCC demo in the CI checks for FreeRTOS+Kernel repository , since this demo is removed from the FreeRTOS repository.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
[#1089](https://github.com/FreeRTOS/FreeRTOS/pull/1089)
> Remove CORTEX_M3_MPS2_QEMU_GCC Demo from yaml file

- include/queue.h
Description
-----------
Fixed typo in the code comments. xQueueSendToFromFromISR --> xQueueSendToFrontFromISR.
Test Steps
-----------
NA.
Checklist:
----------
> Fix typo in the code comments

- croutine.c
- event_groups.c
- include/FreeRTOS.h
- list.c
- queue.c
- stream_buffer.c
- tasks.c
- timers.c
Add Trace Hook Macros to all API calls
Description
-----------
This pull-request adds out-of-the-box support for different tracing tools.
For more information see following forum post: https://forums.freertos.org/t/add-tracing-functionality-for-all-api-calls/18007.
New trace hook macros have been added for all public API functions, one for each function entry and one for each exit.
There are no functional changes, as the macros are by default empty.
Test Steps
-----------
N/A
Checklist:
----------
> Add Trace Hook Macros to all API calls

- tasks.c
Description
-----------
Update the pxMutexHolder is NULL comment in tasks.c. If the mutex is taken by an interrupt, the mutex holder is NULL. Priority inheritance is not applied when a task wants to take the mutex tasken by an interrrupt.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update pxMutexHolder is NULL comment

- portable/ARMv8M/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM23/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM23_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM33/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM33_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM35P/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM35P_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM55/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM55_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM85/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM85_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM23/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM23_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM33/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM33_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM35P/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM35P_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/IAR/ARM_CM55/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM55_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM85/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM85_NTZ/non_secure/portmacrocommon.h
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Reduce memory usage of ACL.
Description
-----------
ACL is a bitmap of kernel objects, every bit represent access control of a kernel object.
The memory usage should be configPROTECTED_KERNEL_OBJECT_POOL_SIZE / portACL_ENTRY_SIZE_BITS.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Reduce memory usage of ACL.

- portable/ARMv8M/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM23/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM23_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM33/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM33_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM35P/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM35P_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM55/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM55_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM85/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM85_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM23/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM23_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM33/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM33_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM35P/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM35P_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/IAR/ARM_CM55/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM55_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM85/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM85_NTZ/non_secure/portmacrocommon.h
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
This PR removes variable portACL_ENTRY_SIZE_BYTES from port header files , since it was only declared and not getting utilized.
Test Steps
-----------
Tested on STM32-H7.
Checklist:
----------
> Remove variable portACL_ENTRY_SIZE_BYTES from ACL

- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/RVDS/ARM_CM4_MPU/mpu_wrappers_v2_asm.c
- portable/RVDS/ARM_CM4_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
A task's privilege level is stored in `ulTaskFlag` member in the TCB. Current implementation of `portSWITCH_TO_USER_MODE()` does not update this flag but just lowers the processor's privilege level. This results in many APIs incorrectly determining task's privilege level and access permissions - 
* xPortIsAuthorizedToAccessBuffer
* xPortIsTaskPrivileged
* xPortIsAuthorizedToAccessKernelObject
This PR fixes the `portSWITCH_TO_USER_MODE()` implementation to correctly update the `ulTaskFlag` member in the TCB before lowering the processor's privilege level.
Test Steps
-----------
Tested on Cortex-M7.
Checklist:
----------
Related Issue
-----------
NA.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Fix portSWITCH_TO_USER_MODE() on Armv7-M MPU ports

- include/FreeRTOS.h
- include/task.h
- tasks.c
Description
-----------
This change necessitates the introduction of 2 new APIs:
```c
void vTaskListTasks( char * pcWriteBuffer, size_t uxBufferLength );
void vTaskGetRunTimeStatistics( char * pcWriteBuffer, size_t uxBufferLength );
```
These 2 APIs behave exactly as `vTaskList` and `vTaskGetRunTimeStats` except the fact that they take the length of the `pcWriteBuffer` as the second argument to ensure that we do not write past the buffer.
`vTaskList` and `vTaskGetRunTimeStats` assume that the length of the buffer is `configSTATS_BUFFER_MAX_LENGTH` which defaults to `0xFFFF`. This is done to ensure that the existing applications do not break. New applications should use the new APIs to avoid memory corruption.
Test Steps
-----------
Tested behavior of these APIs for various buffer sizes on …
> Replace sprintf with snprintf

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Aligns the stack end to a page boundary before computing its size, since the size depends on both the start and end.
The original change which introduced stack alignment (#674) only worked for cases where the round + trunc operation would wind up within the same area, but would lead to segfaults in other cases.
Tested on ARM64 and Intel MacOS, as well as ARM64 and Intel Linux.  The test cases included a single-task case, as well as a case with two tasks passing queue messages.
Test Steps
-----------
Using the Posix port on an M1 Mac, create a task with the default `PTHREAD_STACK_MIN` 
or some other "lucky" size.  The task can do nothing more than delay in a loop, and you should
get a segfault.  If not, a different stack size will cause one.  Example backtrace:
``` …
```
> bugfix: correct computation of stack size on Mac Posix port

- .github/scripts/kernel_checker.py
- portable/template/port.c
- portable/template/portmacro.h
- sample_configuration/FreeRTOSConfig.h
the template port, example project and sample configuration are expected to be incorporated into user code and therefore should not have a copyright or license.  All users are free to use these files in their projects and modify them as they see fit without restrictions.
> removed the copyright and license header for select files

- include/FreeRTOS.h
- tasks.c
Description
-----------
* Implement prvYieldCore with macro
* Remove the portCHECK_IF_IN_ISR macro check. It is not required in SMP now
* Not checking current task is scheduled to yield in prvYieldCore. When a task entering the critical section, the logic in [prvCheckForRunStateChange ](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/2f94b181a2f049ec342deba0927bed51f7174ab0/tasks.c#L704) ensures that the run state of current task is not `taskTASK_SCHEDULED_TO_YIELD`
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
Address #750 comment in line 760
> Implement prvYieldCore with macro

- tasks.c
Description
-----------
* Move trace macro after declaration to comply with ISO C90
Test Steps
-----------
Before this PR
```
/mnt/c/msys64/home/chinglee/kernel/init_review/test/FreeRTOS/FreeRTOS/Source/tasks.c: In function ‘vTaskPrioritySet’:
/mnt/c/msys64/home/chinglee/kernel/init_review/test/FreeRTOS/FreeRTOS/Source/tasks.c:2468:13: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
2468 |             BaseType_t xYieldForTask = pdFALSE;
|             ^~~~~~~~~~
/mnt/c/msys64/home/chinglee/kernel/init_review/test/FreeRTOS/FreeRTOS/Source/tasks.c: In function ‘xTaskIncrementTick’:
/mnt/c/msys64/home/chinglee/kernel/init_review/test/FreeRTOS/FreeRTOS/Source/tasks.c:4382:5: error: ISO C90 forbids mixed declarations and code …
```
> Move trace macro after declaration 

- include/FreeRTOS.h
- queue.c
- tasks.c
- timers.c
Description
-----------
Use the following pattern for loop control in unit test.
```
for( ; configCONTROL_INFINITE_LOOP(); )
{
....
}
```
In the unit test, the configCONTROL_INFINITE_LOOP can be defined to a mocked function for loop controlling.
```
#define configCONTROL_INFINITE_LOOP vFakeInfinitLoop
```
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
Address #750 comment in line 290.
> Use INFINITE_LOOP macro for loop control in unit test

- include/FreeRTOS.h
- tasks.c
Separate the task create function for core affinity
Description
-----------
Create the following private function to create task:
* prvCreateStaticTask
* prvCreateRestrictedStaticTask
* prvCreateRestrictedTask
* prvCreateTask
uxCoreAffinityMask and prvAddNewTaskToReadyList are still required to be called to setup core affinity and add the task to ready list.
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
Address #750 in comment 1151, 1625
> Separate the task create function for core affinity

- timers.c
Title
-----------
Make Timer Service Task core affinity configurable
Description
-----------
This PR introduces the `configTIMER_SERVICE_TASK_CORE_AFFINITY` config option which allows a user to set the core affinity of the Timer Service Task on SMP systems. The motivation to have this feature comes from requests such as [this](https://github.com/espressif/esp-idf/issues/12204#issuecomment-1709830113) and [this](https://github.com/espressif/esp-idf/issues/10315) on the ESP-IDF repository. It would be nice if the FreeRTOS-Kernel can support this natively.
Test Steps
-----------
N.A
Checklist:
----------
Related Issue
-----------
None
> Add option to set the core affinity for the Timer Svc Task on SMP systems

- include/FreeRTOS.h
- include/mpu_prototypes.h
- include/mpu_wrappers.h
- include/task.h
- portable/Common/mpu_wrappers_v2.c
- tasks.c
Description
-----------
* Add uxTaskBasePriorityGet and uxTaskBasePriorityGetFromISR to get the base priority.
The unit test is added in this PR https://github.com/FreeRTOS/FreeRTOS/pull/1099.
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
#811
> Add base priority get APIs

- tasks.c
Description
-----------
Fixes the bug described in this issue: https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/612. This was originally contributed in this PR: https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/625.
The implementation suspends the scheduler before exiting the critical section (i.e. before enabling interrupts).  If we do not do so, a notification sent from an ISR, which happens after exiting the critical section and before suspending the scheduler, will get lost. The sequence of events will be:
1. Exit critical section.
2. Interrupt - ISR calls `xTaskNotifyFromISR` which adds the task to the Ready list.
3. Suspend scheduler.
4. `prvAddCurrentTaskToDelayedList` moves the task to the delayed or suspended list.
5. Resume scheduler does not touch the task (because it is not …
> Fix xTaskNotifyWait & ulTaskNotifyTake determinism.

- cmake_example/main.c
Description
-----------
This PR fixes reliability issues in Sonar Cloud [tests](https://sonarcloud.io/summary/new_code?id=FreeRTOS_FreeRTOS-Kernel&branch=main), caused by unreachable code.
Test Steps
-----------
Re-run the Sonar cloud tests for reliability.
Checklist:
----------
> Fix reliability issues in CMake sample

- portable/Common/mpu_wrappers_v2.c
Description
-----------
Fix possible integer overflow.
Test Steps
-----------
Checklist:
----------
> Fix possible integer overflow

- portable/Common/mpu_wrappers_v2.c
Description
-----------
The PR https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/836 addresses a potential integer overflow.
Test Steps
-----------
Checklist:
----------
> Backport PR 836 to FreeRTOS-Kernel V10.6.1

- portable/Common/mpu_wrappers_v2.c
Description
-----------
This PR removes redundant API calls in MPU wrappers for the following Queue APIs
1. MPU_xQueueGenericSend
2. MPU_xQueueGenericReceive
3. MPU_xQueuePeek
Test Steps
-----------
Checklist:
----------
> Removes redundant API calls in MPU wrappers

- .github/workflows/kernel-checks.yml
Description
-----------
Use echo groups on the header check
Perform sparse checkout of just the .github folder for the header check instead of all the files.
Update python checkout version being used.
Update the version of the get changed files action being used.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Kernel Checker CI Workflow File Updates

- CMakeLists.txt
To build a complete static application (configSUPPORT_DYNAMIC_ALLOCATION set to 0) an ugly workaround is necessary. When FREERTOS_HEAP (CMake variable) is not set, heap 4 is automatically selected in the current CMake. Without this change I got the following error:
`/home/boris/workspace/base/external/freertos/portable/MemMang/heap_4.c:51:6: error: #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0
51 |     #error This file must not be used if configSUPPORT_DYNAMIC_ALLOCATION is 0`
For additional context, please read: https://forums.freertos.org/t/i-cannot-build-a-complete-static-application-bug-or-feature/9553
-----------
I opted to modify the default behavior of the FREERTOS_HEAP CMake variable because I believe it's essential for the user to be conscious of the …
> Remove default behaviour of FREERTOS_HEAP.

- include/FreeRTOS.h
- include/task.h
- tasks.c
Description
-----------
SMP is enabled/disabled via the `configNUMBER_OF_CORES` option. This PR simply renames all occurrences of `CPU` to `Core` in any public facing API for naming consistency. The following APIs have been renamed:
- `traceENTER_xTaskGetCurrentTaskHandleCPU` -> `traceENTER_xTaskGetCurrentTaskHandleForCore`
- `xTaskGetCurrentTaskHandleCPU` -> `xTaskGetCurrentTaskHandleForCore`
This commit renames "CPU" to "Core" for any public facing API for consistency with other SMP related APIs (e.g., "configNUMBER_OF_CORES").
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Rename "CPU" to "Core"

- .github/workflows/coverity_scan.yml
- README.md
Description
-----------
This PR adds nightly coverity scan job to the FreeRTOS-Kernel which is scheduled to be run at 1:15 AM UTC daily.
Builds the minimal [cmake_example](https://github.com/FreeRTOS/FreeRTOS-Kernel/tree/main/examples/cmake_example) project using cov_build and uploads to [coverity scan](https://scan.coverity.com/projects/freertos-kernel) for analysis.
Test Steps
-----------
Tested on fork:
- [Example run](https://github.com/tony-josi-aws/FreeRTOS-Kernel/actions/runs/6637851834/job/18032992133)
Checklist:
----------
- ~[ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.~ NA
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Add nightly coverity scan

- tasks.c
Description
-----------
The function vTaskSwitchContext in smp has an parameter of core id, which means this function is not only used for the core who call it. 
Thus we should use the task running on the specific core id, instead of use the task running on the core who call this function.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix vTaskSwitchContext for smp.

- include/projdefs.h
Description
-----------
This PR adds a simple `pdTICKS_TO_MS()` convenience macro to convert time in ticks to time in milliseconds.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Add pdTICKS_TO_MS macro

- include/task.h
- tasks.c
Description
-----------
Compatibility update for get idle task memory. The prototype for `vApplicationGetIdleTaskMemory` is different for single core and SMP due to the passive idle task memory.
The original implementation.
```c
#if configNUMBER_OF_CORES == 1
void vApplicationGetIdleTaskMemory( StaticTask_t ** ppxIdleTaskTCBBuffer,
StackType_t ** ppxIdleTaskStackBuffer,
uint32_t * pulIdleTaskStackSize );
#else
void vApplicationGetIdleTaskMemory( StaticTask_t ** ppxIdleTaskTCBBuffer,
StackType_t ** ppxIdleTaskStackBuffer,
uint32_t * pulIdleTaskStackSize,
BaseType_t xCoreID );
#endif
```
This brings compatibility problem for single core and SMP. Compile option `#if configNUMBER_OF_CORES == 1` has to be used in application to built with single core and SMP. This PR tries to reduce the …
> Add vApplicationGetPassiveIdleTaskMemory for SMP

- tasks.c
Description
-----------
In smp, every core has a idle task.
So the count of non application tasks(idle tasks) should be number of cores.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix eTaskConfirmSleepModeStatus for smp.

- portable/IAR/ARM_CM0/portmacro.h
Description
-----------
Fix missing semicolon in portEND_SWITCHING_ISR() in IAR/CM0/portmacro.h
Test Steps
-----------
Found when running ci on my repo https://github.com/hathach/tinyusb/actions/runs/6892688960/job/18750555563?pr=2320#step:5:7399
```
Error[Pe065]: 
expected a ";"
portYIELD_FROM_ISR(xHigherPriorityTaskWoken);
````
Checklist:
----------
Related Issue
-----------
- n/a
> Fix IAR/CM0/portmacro.h missing semicolon

- portable/CCS/ARM_CM3/port.c
- portable/CCS/ARM_CM3/portmacro.h
- portable/CCS/ARM_CM4F/port.c
- portable/CCS/ARM_CM4F/portmacro.h
- portable/CCS/ARM_Cortex-R4/port.c
- portable/CCS/ARM_Cortex-R4/portmacro.h
- portable/CCS/MSP430X/data_model.h
- portable/CCS/MSP430X/port.c
- portable/CCS/MSP430X/portmacro.h
Description
-----------
Revert the #768 PR on CCS ports
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Revert Portable/CCS formatting

- .github/workflows/coverity_scan.yml
Description
-----------
This PR updates the coverity scan yml script to do the coverity scan build and upload to single step.
Test Steps
-----------
[Tested on fork](https://github.com/tony-josi-aws/FreeRTOS-Kernel/actions/runs/6979086011/job/18991676061)
Checklist:
----------
Related Issue
-----------
> Update coverity scan build and upload to single step

- .github/workflows/coverity_scan.yml
Description
-----------
The curl command to send the report expects the tar file to be in its current directory. The step either needed to have the working-directory: set to the build directory, or the tar file needs to be created in the parent directory.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Coverity Report Directory Fix

- portable/Common/mpu_wrappers.c
Description
-----------
Fix prototype of MPU_vTimerSetReloadMode
Checklist:
----------
> Fix prototype of MPU_vTimerSetReloadMode

- include/stack_macros.h
The original rule 7.2 fix disappeared during the merge process.
Fix MISRA C 2012 rule 7.2 violation
Description
-----------
**MISRA C 2012 rule 7.2**
> A "u" or "U" suffix shall be applied to all integer constants that are represented in an unsigned type.
**MISRA violation**
MISRA enforces the use of the `U` or `u` suffix for unsigned integer constants.
The statement which leads to the violation
`const uint32_t ulCheckValue = ( uint32_t ) 0xa5a5a5a5;`
Test Steps
-----------
N/A.
Checklist:
----------
> Fix MISRA C 2012 rule 7.2 violation for stack macro

- event_groups.c
- include/list.h
- include/portable.h
- include/queue.h
- include/task.h
- include/timers.h
- list.c
- queue.c
- stream_buffer.c
- tasks.c
- timers.c
Description
-----------
FreeRTOS kernel now make use of coverity static analysis tool for MISRA and static analysis. Remove lint suppression in comment.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Remove lint suppression comment

- examples/sample_configuration/FreeRTOSConfig.h
Description
-----------
This PR updates the sample configuration file , to serve as a starting point for the application users.
The following config definitions are added :
1. configSTATS_BUFFER_MAX_LENGTH
2. configKERNEL_PROVIDED_STATIC_MEMORY
3. configENABLE_HEAP_PROTECTOR
4. configUSE_MPU_WRAPPERS_V1
5. configPROTECTED_KERNEL_OBJECT_POOL_SIZE
6. configSYSTEM_CALL_STACK_SIZE
7. configENABLE_ACCESS_CONTROL_LIST 
8. configNUMBER_OF_CORES
9. configRUN_MULTIPLE_PRIORITIES
10. configUSE_CORE_AFFINITY
11. configUSE_TASK_PREEMPTION_DISABLE
12. configUSE_PASSIVE_IDLE_HOOK
13. configTIMER_SERVICE_TASK_CORE_AFFINITY
Test Steps
-----------
NA
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Update sample configuration file 

- include/queue.h
- tasks.c
Description
-----------
Per request in a [FreeRTOS-Forum Post](https://forums.freertos.org/t/queue-documentation-references-to-portyield-from-isr-with-incorrect-parameter/18563) modify existing comments related to `portYIELD_FROM_ISR()` in `queue.h` to be more consistent with what is said in other header file comment blocks. Also mention the function is port specific in tasks.c
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update comments related to portYIELD_FROM_ISR()

- portable/IAR/ARM_CA5_No_GIC/portASM.h
- portable/IAR/ARM_CA9/portASM.h
- portable/IAR/MSP430/portasm.h
Description
-----------
Fix a build error in the MSP430 and Cortex A IAR ports caused by whitespace missing in asm macros.  Add whitespace to make sure all instruction mnemonics and assembler directives do not appear in the label field (column 1) of the line.
Test Steps
-----------
Build the msp430_IAR demo with and without this PR.  When building without this PR, the assembler gives the error "Error[14]: Missing #endif" for both serialASM.s43 and portext.s43.  When building with this PR, no error.
Note I did not test the Cortex A ports.  I don't have the IAR compiler/assembler for Cortex A.
Checklist:
----------
> Fix build error for MSP430 and Cortex A with IAR

- include/queue.h
Fix documentation for `xQueueTakeMutexRecursive`
Description
-----------
Fixes documentation for `xQueueTakeMutexRecursive` reported on the [forum](https://forums.freertos.org/t/incorrect-misleading-comment-in-queue-h/18843)
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix documentation for xQueueTakeMutexRecursive

- .github/.cSpellWords.txt
Description
-----------
Use Unix/GNU Sort instead of MacOS sort. MacOS version of sort will put capital letters at the end, GNU sort does not.
Add new common spelling words to the cSpellWordList to account for the issue mentioned in https://github.com/FreeRTOS/CI-CD-Github-Actions/pull/99
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Add new common words to the cSpellWordList.txt

- tasks.c
Description
-----------
All the cores start with idle tasks before the SMP scheduler is running.
In this PR:
* Assign idle task to each core when they are created in `prvCreateIdleTasks()`.
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
> Assign idle task to each core before the SMP scheduler start

- portable/ThirdParty/XCC/Xtensa/port.c
- portable/ThirdParty/XCC/Xtensa/portbenchmark.h
- portable/ThirdParty/XCC/Xtensa/portclib.c
- portable/ThirdParty/XCC/Xtensa/portmacro.h
- portable/ThirdParty/XCC/Xtensa/porttrace.h
- portable/ThirdParty/XCC/Xtensa/xtensa_api.h
- portable/ThirdParty/XCC/Xtensa/xtensa_config.h
- portable/ThirdParty/XCC/Xtensa/xtensa_context.h
- portable/ThirdParty/XCC/Xtensa/xtensa_init.c
- portable/ThirdParty/XCC/Xtensa/xtensa_intr.c
- portable/ThirdParty/XCC/Xtensa/xtensa_overlay_os_hook.c
- portable/ThirdParty/XCC/Xtensa/xtensa_rtos.h
- portable/ThirdParty/XCC/Xtensa/xtensa_timer.h
Description
-----------
Per this [FreeRTOS Forum Thread](https://forums.freertos.org/t/failed-to-build-freertos-demo-for-xtensa/18897)
Revert #768 on ThirdParty/XCC/Xtensa Portable directory
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Revert Formatting on the XCC/Xtensa portable files

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
This PR supress the unused variable `void * arg` in the `prvTimerTickHandler` in the [GCC/Posix/port.c](https://github.com/FreeRTOS/FreeRTOS-Kernel/compare/main...tony-josi-aws:FreeRTOS-Kernel:fix_posix_port_build?expand=1#diff-e52a551c2f42efff2bb76b7f63f1bdd88b6b2d740fe7a66fd684a462201eda4f)
Test Steps
-----------
Build check
Checklist:
----------
- ~[ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.~
Related Issue
-----------
>  Suppress unused variable in GCC posix prvTimerTickHandler()

- portable/CMakeLists.txt
Add MPU V2 support to CMake
Description
-----------
The current CMakeList.txt doesn't include the `mpu_wrappers_v2(_asm)?.c` files into the build when a MPU port is selected. So following the `Consume with CMake` steps in the README fails.
This PR add the necessary files to the CMake build.
I'm not 100% sure if the `GCC_ARM_CM(33|55|85)_TFM` ports need the wrappers, can somebody confirm this?
Checklist:
----------
> Add MPU V2 support to CMake build

- tasks.c
Make configSUPPORT_STATIC_ALLOCATION==1 an error for MPU ports
Description
-----------
The `vApplicationGet*TaskMemory()` functions are not generated for MPU ports even when `configSUPPORT_STATIC_ALLOCATION` is set.  This PR makes setting `configSUPPORT_STATIC_ALLOCATION` for MPU ports an error.  Copied explanation from https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/790#discussion_r1329997898
Checklist:
----------
> Make configSUPPORT_STATIC_ALLOCATION==1 an error for MPU ports

- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM3_MPU/portmacro.h
MPU assert for ARM_CM3_MPU
Description
-----------
This PR adds runtime check to see if the target even has a MPU. Copied over from ARM_CM4_MPU. All other CM3 and CM4 ports already have this check.
While I was copying I also copied over support for the external symbols when __ARMCC_VERSION is set.
Checklist:
----------
> MPU assert for ARM_CM3_MPU

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Pass the FreeRTOS task name to pthread via `pthread_setname_np()` for prettier output in debuggers. 
Tested on Linux, may need some fixes for macOS / *BSD
Test Steps
-----------
build any FreeRTOS-based app with posix port and run with attached debug
Checklist:
----------
-----------
> Posix port - set name for threads

- tasks.c
Update unpaired critical section in vTaskDelete for readability
Description
-----------
The implementation in vTaskDelete increase cognitive load as the critical section is unpaired due to single core and SMP implementation.
In this PR:
* Update the implementation to fix the unpaired critical section.
* Move the prvDeleteTCB out of the critical section
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update unpaired critical section in vTaskDelete for readability

- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
Description
-----------
Add a check for if the scheduler is running to [xPortIsAuthorizedToAccessBuffer()](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/V11.0.1/portable/GCC/ARM_CM4_MPU/port.c#L1517).
This fixes an issue where before the scheduler is started APIs can fail as the TCB pointed to by pxCurrentTCB may not have access to requested APIs.
Test Steps
-----------
Call [xTimerStart()](https://github.com/FreeRTOS/FreeRTOS/blob/main/FreeRTOS/Demo/CORTEX_MPU_Static_Simulator_Keil_GCC/main.c#L499), which calls [MPU_xTimerGenericCommandFromTask](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/V11.0.1/portable/Common/mpu_wrappers_v2.c#L3437):
```
xReturn = MPU_xTimerGenericCommandFromTaskEntry( &( xParams ) );
```
Which calls …
> Add check for if the scheduler is running to MPU ports

- tasks.c
Update for unpaired critical section in vTaskSuspend
Description
-----------
* Move the `taskEXIT_CRITICAL` out of the macro to improve readability.
Unit test is updated in this PR : https://github.com/FreeRTOS/FreeRTOS/pull/1160
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update for unpaired critical section in vTaskSuspend

- portable/ARMv8M/non_secure/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM35P/non_secure/port.c
- portable/GCC/ARM_CM35P_NTZ/non_secure/port.c
- portable/GCC/ARM_CM55/non_secure/port.c
- portable/GCC/ARM_CM55_NTZ/non_secure/port.c
- portable/GCC/ARM_CM85/non_secure/port.c
- portable/GCC/ARM_CM85_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM35P/non_secure/port.c
- portable/IAR/ARM_CM35P_NTZ/non_secure/port.c
- portable/IAR/ARM_CM55/non_secure/port.c
- portable/IAR/ARM_CM55_NTZ/non_secure/port.c
- portable/IAR/ARM_CM85/non_secure/port.c
- portable/IAR/ARM_CM85_NTZ/non_secure/port.c
Description
-----------
This is a duplicate of #954 but for ARMv8M Ports
Refer to #954 for more information about this change
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Add check for if the scheduler is running to ARMv8M MPU ports

- .github/workflows/kernel-demos.yml
- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Changes in #914 have caused the Posix GCC FreeRTOS Port to fail to build on MacOS
This PR fixes this issue by wrapping the resetting of a variable used when stopping the scheduler in an OS type check.
This PR also adds a Matrix configuration to the GitHub kernel-demo workflow to build the Posix Demos on MacOS
The exact commit that introduced the breaking change, per the git blame, can be found [here](https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/7ba4124c785e400cb0e8c3c17a49f390e90ba77e)
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix MacOS Posix port

- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM35P/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM23/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM23_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM35P/portmacro.h
- portable/GCC/ARM_CM23/non_secure/portmacro.h
- portable/GCC/ARM_CM23_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM33/non_secure/portmacro.h
- portable/GCC/ARM_CM33_NTZ/non_secure/portmacro.h
- portable/GCC/ARM_CM35P/non_secure/portmacro.h
- portable/GCC/ARM_CM35P_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM23/non_secure/portmacro.h
- portable/IAR/ARM_CM23_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM33/non_secure/portmacro.h
- portable/IAR/ARM_CM33_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM35P/non_secure/portmacro.h
- portable/IAR/ARM_CM35P_NTZ/non_secure/portmacro.h
Description
-----------
`configENABLE_MVE` is only applicable to Cortex-M55 and Cortex-M85 ports. It must not be defined to 1 for other ARMv8_m ports.
Test Steps
-----------
Built M23 and M33 example projects locally.
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/status-of-the-gcc-arm-cm55-and-ntz-ports/19042
> Add a check for configENABLE_MVE to M23, M33 ports

- portable/Common/mpu_wrappers_v2.c
Description
-----------
Rule 10.1 - Operands shall not be of an inappropriate essential type 
- Shift and bitwise operations shall not performed on operands of an essentially signed or enum type
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix MISRA C 2012 Rule 10.1 Violations

- portable/Common/mpu_wrappers_v2.c
Description
-----------
Fix MISRA C 2012 Rule 9.3 Violations - Arrays shall not be partially initialized
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix MISRA C 2012 Rule 9.3 Violations

- portable/Common/mpu_wrappers_v2.c
- queue.c
- tasks.c
Description
-----------
Fix violations for MISRA C 2012 Rule 10.3 - The value of an expression shall not be assigned to an object with a narrower essential type or of a different essential type category
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix MISRA C 2012 Rule 10.3 Violations

- portable/Common/mpu_wrappers_v2.c
Description
-----------
The MISRA C Directive 4.7 states that : _If a function returns error information, then that error information shall be tested_.
In this code, since we are not testing the return value of `xTaskResumeAll()` , it is encased with typecast _void_ to remove the warning.
Test Steps
-----------
NA
Checklist:
----------
> Fix MISRA directive 4.7 warning

- tasks.c
Description
-----------
MISRA rule 14.4 - The controlling expression of an if statement and the controlling expression of an iteration-statement shall have essentially boolean type. 
- macro listLIST_IS_EMPTY() returns pdTrue or pdFalse which are not of the essentially bool type (_Bool). By comparing the value it returns against 0, the expression evaluates to essentially boolean type.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix MISRA C 2012 Rule 14.4 Violations.

- include/FreeRTOS.h
Description
-----------
This PR updates the default configuration value of configSTACK_DEPTH_TYPE  in FreeRTOS.h configuration file to StackType_t.
Test Steps
-----------
Run and Build [MPU demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil) successfully.
Checklist:
----------
Related Issue
-----------
Bug reported in issue [986](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/986)
> Update default value of configSTACK_DEPTH_TYPE in config file

- examples/template_configuration/FreeRTOSConfig.h
- include/FreeRTOS.h
- tasks.c
Description
-----------
Add a config define to set the default core affinity mask for tasks created without an affinity mask specified via arguments.
Test Steps
-----------
Set configTASK_DEFAULT_CORE_AFFINITY to 1 and check if all tasks created without an affinity mask specified run on core 0.
Checklist:
----------
- [ x ] I have tested my changes. No regression in existing tests.
Related Issue
-----------
Closes #993.
> Add default core affinity config value.

- MISRA.md
- examples/coverity/CMakeLists.txt
- examples/coverity/coverity_misra.config
- include/FreeRTOS.h
- include/portable.h
- portable/ThirdParty/GCC/Posix/portmacro.h
- portable/template/port.c
- tasks.c
- Move the default value of `configUSE_MALLOC_FAILED_HOOK` as it is used in "portable.h"
- Add extra parenthesis in the definition of `portMAX_DELAY`.
- ~~Add check in the function `prvCreateIdleTasks` so that when the length of `configIDLE_TASK_NAME` is less than `configMAX_TASK_NAME_LEN` we do not go over `configIDLE_TASK_NAME`.~~
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix small bugs in Kernel

- croutine.c
Fix typo in croutine.c
Description
-----------
Fixes a small typo in a comment in croutine.c.
Test Steps
-----------
None
Checklist:
----------
None
Related Issue
-----------
None
> Fix typo in croutine.c

- examples/template_configuration/FreeRTOSConfig.h
Description
-----------
Update the comment for configKERNEL_INTERRUPT_PRIORITY in the template FreeRTOSConfig.h.
It was reported here - https://forums.freertos.org/t/migration-from-v10-5-1-to-v11-0-1-fails-with-new-freertosconfig-h-file/19276/
Checklist:
----------
Related Issue
-----------
[](https://forums.freertos.org/t/migration-from-v10-5-1-to-v11-0-1-fails-with-new-freertosconfig-h-file/19276/)
> Update comment in template FreeRTOSConfig.h

- include/list.h
- tasks.c
Description
-----------
`pxIndex` in `List_t` should only be used when selecting next task to run. Altering `pxIndex` of a ready list will cause the scheduler unable to select the right task to run.
Use `prvListTasksWithinSingleList` as an example. 
`prvListTasksWithinSingleList` is called in `uxTaskGetSystemState` and `pxIndex` is used to traverse the ready list in `listGET_OWNER_OF_NEXT_ENTRY`. This will cause the `pxIndex` points to a different task after `uxTaskGetSystemState` is called. Single core FreeRTOS make use of `pxIndex` to select next task to run. The scheduler will select wrong task since the `pxIndex` is moved. This also causes problem In FreeRTOS SMP as `pxIndex` is not moved in SMP and it should always point to `xListEnd`.
**Example code**
```c
TaskStatus_t …
```
> Not using pxIndex to iterate ready list in trace utility

- portable/ThirdParty/GCC/RP2040/include/portmacro.h
Description
-----------
Define portNOP in RP2040 port. This is used in [on target test](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Test/Target) for busy looping.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Define portNOP in RP2040 port

- include/FreeRTOS.h
Description
-----------
Add a compile time check that emits a helpful error message if the user attempts to create a daemon task startup hook without also creating the timer/daemon task.
The timer/daemon task startup hook runs in the context of the timer/daemon task.  Therefore, it won't run even if configUSE_DAEMON_TASK_STARTUP_HOOK is set to 1 if the timer task isn't created.  The timer task is only created if configUSE_TIMERS is not equal to 0.  
Test Steps
-----------
Manually checked as requires multiple compilations with different configurations.
Checklist:
----------
- [x ] I have tested my changes. No regression in existing tests.
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms …
> Add daemon task startup hook / timer task creation consistency check

- portable/MSVC-MingW/port.c
- portable/MSVC-MingW/portmacro.h
Improvement for 64bit Windows port
Description
-----------
1. 64bit TickType_t is supported. (MSVC and MinGW)
The case `configTICK_TYPE_WIDTH_IN_BITS == TICK_TYPE_WIDTH_64_BITS` is added in portmacro.h.
It is straightforward extension from 16bit and 32bit.
This change is based on the following discussion on the FreeRTOS forum.
https://forums.freertos.org/t/64bit-application-on-freertos-windows-port/19110
2. Unnecessary compiler warning is disabled locally. (MinGW-w64 only)
#pragma for ignoring the warning `cast-function-type` is added in port.c.
MinGW-w64 reports this warning for the for the cast operation from `TaskFunction_t` to `LPTHREAD_START_ROUTINE`.
This warning should be ignored because it is unavoidable. `TaskFunction_t` is an essential type in FreeRTOS and …
> Improvement for 64bit Windows port

- .github/workflows/kernel-demos.yml
Description
-----------
As part of FreeRTOS-Kernel CI-CD checks build the [FreeRTOS/FreeRTOS](https://github.com/FreeRTOS/FreeRTOS) demos for the [CORTEX_MPU_R4F_TI_RM46_HERCULES_GCC](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_R4F_TI_RM46_HERCULES_GCC ) and [CORTEX_MPU_R5F_TI_RM57_HERCULES_GCC](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_R5F_TI_RM57_HERCULES_GCC).
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
This change is blocked by: https://github.com/FreeRTOS/FreeRTOS/pull/1200, which fixes a build issue with the current mainline version of the Kernel.
> Add in CI-CD builds of the Cortex-Rx MPU Demos

- examples/cmake_example/main.c
- examples/coverity/README.md
Update coverity example README
Description
-----------
In this PR:
* Update coverity example README
* Refine the cmake_example/main.c file
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Update coverity example README

- portable/GCC/ARM_AARCH64/README.md
- portable/GCC/ARM_AARCH64_SRE/README.md
- portable/GCC/ARM_CA53_64_BIT/README.md
- portable/GCC/ARM_CA53_64_BIT_SRE/README.md
- portable/GCC/ARM_CA9/portASM.S
- portable/GCC/ARM_CR5/portASM.S
- portable/GCC/ARM_CRx_MPU/portASM.S
- portable/GCC/ARM_CRx_No_GIC/portASM.S
- portable/IAR/ARM_CRx_No_GIC/portASM.s
- portable/RVDS/ARM_CA9/portASM.s
- portable/ThirdParty/CDK/T-HEAD_CK802/port.c
- portable/ThirdParty/XCC/Xtensa/xtensa_context.h
Fix typos in comments: interace -> interface, swtich -> switch.
Description
-----------
Just about typos in source code comments.
Test Steps
-----------
Using grep to find all occurances of the typos. ;-)
Checklist:
----------
Related Issue
-----------
Thanks a lot for FreeRTOS,
Florian La Roche
> fix typos in comments: interace -> interface, swtich -> switch

- examples/template_configuration/FreeRTOSConfig.h
Description
-----------
This PR adds a new config option `configCHECK_HANDLER_INSTALLATION` and updates the description in the template configuration file.
Test Steps
-----------
NA
Checklist:
----------
> Add configCHECK_HANDLER_INSTALLATION description in template file

- portable/GCC/ARM_CR5/portASM.S
Update alignment in ARM_CR5 port.
This is the same patch as 553caa18ced4906cf5060823ada7a10e73c7b535 provided by Richard Barry for issue #426 (ARM_CA9).
Description
-----------
ARM_CA9 and ARM_CR5 are very close. This patch was applied to ARM_CA9, so it
might also make sense to apply it to ARM_CR5.
Test Steps
-----------
This was just observed by looking at the changes between A9 and R5, no real
testing was conducted.
Checklist:
----------
Related Issue
-----------
> Update the memory alignment within the Cortex-R5 port asm code

- examples/template_configuration/FreeRTOSConfig.h
Description
-----------
This PR adds the description and default value for `configUSE_EVENT_GROUPS` and `configUSE_STREAM_BUFFERS` in the template configuration file.
Test Steps
-----------
NA
Checklist:
----------
> Add event group and stream buffer config option in template

- include/list.h
Description
-----------
This PR updates use of the volatile qualifier with uxNumberOfItems to configLIST_VOLATILE to be inline with the use of this macro across the rest of the file.
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
#995 
> Replace volatile with configLIST_VOLATILE for uxNumberOfItems

- tasks.c
Description
-----------
The access macro `listGET_LIST_ITEM_OWNER` returns the owner `( pxListItem )->pvOwner` of a list item, which is a non-volatile variable. Hence this PR removes the `configLIST_VOALTILE` macro for the TCB in the API `prvListTasksWithinSingleList` . 
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
#995 
> Remove unwanted volatile keyword

- portable/GCC/RISC-V/portASM.S
- portable/IAR/RISC-V/portASM.s
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix the pxTopcOfStack typo in the RISC-V ports.

- include/FreeRTOS.h
- include/message_buffer.h
- include/stream_buffer.h
- stream_buffer.c
Add IRQ safe API for message buffer reset
Description
-----------
Allow reseting the message and stream buffers from IRQ context
Test Steps
-----------
called the new added API xMessageBufferResetFromISR from within interrupt context.
Checklist:
----------
Related Issue
-----------
> Add IRQ safe API for message buffer reset

- include/mpu_prototypes.h
- include/mpu_wrappers.h
- portable/Common/mpu_wrappers_v2.c
Description
-----------
This PR adds the MPU wrapper for `xStreamBufferResetFromISR` API in the secure MPU wrappers file. To use this wrapper, `configUSE_MPU_WRAPPERS_V1` must be set to 0.
Test Steps
-----------
Ran MPU soak tests on STM32H7ZI board.
Checklist:
----------
Related Issue
-----------
#1033 
> Add MPU wrapper from xStreamBufferResetFromISR

- include/task.h
Description
-----------
This PR fixes the build error: `comma at end of enumerator list [-Werror=pedantic]` for `eSleepModeStatus` enum.
Test Steps
-----------
Checklist:
----------
- ~[ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.~
Related Issue
-----------
> Fix build with C90

- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portasm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portasm.c
- portable/GCC/ARM_CM23/non_secure/portasm.c
- portable/GCC/ARM_CM23_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM33/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM33/non_secure/portasm.c
- portable/GCC/ARM_CM33_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM35P/non_secure/portasm.c
- portable/GCC/ARM_CM35P_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM55/non_secure/portasm.c
- portable/GCC/ARM_CM55_NTZ/non_secure/portasm.c
- portable/GCC/ARM_CM85/non_secure/portasm.c
- portable/GCC/ARM_CM85_NTZ/non_secure/portasm.c
Description
-----------
Currently in Armv8-M GCC/ArmClang ports, constant pool is used to define literals needed for `ldr` instruction. However, those constant pools are defined with `.align 4` which increases code size. Instead of defining the constant pool with `.align 4`, let the compiler hanlde the constant pool and the required alignment.
Benchmarking these changes using Cortex-M85 (Corstone-315) and blinky application in https://github.com/FreeRTOS/iot-reference-arm-corstone3xx/tree/main/applications/blinky shows a code size reduction of `72 bytes (GCC)` and `56 bytes (ArmClang)`.
Additional info:
Armv8-M IAR port doesn't use any constant pool. With these changes all three ports GCC/ArmClang/IAR are aligned.
Test Steps
-----------
Validated the changes using GCC and ArmClang and …
> armv8-m: GCC/ArmClang: Remove redundant constant pools

- .github/workflows/coverity_scan.yml
- MISRA.md
- event_groups.c
- examples/coverity/CMakeLists.txt
- examples/coverity/README.md
- queue.c
- stream_buffer.c
- tasks.c
Adding SMP coverity example
Description
-----------
In this PR:
* Add SMP coverity example. User can reference the ./examples/coverity/README.md to run coverity with SMP FreeRTOS.
* Suppress MISRA C:2012 directive 4.7 by comment. The return value of `taskENTER_CRITICAL_FROM_ISR()` is the interrupt mask. No error information will be returned by this function and no need to perform a check.
Test Steps
-----------
Run coverity 2023.6.1 with the following command should shows no violations.
Single core
```
cmake -B build -S examples/coverity
```
SMP
```
cmake -B build -S examples/coverity -DFREERTOS_SMP_EXAMPLE=1
```
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of …
> Adding SMP coverity example

- include/event_groups.h
- include/queue.h
- include/task.h
- portable/template/portmacro.h
- tasks.c
Description
-----------
This PR fix the MISRA C:2012 rule 7.2 deviations.
MISRA C:2012 rule 7.2 requires that
>A “u” or “U” suffix shall be applied to all integer constants that are represented in an unsigned type
**In this PR**:
* Use suffix "U" for unsigned constant.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Use suffix "U" for unsigned constant

- include/FreeRTOS.h
- include/portable.h
- include/queue.h
The:
```
#ifdef __cplusplus
extern "C" {
#endif
```
should come after any other includes.
> Move Header Includes Before Extern C

- portable/MSVC-MingW/port.c
Description
-----------
The variable `xPortRunning` is now updated before starting the first task.
Test Steps
-----------
Build and Run the following demo - https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/WIN32-MSVC
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/possible-bug-in-the-way-prvtimertask-thread-function-is-started-in-win32-port/19959/
> Update xPortRunning before resuming first task

- portable/MSVC-MingW/port.c
- portable/MSVC-MingW/portmacro.h
Add vPortGenerateSimulatedInterruptFromWindowsThread in MSVC port
Description
-----------
In the MSVC port of FreeRTOS, native Windows threads execute concurrently with FreeRTOS tasks and simulated interrupt handlers. Calling a FreeRTOS API from within a native Windows thread can lead to race conditions due to the concurrent execution. One way to enable synchronization between native Windows threads and FreeRTOS tasks is to make use of simulated interrupts. When a native Windows thread needs to invoke a FreeRTOS API, it generates a simulated interrupt and calls the FromISR API within the interrupt service routine (ISR).
The existing `vPortGenerateSimulatedInterrupt` function is designed to be called from within a FreeRTOS task, and it references the current thread structure. To facilitate …
> Add vPortGenerateSimulatedInterruptFromWindowsThread in MSVC port

- portable/GCC/ARM_AARCH64/port.c
- portable/GCC/ARM_AARCH64/portmacro.h
Description
-----------
NEON SIMD is required by standard AARCH64 and its registers are frequently utilized by standard functions such as memcpy(). This means that even simple tasks that do not use any floating point arithmetics may still alter the contents of the FPU registers.
For this reason it makes sense to add support for configUSE_TASK_FPU_SUPPORT to be able to enforce FPU register saving and restoring globally.
Without configUSE_TASK_FPU_SUPPORT it is not possible to enforce this for some library tasks.
This pull request partially fixes this issue:
https://forums.freertos.org/t/zynq-ultrascale-mpsoc-task-floating-point-corruption/9121
For a full fix `portASM.S` also needs to be adapted to save/restore all FPU registers at interrupt entry/exit.
Maybe I will find time to contribute …
> Add configUSE_TASK_FPU_SUPPORT to AARCH64 port

- list.c
Description
-----------
Improve comments to help people when debugging. This would have saved me weeks of time. An uninitialized binary semaphore (ie: one which has not been given yet) will result in getting stuck inside of `vListInsert()`. You must give it before taking it. 
Test Steps
-----------
Create a semaphore, start the scheduler, try to take it. You'll get stuck in a debugger inside the for loop in `VListInsert()`. 
Now, right after creating it, but before starting the scheduler, give it. Start the scheduler. Now, when it is taken it works fine. 
Checklist:
----------
_Can someone please run necessary tests on your end to ensure this is behavior you see too?_
Related Issue
-----------
NA
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute …
> list.c: improve code comments to point to official documentation about problems which may cause code to get stuck inside of list.c

- portable/MSVC-MingW/port.c
Description
-----------
Earlier the code was suspending the current thread after calling vTaskSwitchContext. This left a gap where the current thread could access incorrect pxCurrentTCB after it was changed by vTaskSwitchContext.
This PR addresses the problem by suspending the current thread before calling vTaskSwitchContext.
Test Steps
-----------
Build and run the following demo - https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/WIN32-MSVC
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1054.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your …
> Fix race in prvProcessSimulatedInterrupts

- list.c
Description
-----------
As pointed out by Jeff Tenney, the comment introduced in the PR is not accurate.
Test Steps
-----------
I verified using the following code snippet:
```c
void Task( void * param )
{
SemaphoreHandle_t xBinarySem;
( void ) param;
xBinarySem = xSemaphoreCreateBinary();
xSemaphoreTake( xBinarySem, portMAX_DELAY );
for( ;; )
{
HAL_GPIO_TogglePin( LD1_GPIO_Port, LD1_Pin );
vTaskDelay( pdMS_TO_TICKS( 1000 ) );
}
}
void app_main( void )
{
xTaskCreate( Task,
"Task",
configMINIMAL_STACK_SIZE,
NULL,
tskIDLE_PRIORITY | portPRIVILEGE_BIT,
NULL );
vTaskStartScheduler();
for( ;; );
}
```
Checklist:
----------
Related …
> Revert the change introduced in PR #1051

- examples/template_configuration/FreeRTOSConfig.h
configUSE_POSIX_ERRNO was missing so now it is added.
.clang-format reformatted the file somewhat.
> added configUSE_POSIX_ERRNO to the template FreeRTOSConfig.h

- examples/cmake_example/main.c
- portable/template/portmacro.h
Description
-----------
This PR adds the `_Noreturn` attribute in the coverity example configuration where a function is used that does not return.
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
[1057](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1057)
> Add Noreturn attribute in template port for static analysis

- tasks.c
Description
-----------
Update documentation of prvGetExpectedIdleTime
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/potential-xnumofoverflows-bug-when-tickless-idle-is-enabled/10846/
> Update documentation of prvGetExpectedIdleTime

- examples/template_configuration/FreeRTOSConfig.h
Description
-----------
Just a minimal typo in comments. A space char added between words.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> typo: add space to examples/template_configuration/FreeRTOSConfig.h

- tasks.c
Description
-----------
MISRA-C 2012 rule 10.4 states that : _Both operands of an operator in which the usual arithmetic conversions are performed shall have the same _essential type category__.
In tasks.c , Line 3937
`else if( uxHigherPriorityReadyTasks != pdFALSE )`
Where `uxHigherPriorityReadyTasks` is an unsigned char and `pdFALSE` is a signed char, thereby violating the rule.
This PR addresses this issue by making the variable `xHigherPriorityReadyTasks` a signed char.
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
#1066 
> Change UBaseType_t to BaseType_t for a boolean variable

- portable/MSVC-MingW/portmacro.h
Add missing `Extern "C"` to MSVC portmacro.h as a fix for issue #1064
Description
-----------
It appears that in merge request https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1047 The C++ block was reduced to not include the transitive header includes. This makes sense but revealed the lack of the `extern "C"` guard in the MSVC-MingW/portmacro.h header.
Test Steps
-----------
compile a project for the MSVC-MingW simulator and there will be undefined references.
Checklist:
----------
Related Issue
-----------
introduced in https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1047
> Add missing Extern "C" to MSVC portmacro.h

- include/task.h
Description
-----------
Discussed here: https://forums.freertos.org/t/tracing-improvements/20097
Adds a note to the (confusingly named) xTaskNumber member of TaskStatus_t explaining that the value is different to the TaskNumber that can be accessed using the vTaskSetTaskNumber and vTaskGetTaskNumber functions.
The value returned is actually the value of uxTCBNumber in the TCB.
Note that documentation on the website should also be updated (https://www.freertos.org/vTaskGetInfo.html#TaskStatus_t). Is this done automatically based on code comments or does this need to be done manually?
Thanks!
Test Steps
-----------
N/A
Checklist:
----------
N/A
Related Issue
-----------
N/A
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under …
> Clarify documentation of xTaskNumber in TaskStatus_t.

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Use `_GNU_SOURCE` macro instead of `__USE_GNU` and define it before including portmacro.h. The reason is that portmacro.h includes limits.h which in-turn includes features.h - this results in `__USE_GNU` getting incorrectly undefined. 
Test Steps
-----------
1. use glibc2.24 and gcc 6.3.0 build sucess
2. use glibc2.35 and gcc 11.3.0 build sucess
Checklist:
----------
Related Issue
-----------
#1077 
> Fix compilation warning about undelcared pthread_setname_np

- include/FreeRTOS.h
- tasks.c
Description
-----------
Discussed here: https://forums.freertos.org/t/tracing-improvements/20097
This hook enables tracers to run code on startup after all RTOS resources are created and to detect that the scheduler is starting without relying on traceENTER/traceEXIT macros.
It also provides tracers access to the task handle of all IDLE tasks, allowing them to be identified unambiguously and without relying on INCLUDE_xTaskGetIdleTaskHandle.
Notes: 
I  had another think about the above discussion regarding a `traceTASK_IS_IDLE_TASK` and `traceTASK_IS_TIMER_TASK` hook. I agree that they are probably very specific and maybe not the best solution. Instead I propose a `traceSTARTING_SCHEDULER` hook that is called just before `xPortStartScheduler` and exposes the idle task TCBs.
This is …
> Add traceSTARTING_SCHEDULER tracing hook.

- portable/GCC/ARM_CM4F/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM7/r0p1/port.c
…
Changed macro `__VFP_FP__` to `__ARM_FP` 
Description
-----------
Changed macro `__VFP_FP__` to `__ARM_FP` for ports GCC/ARM_CM7, GCC/ARM_CM4_MPU, and GCC/ARM_CM4F to accurately reflect if floating point hardware support is enabled. See linked issue for more details, but the macro `__VFP_FP__` is deprecated, and always set to `1` regardless of if floating point is enabled or not.
Test Steps
-----------
- Compiling the affected ports without floating point support enabled (`-mfloat-abi=soft`) now properly throws a compiler error
Checklist:
----------
Related Issue
-----------
Issue ID: 1087
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1087
> Changed macro __VFP_FP__ to __ARM_FP 

- portable/ARMv8M/secure/heap/secure_heap.c
- portable/GCC/ARM_CM23/secure/secure_heap.c
- portable/GCC/ARM_CM33/secure/secure_heap.c
- portable/GCC/ARM_CM35P/secure/secure_heap.c
- portable/GCC/ARM_CM55/secure/secure_heap.c
- portable/GCC/ARM_CM85/secure/secure_heap.c
- portable/IAR/ARM_CM23/secure/secure_heap.c
- portable/IAR/ARM_CM33/secure/secure_heap.c
- portable/IAR/ARM_CM35P/secure/secure_heap.c
- portable/IAR/ARM_CM55/secure/secure_heap.c
- portable/IAR/ARM_CM85/secure/secure_heap.c
- portable/MemMang/heap_2.c
- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
Update the call to traceMALLOC() to pass the actual size of the allocated block for secure_heap, heap2, heap4 and heap5.
Test Steps
-----------
test code:
```c
// hook to freertos kernel
#define traceMALLOC( pvAddress, uiSize ) trace_malloc(pvAddress, uiSize)
#define traceFREE( pvAddress, uiSize )   trace_free(pvAddress, uiSize)
```
```c
static int trace_enable = 0;
static uint32_t malloc_total = 0;
static uint32_t free_total = 0;
void trace_malloc(void *ptr, uint32_t size){
if(trace_enable){
printf("=malloc= %p, %lu\r\n", ptr, size);
malloc_total += size;
}
}
void trace_free(void *ptr, uint32_t size){
if(trace_enable){
printf("= free = %p, %lu\r\n", ptr, size);
free_total += size;
}
}
int test_unit(void){
trace_enable = 1;
void *p1 = pvPortMalloc(1016);
void *p2 = …
```
> Fix traceMALLOC() allocated bytes

- tasks.c
Description
-----------
Address the problem in this [thread](https://forums.freertos.org/t/smp-porting-checklist-a53-4-as-reference/14499/29).
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/76eb44382178237197a2c4982f9d99e8d64c9599/tasks.c#L846-L853
In `prvCheckForRunStateChange()`, enabling interrupts should cause this core to immediately service the pending interrupt and yield. Upon the next scheduling of the task, the assertion `configASSERT(pxThisTCB->xTaskRunState != taskTASK_SCHEDULED_TO_YIELD);` may not be true, as other cores could have requested a yield for this task before it evaluates its run state within the assertion. To address this, the task re-evaluates its run state in critical section within a loop until it is eligible for execution, which is the current implementation. …
> Remove run state assertion in prvCheckForRunStateChange

- portable/ARMv8M/secure/heap/secure_heap.c
- portable/GCC/ARM_CM23/secure/secure_heap.c
- portable/GCC/ARM_CM33/secure/secure_heap.c
- portable/GCC/ARM_CM35P/secure/secure_heap.c
- portable/GCC/ARM_CM55/secure/secure_heap.c
- portable/GCC/ARM_CM85/secure/secure_heap.c
- portable/IAR/ARM_CM23/secure/secure_heap.c
- portable/IAR/ARM_CM33/secure/secure_heap.c
- portable/IAR/ARM_CM35P/secure/secure_heap.c
- portable/IAR/ARM_CM55/secure/secure_heap.c
- portable/IAR/ARM_CM85/secure/secure_heap.c
- portable/MemMang/heap_1.c
- portable/MemMang/heap_2.c
- portable/MemMang/heap_4.c
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> fix typo gab -> gap and adjust indentation level

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Fix warning from "gcc -Wsign-compare" in the file
portable/ThirdParty/GCC/Posix/port.c since PTHREAD_STACK_MIN is used from system headers.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix gcc warning in posix port

- portable/GCC/ARM_CRx_No_GIC/port.c
- portable/GCC/ARM_CRx_No_GIC/portASM.S
- portable/GCC/ARM_CRx_No_GIC/portmacro.h
Description
-----------
This PR makes the following improvements to the ARM_CRx_No_GIC port-
1. Remove inline assembly and move all the assembly code to the `portASM.S` file.
2. Add support for `configUSE_TASK_FPU_SUPPORT` - 
* When `configUSE_TASK_FPU_SUPPORT` is defined to 1, tasks are created without floating point context. Tasks that want to use floating point, need to call `portTASK_USES_FLOATING_POINT()`. This is the current behavior.
* When `configUSE_TASK_FPU_SUPPORT` is defined to 2, each task is created with a floating point context.
If left undefined, `configUSE_TASK_FPU_SUPPORT` defaults to 1 for backward compatibility. 
3. The application writer can now implement `vApplicationSVCHandler` to handle the `SVC` calls raised within the application. `SVC 0` is used for the yield …
> Update ARM_CRx_No_GIC port

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Fix POSIX port to respect configUSE_TIME_SLICING.
Test Steps
-----------
```c
int main( void )
{
BaseType_t xTaskCreationResult = pdFAIL;
xTaskCreationResult = xTaskCreate( prvTask1Function,
"Task1",
configMINIMAL_STACK_SIZE,
NULL,
tskIDLE_PRIORITY,
NULL );
configASSERT( xTaskCreationResult == pdPASS );
vTaskStartScheduler();
for( ;; )
{
}
return 0;
}
/*-----------------------------------------------------------*/
static void prvTask1Function( void * pvParams )
{
uint64_t i;
BaseType_t xTaskCreationResult = pdFAIL;
/* Silence warning about unused parameters. */
( void ) pvParams;
xTaskCreationResult = xTaskCreate( prvTask2Function,
"Task2",
configMINIMAL_STACK_SIZE,
NULL,
tskIDLE_PRIORITY,
NULL );
configASSERT( xTaskCreationResult == pdPASS );
for( ;; )
{ …
```
> Fix POSIX port to respect configUSE_TIME_SLICING

- tasks.c
Otherwise it is very reasonable that config_TIMER_TASK_STACK_DEPTH is undefined.
Description
-----------
Add the `vApplicationGetTimerTaskMemory`s `#if` the condition `configUSE_TIMERS ==1` .
Test Steps
-----------
Define `configSUPPORT_STATIC_ALLOCATION`, and `configKERNEL_PROVIDED_STATIC_MEMORY`, but not `configTIMER_TASK_STACK_DEPTH`, you get a compiler error, that `configTIMER_TASK_STACK_DEPTH` is undefined.
Checklist:
----------
Related Issue
-----------
> Define vApplicationGetTimerTaskMemory only when configUSE_TIMERS is set

- stream_buffer.c
Description
-----------
The checks for `configUSE_TASK_NOTIFICATIONS` and `INCLUDE_xTaskGetCurrentTaskHandle` , are now placed after the check for `configUSE_STREAM_BUFFERS==1`, and hence only performed if support for stream buffers is actually requested.
Test Steps
-----------
Setting `configUSE_STREAM_BUFFERS` and `configUSE_TASK_NOTIFICATIONS` and/or `INCLUDE_xTaskGetCurrentTaskHandle` to 0 will trigger a compilation error. This is also described in #1108 .
Checklist:
----------
Related Issue
-----------
This PR addresses issue #1108 .
> Only check for stream buffer dependencies, if configUSE_STREAM_BUFFERS==1

- tasks.c
Description
-----------
If a task is blocked waiting for a notification then xNextTaskUnblockTime might be set to the blocked task's timeout time. If the task is unblocked for a reason other than a timeout xNextTaskUnblockTime is normally left unchanged, because it will automatically get reset to a new value when the tick count equals xNextTaskUnblockTime. However if tickless idle is used it is important to enter sleep mode at the earliest possible time - so reset xNextTaskUnblockTime here to ensure it is updated at the earliest possible time.
Test Steps
-----------
Tested the change on STM32H7 to ensure that xNextTaskUnblockTime gets reset after the call to vTaskNotifyGiveFromISR.
Checklist:
----------
- [NA] I have modified and/or added unit-tests to cover the code changes in this Pull …
> Reset xNextTaskUnblockTime in task notify FromISR APIs

- portable/GCC/ARM_CRx_No_GIC/portASM.S
Description
-----------
This PR adds support for `vApplicationFPUSafeIRQHandler`. The application writer needs to name their IRQ handler as:
1. `vApplicationIRQHandler` if the IRQ handler does not use FPU registers.
2.  `vApplicationFPUSafeIRQHandler` is the IRQ handler uses FPU registers.
When the application uses `vApplicationFPUSafeIRQHandler`, a default implementation of  `vApplicationIRQHandler` is used which stores FPU registers and then calls  `vApplicationFPUSafeIRQHandler`.
Test Steps
-----------
Tested on ARM_CRx_No_GIC [Demo ](https://github.com/FreeRTOS/FreeRTOS/pull/1236) with the code snippet
```
__asm volatile ( "vmov d8, r0, r1       \n"
"vmov d9, r0, r1       \n"
"vmov d10, r0, r1      \n"
"vmov d11, r0, r1      \n"
"vmov d12, r0, r1      \n"
"vmov d13, r0, r1      \n" …
```
> Add support for vApplicationFPUSafeIRQHandler

- portable/ThirdParty/XCC/Xtensa/portmacro.h
Add portMEMORY_BARRIER defination for Xtensa platform.
Description
-----------
The following code in xTaskResumeAll function may be over-optimized, the result is that the variable pxTCB does not change after the first loop.
```
pxTCB = listGET_OWNER_OF_HEAD_ENTRY( ( &xPendingReadyList ) );
listREMOVE_ITEM( &( pxTCB->xEventListItem ) );
portMEMORY_BARRIER();
listREMOVE_ITEM( &( pxTCB->xStateListItem ) );
prvAddTaskToReadyList( pxTCB );
```
The problem will be solved after define portMEMORY_BARRIER with a proper statement.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1114
> Add portMEMORY_BARRIER defination for Xtensa platform

- queue.c
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Modify the name of a private function to reflect what it actually does

- tasks.c
Description
-----------
The original implementation only initializes the first variable. After executing xTaskIncrement, the schedule might not behave as expected.
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
N/A
> Optimize xTaskIncrementTick for configNUMBER_OF_CORES > 1

- tasks.c
Description
-----------
Address the issue https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1086
In this PR:
* The SMP scheduler re-select a core to yield when the core affinity of a ready task is changed.
Test Steps
-----------
Running the unit test in this [PR](https://github.com/FreeRTOS/FreeRTOS/pull/1247) should has no error.
The test case `test_task_create_task_set_affinity_async_yield`.
```
/mnt/c/msys64/home/chinglee/kernel/oncall/affinity/FreeRTOS/FreeRTOS/Test/CMock/build/bin/smp_multiple_priorities_no_timeslice_multiple_priorities_no_timeslice_utest /mnt/c/msys64/home/chinglee/kernel/oncall/affinity/FreeRTOS/FreeRTOS/Test/CMock/build/bin/smp_multiple_priorities_no_timeslice_covg_multiple_priorities_no_timeslice_utest
... …
```
> Yield for task when core affinity of a ready task is changed

- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Description
-----------
When a block was allocated to the user by `pvPortMalloc`, its `pxNextFreeBlock` was set to NULL and not XORed with the canary (when `configENABLE_HEAP_PROTECTOR` was set to 1). As a result, a memory corruption which sets `pxNextFreeBlock` to zero wont be detected. 
This PR XORs `pxNextFreeBlock`  with the canary before returning the block to the user. This would ensure that a memory corruption would get detected if  `pxNextFreeBlock`  is modified. The only time it won't be caught is when  `pxNextFreeBlock` is updated to the canary value. Since canary values changes on every run, it is unlikely that a memory corruption would set `pxNextFreeBlock` to the canary value on every run.
Test Steps
-----------
I have tested the FreeRTOS/Demo test on the RISCV platform for …
> Add heap protector to allocted heap blocks

- portable/Common/mpu_wrappers_v2.c
Description
-----------
The function  `xTimerStartFromISR()`  is called from an ISR. This call leads to `MPU_xTimerGenericCommandFromISR()` in mpu_wrappers_v2.c.In this latter function, `pxHigherPriorityTaskWoken` is checked for being writable by `xPortIsAuthorizedToAccessBuffer()` which is not needed as the code is executed from ISR and thus is privileged. 
Test Steps
-----------
Compiled and ran the CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil [Demo](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil)
Checklist:
----------
Related Issue
-----------
#1126 
> Remove access check from MPU wrapper for xTimerStartFromISR

- portable/MSVC-MingW/port.c
Description
-----------
When a task deletes itself, `vTaskDelete` calls `portPRE_TASK_DELETE_HOOK` which translates to `vPortCloseRunningThread` on the Windows port. `vPortCloseRunningThread` never returns and as a result, `taskYIELD_WITHIN_API` in `vTaskDelete` does not get called. As a result, the next task is not scheduled when `configUSE_PREEMPTION` is set to 0.
This change records that a yield is pending in `vPortCloseRunningThread` so that the next tick interrupt schedules the next task regardless of the value of `configUSE_PREEMPTION`. 
Test Steps
-----------
```c
static void lowPrioTask(void* pvParam)
{
(void)pvParam;
for (;;)
{
printf("Low prio Task\r\n");
vTaskDelay(pdMS_TO_TICKS(1000));
}
}
static void highPrioTask(void* pvParam)
{
(void)pvParam;
vTaskDelete(NULL);
}
void …
```
> Pend a yield in vPortCloseRunningThread

- include/timers.h
Description
-----------
This removes an application race condition.
It was reported here - https://forums.freertos.org/t/software-timers-possible-race-condition-in-xtimerreset-example/21243
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
> Update comment in the example for declaration of xTimerReset

- portable/Common/mpu_wrappers.c
- portable/Common/mpu_wrappers_v2.c
- tasks.c
Description
-----------
This PR updates the preprocessor directive for `xTaskGetCurrentTaskHandle` from `configUSE_MUTEXES` to `configUSE_RECURSIVE_MUTEXES` . This change is made, since `xTaskGetCurrentTaskHandle` is used in these 2 functions
1. https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/queue.c#L771
2. https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/queue.c#L830
which use the `configUSE_RECURSIVE_MUTEXES` macro.
Test Steps
-----------
Compile and run the [STM32H7-NUCLEO](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/CORTEX_MPU_M7_NUCLEO_H743ZI2_GCC_IAR_Keil) MPU demo and [Posix-GCC](https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS/Demo/Posix_GCC) demo
Checklist:
----------
By submitting this pull request, I confirm that you can use, modify, copy, …
> Update preprocessor directive for xTaskGetCurrentTaskHandle

- portable/ARMv8M/secure/heap/secure_heap.c
- portable/GCC/ARM_CM23/secure/secure_heap.c
- portable/GCC/ARM_CM33/secure/secure_heap.c
- portable/GCC/ARM_CM35P/secure/secure_heap.c
- portable/GCC/ARM_CM55/secure/secure_heap.c
- portable/GCC/ARM_CM85/secure/secure_heap.c
- portable/IAR/ARM_CM23/secure/secure_heap.c
- portable/IAR/ARM_CM33/secure/secure_heap.c
- portable/IAR/ARM_CM35P/secure/secure_heap.c
- portable/IAR/ARM_CM55/secure/secure_heap.c
- portable/IAR/ARM_CM85/secure/secure_heap.c
Enables actually changing the size of the secure heap
Description
-----------
The secure heap is trying to use defines from FreeRTOSConfig.h but never actually included it. This patch changes this.
Test Steps
-----------
1. Create a project with secure heap 
2. Increase the secure heap size in the config
3. Check real heap size via build analyzer
Checklist:
----------
Related Issue
-----------
> Add configuration include to secure_heap.c

- event_groups.c
- include/event_groups.h
Event Groups: snapshot xEventGroupSetBits returning value while in vTaskSuspendAll
Description
-----------
Event Groups: snapshot xEventGroupSetBits returning value while in vTaskSuspendAll.
Fixes uxEventBits dereference after event group deleted by higher priority thread.
Test Steps
-----------
Code example that causes issues: https://github.com/flipperdevices/flipperzero-firmware/blob/78c5dd95d867941206e1be2fd3585c9c76132bd7/furi/core/timer.c#L43
General flow to reproduce issue:
- In High Priority Thread:
- Place StaticEventGroup_t on stack and initialize
- Call xTimerPendFunctionCall, pass reference to callback and event group handler
- Call xEventGroupWaitBits
- Delete Event Group 
- In callback(which will be executed in timer thread):
- use xEventGroupSetBits
- check returned result …
> Event Groups: snapshot xEventGroupSetBits returning value while in vTaskSuspendAll

- portable/MemMang/heap_5.c
heap_5 is used for multiple separated memory spaces. In the previous implementation, it only verifies the highest and lowest addresses. A pointer may not be within heap regions, but is still located between the highest and lowest addressed.
Description
heap_5 is used for multiple separated memory spaces. In the previous implementation, it only verifies the highest and lowest addresses. A pointer may not be within heap regions, but is still located between the highest and lowest addressed.
This PR will use a buffer to record the boundary of each heap region so the pointer detection can be made more accurate . This buffter is dynamically allocated at the end of vPortDefineHeapRegions().  At this time, the multi heap regions have been defined and there is only a free block and "pxFakeEnd" …
> Refine heap_5 heap protector

- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM33_NTZ/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM35P/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM55/portmacro.h
- portable/ARMv8M/non_secure/portable/IAR/ARM_CM85/portmacro.h
- portable/IAR/ARM_CM33/non_secure/portmacro.h
- portable/IAR/ARM_CM33_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM35P/non_secure/portmacro.h
- portable/IAR/ARM_CM35P_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM55/non_secure/portmacro.h
- portable/IAR/ARM_CM55_NTZ/non_secure/portmacro.h
- portable/IAR/ARM_CM85/non_secure/portmacro.h
- portable/IAR/ARM_CM85_NTZ/non_secure/portmacro.h
Description
-----------
Support for 16 MPU regions was added to Cortex-M33, M35P, M55 and M85 ports was added in [this PR](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/705) but the compile time error check was not removed. This results in compilation error when 16 MPU regions are used. This PR removes the not needed compile time error check.
Test Steps
-----------
Build IAR demo with `configTOTAL_MPU_REGIONS` set to 16.
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/cortex-m55-and-16-region-mpu-support/21470
> Remove error for 16 MPU resgion from IAR ports

- queue.c
Description
-----------
This was causing problem for 8-bit ports.
Test Steps
-----------
NA.
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1151
> Change the cast from UBaseType_t to size_t

- include/mpu_prototypes.h
- include/mpu_wrappers.h
- portable/Common/mpu_wrappers.c
Description
-----------
This PR address the following issues in MPU prototypes:
1. Fix the function decorator according to MPU wrapper used.
1. Add the missing prototypes for v1.
1. Add the corresponding mapping to mpu_wrappers.h.
1. Update v1 MPU wrappers for vTaskList and vTaskGetRuntimeStats to their newer versions.
Test Steps
-----------
Tested using Cortex-M7 MPU demo project.
Checklist:
----------
Related Issue
-----------
https://forums.freertos.org/t/cortex-m55-and-16-region-mpu-support/21470/5
> Update MPU prototypes

- .github/third_party_tools.md
- examples/coverity/README.md
- include/portable.h
- queue.c
- tasks.c
- timers.c
refactor: remove uneccesary task{ENTER | EXIT}_CRITICAL()
Description
-----------
The call to the task{ENTER|EXIT}_CRITICAL() function is being made unnecessarily. It was probably placed to control access to the UBaseType_t variable, which the kernel is only accessed in atomic contexts. Therefore, the MUTEX to access this variable is not necessary since tasks in the atomic context do not have concurrency problems in accessing certain data
I would like to thanks @n9wxu, @svenbieg, @richard-damon to help me with this task.
Test Steps
-----------
For test in ATMega328p:
First I create this FreeRTOSConfig.h
```C
#ifndef FREERTOS_CONFIG_H
#define FREERTOS_CONFIG_H
#define configUSE_PREEMPTION            1
#define configUSE_IDLE_HOOK             0
#define configUSE_TICK_HOOK             0 …
```
> refactor: remove uneccesary task{ENTER | EXIT}_CRITICAL()

- tasks.c
Fix incorrect error checking of prvCreateIdleTasks
Description
-----------
In environments that do not support static allocation (`configSUPPORT_STATIC_ALLOCATION == 0`), at `prvCreateIdleTasks()`, it calls `xCreateTask()` and compares its return value to `pdFAIL` (0) to check whether `xCreateTask()` failed. However, `xCreateTask()` returns `errCOULD_NOT_ALLOCATE_REQUIRED_MEMORY` (-1) as the error value, so the result of this comparison is always false.
This MR fixes this problem by changing the return value comparison to `!= pdPASS` instead of `== pdFAIL`.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Fix incorrect error checking of prvCreateIdleTasks

- portable/CMakeLists.txt
Description
-----------
Since `freertos_config` is an interface library, `INTERFACE` scope shall be used to define compile definitions.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> freertos-config: Fix library definitions scope

- include/mpu_prototypes.h
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/mpu_wrappers_v2_asm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/mpu_wrappers_v2_asm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/mpu_wrappers_v2_asm.c
- portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/mpu_wrappers_v2_asm.c
- portable/Common/mpu_wrappers.c
- portable/GCC/ARM_CM0/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM23/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM23_NTZ/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM33/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM33_NTZ/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM35P/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM35P_NTZ/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM3_MPU/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM4_MPU/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM55/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM55_NTZ/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM85/non_secure/mpu_wrappers_v2_asm.c
- portable/GCC/ARM_CM85_NTZ/non_secure/mpu_wrappers_v2_asm.c
- portable/RVDS/ARM_CM4_MPU/mpu_wrappers_v2_asm.c
Description
-----------
Removes the 'u' prefix as the variable is
no longer unsigned.
Test Steps
-----------
See https://github.com/search?q=repo%3AFreeRTOS%2FFreeRTOS-Kernel%20uxAutoReload%20&type=code
Checklist:
----------
- Will test through CI jobs.
- N/A - Simple variable renaming.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1165
> Fix AutoReload variable name

- include/mpu_prototypes.h
- portable/Common/mpu_wrappers.c
- portable/Common/mpu_wrappers_v2.c
Description
-----------
Fix variable name mismatch introduced by #1166.
Fix MPU v2 wrappers incorrectly using UBaseType_t instead of BaseType.
Test Steps
-----------
Allowing the CI jobs to execute.
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1165
> Fix variable name mismatch, mpu_wrappers type mismatch.

- tasks.c
Description
-----------
This PR adds configASSERT check for a NULL TCB Handle in case of APIs which use the function `prvGetTCBFromHandle` for getting a pointer to the appropriate TCB.
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
#1173 
> Add assert check for NULL TCB handle

- .github/workflows/auto-release.yml
- tasks.c
Follow Security Guide to update release.yml
Description
-----------
Follow [Security Guide](https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#understanding-the-risk-of-script-injections) to update release.yml.
Test Steps
-----------
Execute release flow in local branch, see result by https://github.com/ActoryOu/FreeRTOS-Kernel/actions/runs/11626810540/job/32379084241.
Checklist:
----------
Related Issue
-----------
> Follow Security Guide to update release.yml

- portable/GCC/RISC-V/port.c
- portable/IAR/RISC-V/port.c
Related to #189
Update `configMTIMECMP_BASE_ADDRESS` to be stored in a 64-bit integer.
* Change the type of `ullMachineTimerCompareRegisterBase` to `uint64_t` in `portable/GCC/RISC-V/port.c`.
* Change the type of `ullMachineTimerCompareRegisterBase` to `uint64_t` in `portable/IAR/RISC-V/port.c`.
* Update the initialization of `ullMachineTimerCompareRegisterBase` to use `configMTIMECMP_BASE_ADDRESS` in both files.
> Fix RISC-V configMTIMECMP_BASE_ADDRESS (64-bit) stored in 32-bit int

- portable/ThirdParty/GCC/RP2040/port.c
Related to #1172
Add `multicore_reset_core1` before `multicore_launch_core1` in `xPortStartScheduler` function to fix debugging issue on rp2040 with SMP enabled.
* Modify `portable/ThirdParty/GCC/RP2040/port.c` to include a call to `multicore_reset_core1` before `multicore_launch_core1` within the `#if portRUNNING_ON_BOTH_CORES` block.
> Fix SMP debugging issue on rp2040

- portable/CCRH/F1Kx/README.md
- portable/CCRH/F1Kx/port.c
- portable/CCRH/F1Kx/portasm.s
- portable/CCRH/F1Kx/portmacro.h
Description
-----------
- Fixed interrupt depth comparison logic to enhance accuracy in handling nested interrupts.
- Resolved parameter mismatch in portmacro.h, aligning function calls and definitions for consistency.
- Addressed FPU stack order issue to ensure correct stack management during FPU operations.
- Improved FPU checking flow, optimizing the process to better handle FPU-related context switching.
Test Steps
-----------
The test project [here](https://github.com/FreeRTOS/FreeRTOS-Community-Supported-Demos) (RH850_F1Kx_CCRH) has been re-conducted, and no regressions were found.
Checklist:
----------
Related Issue
-----------
N/A
> Enhancements and Bug Fixes for F1Kx Port

- include/portable.h
- portable/MemMang/heap_4.c
Heap: add new API to reset xMinimumEverFreeBytesRemaining.
Description
-----------
This commit adds new API functionality to reset xMinimumEverFreeBytesRemaining. 
This functionality provides ability to get heap statistics during a particular period of time.
For example, such use case could be required in a application that support FreeRTOS as OS and the software diagnostic cluster "reset watermarks" command.
Test Steps
-----------
- Allocate 10 times 100 bytes [pvPortMalloc()].
- xMinimumEverFreeBytesRemaining will decrease by 1000 bytes.
- Free 5 times 100 bytes [vPortFree()].
- xMinimumEverFreeBytesRemaining will remain unchanged.
- Call xPortResetHeapMinimumEverFreeHeapSize()
- xMinimumEverFreeBytesRemaining will be set to current free bytes remaining.
Checklist:
----------
- [ x ] I …
> Heap: add new API to reset xMinimumEverFreeBytesRemaining.

- tasks.c
Description
-----------
Apply a small optimization to recent changes to `xTaskNotifyWait()` and `ulTaskNotifyTake()`.  Prior to this PR, these functions suspend and resume the scheduler for all executions.  After this PR, these functions suspend the scheduler only if the task is not already notified, and only if the caller is willing to wait for the notification.
Checklist:
----------
Related Issue
-----------
Prior to #833, these functions never suspended the scheduler but used a critical section only.  After #833, these functions suspended the scheduler but only as needed (eg, the task wasn't already notified).  Then #982 cleaned up the implementation but also resulted in suspending the scheduler for every call to these functions.
By submitting this pull request, I confirm that you can …
> Don't suspend scheduler if task already notified

- portable/MemMang/heap_5.c
Description
-----------
The same was added to heap 4 in this PR - https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1189.
Test Steps
-----------
Build Posix_GCC demo with heap_5. 
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1188
> Add xPortResetHeapMinimumEverFreeHeapSize to heap5

- portable/ThirdParty/GCC/RP2040/include/portmacro.h
- portable/ThirdParty/GCC/RP2040/port.c
* Standardize on configNUMBER_OF_CORES != 1 to select SMP functionality
* Fix SDK pico_sync interoperability (configSUPPORT_PICO_SYNC_INTEROP == 1)
* Support for SDK2.0.0
> RP2040 updates/fixes from github.com/raspberrypi/FreeRTOS-Kernel

- portable/GCC/RISC-V/chip_specific_extensions/Pulpino_Vega_RV32M1RM/freertos_risc_v_chip_specific_extensions.h
- portable/GCC/RISC-V/chip_specific_extensions/RV32I_CLINT_no_extensions/freertos_risc_v_chip_specific_extensions.h
- portable/GCC/RISC-V/chip_specific_extensions/readme.txt
- portable/GCC/RISC-V/portASM.S
- portable/GCC/RISC-V/readme.txt
Description
-----------
Whilst reading through the RISC-V `portASM.S`, I noticed the documentation on lines 35 and 49 referenced an old directory (`RISC-V-RV32/`). After grepping through the other files in the directory, I noticed some discrepancies (some referencing `RISC-V/`, and some referencing `RISC-V-RV32/`). I've gone through and made the necessary changes.  
Checklist:
----------
Related Issue
-----------
> RISC-V documentation fixes

- portable/CMakeLists.txt
Fix CMake build for RP2040.
This fix enables build RP2040 using generic FreeRTOS CMake. Currently (before this fix), RP2040 is built using only its internal custom CMake [portable/ThirdParty/GCC/RP2040/library.cmake](https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/main/portable/ThirdParty/GCC/RP2040/library.cmake).
Description
-----------
Add public dependency to `hardware_sync` because `portable\ThirdParty\GCC\RP2040\include\portmacro.h` exposes include `"hardware/sync.h"` to `FreeRTOS.h` which is PUBLIC.
Add private dependency to `pico_multicore` to expose `LIB_PICO_MULTICORE` definition which enables `prvFIFOInterruptHandler()` under the following conditions:
https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/874fa7bed4b30ed4f1887ba3eae767c734515aa4/portable/ThirdParty/GCC/RP2040/port.c# …
> Fix CMake build for RP2040

- .github/scripts/manifest_updater.py
- manifest.yml
Description
-----------
Release tags use a capitalized V.
Our manifest tag is used by our SBOM
script to generate the URL and so
this needs to be capitalized to generate
a valid URL.
Test Steps
-----------
Testing the manifest updater...
```
./manifest_updater.py -v 12.34.56
```
manifest.yml contents
```
name : "FreeRTOS-Kernel"
version: "V12.34.56"
description: "FreeRTOS Kernel."
license: "MIT"
```
Verifying the SBOM generator...
```
export GITHUB_REPOSITORY=FreeRTOS/FreeRTOS-Kernel
python3 ./scan_dir.py --repo-root-path /Users/kstribrn/workspace/forks/FreeRTOS-Kernel
```
```
SPDXVersion: SPDX-2.2
DataLicense: CC0-1.0
SPDXID: SPDXRef-DOCUMENT
DocumentName: FreeRTOS-Kernel
DocumentNamespace: https://github.com/FreeRTOS/FreeRTOS-Kernel/blob/V11.1.0/sbom.spdx
Creator: Organization:Amazon …
```
> Update manifest to use 'V'

- .github/allowed_urls.txt
- .github/workflows/ci.yml
- portable/ARMv8M/non_secure/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM35P/non_secure/port.c
- portable/GCC/ARM_CM35P_NTZ/non_secure/port.c
- portable/GCC/ARM_CM55/non_secure/port.c
- portable/GCC/ARM_CM55_NTZ/non_secure/port.c
- portable/GCC/ARM_CM85/non_secure/port.c
- portable/GCC/ARM_CM85_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM35P/non_secure/port.c
- portable/IAR/ARM_CM35P_NTZ/non_secure/port.c
- portable/IAR/ARM_CM55/non_secure/port.c
- portable/IAR/ARM_CM55_NTZ/non_secure/port.c
- portable/IAR/ARM_CM85/non_secure/port.c
- portable/IAR/ARM_CM85_NTZ/non_secure/port.c
Description
-----------
This PR adds the guard `configUSE_MPU_WRAPPERS_V1` to the function `prvGetRegionAccessPermissions` to remove warning . 
Test Steps
-----------
NA.
Checklist:
----------
Related Issue
-----------
#1205 
> Add macro guard configUSE_MPU_WRAPPERS_V1 to remove definition missing warning.

- portable/MSVC-MingW/portmacro.h
Description
-----------
This is a regression issue introduced in https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/cfc268814a94a4deb8ddc8322b63ccae270a8669.
That PR was intended to update MIT licensed header from v9 to v10.
But it accidentally changed "portYIELD_FROM_ISR( x )" in MSVC-MingW/portmacro.h.
It caused "portYIELD_FROM_ISR( x )" does not return correct value to "prvProcessSimulatedInterrupts".
Test Steps
-----------
"prvProcessSimulatedInterrupts" checks the return value of ISR (portYIELD_FROM_ISR( x )) and updates ulSwitchRequired.
I tested on my laptop. The current return value is 0x52 which is due to missing return value of portYIELD_FROM_ISR( x ). 
After this patch, the returned value is correct. 
Checklist:
----------
Related Issue
----------- …
> Regression Bug Fix: Fix Incorrect Return of MSVC-MingW portYIELD_FROM_ISR

- portable/GCC/ARM_CA9/portASM.S
s0–s15 (d0–d7, q0–q3) and d16–d31 (q8–q15) are caller save register on aacps32
Description
-----------
From the AAPCS32, https://github.com/ARM-software/abi-aa/blob/main/aapcs32/aapcs32.rst#6121vfp-register-usage-conventions
- s16-s32 (d8-d15, q4-q7) must be preserved across subroutine calls (Callee save).
- s0-s14 (d0-d7,q0-q3) and d16-d32 (q8-q15) do not need be preserved (Caller save).
Checklist:
----------
Related Issue
-----------
> Refine VFP context for Coretex-A9

- .github/scripts/manifest_updater.py
- manifest.yml
- tasks.c
Description
-----------
Passes the core ID as an argument to the critical nesting count macros `port{GET/SET/INCREMENT/DECREMENT}_CRITICAL_NESTING_COUNT` in `tasks.c`. This allows the functions that use these macros to read and store the core ID once per call using `portGET_CORE_ID()` when using FreeRTOS SMP, thereby reducing the number of unnecessary, and generally slow, accesses to a peripheral register. I have summarised the worst-case number of calls to `portGET_CORE_ID()` before and after these changes:
| Function | # of calls (before) |  # of calls (after) |
| -------- | ------------------- | ------------------- |
| `prvCheckForRunStateChange()` | 4 | 1 |
| `prvYieldForTask()` | 5 | 1 |
| `vTaskSwitchContext()` | 2 | 1 |
| `vTaskYieldWithinAPI()` | 2 | 1 |
| `vTaskEnterCritical()` | …
> Pass core ID to critical nesting count macros

- tasks.c
This PR:
- Limits the idle task name length copy operation to prevent Out-of-bounds memory access warnings from static code analyzers.
- Fixes a bug where in the idle task name could be non null-terminated string for SMP configuration.
Description
-----------
- In the function `prvCreateIdleTasks()`, we have the operation -
```
for( xIdleTaskNameIndex = ( BaseType_t ) 0; xIdleTaskNameIndex < ( BaseType_t ) configMAX_TASK_NAME_LEN; xIdleTaskNameIndex++ )
{
cIdleName[ xIdleTaskNameIndex ] = configIDLE_TASK_NAME[ xIdleTaskNameIndex ];
/* Don't copy all configMAX_TASK_NAME_LEN if the string is shorter than
* configMAX_TASK_NAME_LEN characters just in case the memory after the
* string is not accessible (extremely unlikely). */
if( cIdleName[ xIdleTaskNameIndex ] == ( char ) 0x00 )
{
break;
} …
```
> fix(freertos): Limit idle task name length copy operation and ensure null-termination of the idle task name string

- include/FreeRTOS.h
- portable/CCRH/F1Kx/port.c
- portable/CCRH/F1Kx/portmacro.h
- portable/ThirdParty/GCC/RP2040/include/portmacro.h
- portable/ThirdParty/xClang/XCOREAI/portmacro.h
- portable/template/portmacro.h
- tasks.c
Description
-----------
Passes the core ID as an argument to the SMP lock macros `port{GET/RELEASE}_{TASK/ISR}_LOCK` in `tasks.c`. Since #1206, the functions calling these macros keep track of the core ID, so the port-specific spinlock function implementations can eliminate their internal calls to `portGET_CORE_ID()` to reduce the number of unnecessary, and generally slow, accesses to a peripheral register. This benefits the following FreeRTOS functions:
| Function | # of eliminated calls to `portGET_CORE_ID()` |
| -------- | -------------------------------------------- |
| `prvCheckForRunStateChange()` | 5 |
| `vTaskSwitchContext()` | 4 |
| `vTaskEnterCritical()` | 2 |
| `vTaskEnterCriticalFromISR()` | 1 |
| `vTaskExitCritical()` | 2 |
| `vTaskExitCriticalFromISR()` | 1 |
I've updated …
> Pass core ID to port lock macros

- include/stack_macros.h
Add a stack pointer bounds check when configCHECK_FOR_STACK_OVERFLOW is set to 2.
Description
-----------
I'm working on a small STM32F4 project using FreeRTOS. I've encountered a problem with stack overflow checks:
I am unsure how many bytes I need for my shell thread, so I set the stack size to 1024 bytes.
As documented in _FreeRTOS-Kernel/include/stack_macros.h_:
> Setting configCHECK_FOR_STACK_OVERFLOW to 1 will cause the macro to check
the current stack state only - comparing the current top of stack value to
the stack limit.  Setting configCHECK_FOR_STACK_OVERFLOW to greater than 1
will also cause the last few stack bytes to be checked to ensure the value
to which the bytes were set when the task was created have not been
overwritten.  Note this second test does not guarantee that …
> Add a stack pointer bounds check when configCHECK_FOR_STACK_OVERFLOW is set to 2.

- portable/GCC/ARM_CA9/port.c
- portable/GCC/ARM_CA9/portASM.S
Description
-----------
The function vApplicationFPUSafeIRQHandler gets the value of ICCIAR as parameter, but a constant containing the address of ICCIAR was also defined. Fix the name of the constant to align it with what it actually holds.
Test Steps
-----------
I have a build of FreeRTOS with variable shadowing warnings enabled, before the PR it produces a warning, afterwards it doesn't.
Checklist:
----------
Related Issue
-----------
> Fix variable shadowing warning in GCC

- .github/workflows/kernel-demos.yml
- portable/ThirdParty/GCC/Posix/port.c
Remove unused `__APPLE__` `mach_vm.h` include
Description
-----------
Looks like this was left over from https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/674 but the rest of that code (The `mach_vm_round_page`/`mach_vm_trunc_page` bits) are no longer in the codebase.
Including this file breaks compilation for iOS.
Test Steps
-----------
Run the POSIX sim on macOS. It still works!
Checklist:
----------
> POSIX Simulator: Remove unused __APPLE__ mach_vm.h include

- include/FreeRTOS.h
- include/mpu_prototypes.h
- include/mpu_wrappers.h
- include/queue.h
- portable/Common/mpu_wrappers.c
- portable/Common/mpu_wrappers_v2.c
- queue.c
This commit introduces the xQueueCreateSetStatic function, which allows for the static allocation of Queue Sets in FreeRTOS when both configUSE_QUEUE_SETS and configSUPPORT_STATIC_ALLOCATION are enabled.
Changes:
- Implemented xQueueCreateSetStatic function.
- Updated kernel to support static queue set creation.
Description
-----------
This commit introduces the xQueueCreateSetStatic function, enabling the static allocation of Queue Sets in FreeRTOS when both configUSE_QUEUE_SETS and configSUPPORT_STATIC_ALLOCATION are enabled. It leverages the xQueueGenericCreateStatic function for creating queue sets with user-supplied storage and static queue structures. This enhancement provides improved memory management for applications requiring static queue set creation, helping to minimize …
> Add xQueueCreateSetStatic method for static allocation of Queue Sets

- portable/GCC/ARM_AARCH64_SRE/port.c
- portable/GCC/ARM_AARCH64_SRE/portASM.S
- portable/GCC/ARM_AARCH64_SRE/portmacro.h
Add FPU Context Handling for ARM_AARCH64_SRE port.
Description
-----------
- Add support for vApplicationFPUSafeIRQHandler for ARM_AARCH64_SRE port, similar to the work done in [#1113](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1113).
- Add the configuration and status registers to the fpu saved context for ARM_AARCH64_SRE port.
- Add configUSE_TASK_FPU_SUPPORT support for ARM_AARCH64_SRE port. Ported from [#1048](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1048).
Test Steps
-----------
Tested on our example applications [NXP/harpoon-apps](https://github.com/NXP/harpoon-apps), which are demo applications running on Cortex-A using the [jailhouse](https://github.com/siemens/jailhouse) hypervisor with Linux running and FreeRTOS as a guest OS.
Checklist:
----------
Related Issue …
> Add FPU Context Handling for ARM_AARCH64_SRE port

- portable/ThirdParty/GCC/Posix/port.c
Avoid calling `pthread_sigmask` on `pthread`s not created by FreeRTOS. Also avoids waiting forever on `vPortEndScheduler` if that's called from a non-FreeRTOS thread.
Description
-----------
This PR modifies the behavior of the FreeRTOS POSIX simulator. The tick handler (via `sigaction`) might happen on any thread in the current process. This can cause hangs with non-FreeRTOS threads (because they can get hung when `prvSuspendSelf` is called on them.
Test Steps
-----------
Run this program against the `main` branch, notice that it hangs on shutdown.
```
#include <freertos/FreeRTOS.h>
#include <freertos/task.h>
#include <thread>
#include <iostream>
#include <unistd.h>
void appMainTask(void *parameters) {
while (true) {}
vTaskDelete(NULL);
}
bool mainLoop() {
static bool shouldRun = true; …
```
> POSIX Simulator: Handle `pthread`s not created by FreeRTOS differently

- .github/workflows/kernel-demos.yml
- portable/ARMv8M/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM23/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM23_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM33/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM33_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM35P/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM35P_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM3_MPU/portmacro.h
- portable/GCC/ARM_CM4_MPU/portmacro.h
- portable/GCC/ARM_CM55/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM55_NTZ/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM85/non_secure/portmacrocommon.h
- portable/GCC/ARM_CM85_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM23/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM23_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM33/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM33_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM35P/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM35P_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM4F_MPU/portmacro.h
- portable/IAR/ARM_CM55/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM55_NTZ/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM85/non_secure/portmacrocommon.h
- portable/IAR/ARM_CM85_NTZ/non_secure/portmacrocommon.h
- portable/RVDS/ARM_CM4_MPU/portmacro.h
Description
-----------
Ensure the saved context location falls within the reserved context area rather than overlapping with the next `MPU_SETTINGS` structure member.
This never caused a problem because actual read/write operations start from one word before the saved context location.
Thanks to @dajiang0055 for reporting this.
Test Steps
-----------
Verified on Cortex-M33 hardware.
Checklist:
----------
Related Issue
-----------
NA.
> Fix the context array size for MPU ports

- MISRA.md
- tasks.c
Description
-----------
This change:
* Removes the dependency on strings.h for the prvCreateIdleTask function
* Resolves several static analysis violations reported by tools like Parasoft
Test Steps
-----------
This change is being introduced for our upcoming safety certification release. This has been tested by our safety UTs.
Checklist:
----------
Related Issue
-----------
Builds off of https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1203
> fix: SA violation fixes and simplification for idle task length restrictions

- portable/ThirdParty/GCC/Posix/port.c
- portable/ThirdParty/GCC/Posix/utils/wait_for_event.c
Description
-----------
Prevent application hangs that occur when a thread dies while holding a mutex, particularly during vTaskEndScheduler or exit calls. This is achieved by setting the PTHREAD_MUTEX_ROBUST attribute on the mutex.
Test Steps
-----------
Tested locally using the modified application as suggested in [this thread](https://forums.freertos.org/t/freertos-hangs-after-vtaskendscheduler-in-posix-gcc-port/22287). Was also tested by @denravonska. 
Checklist:
----------
Related Issue
-----------
- GitHub issue: FreeRTOS/FreeRTOS-Kernel#1217
- Forum thread: [freertos.org/t/22287](https://forums.freertos.org/t/freertos-hangs-after-vtaskendscheduler-in-posix-gcc-port/22287)
By submitting …
> Mark mutex as robust to prevent deadlocks

- portable/MSVC-MingW/port.c
Reinstate "Fix inaccurate ticks in windows port"
Description
-----------
Reinstates PR #142 by that was reverted in #143 by . The reason given for the reversion was "Backing this out to merge it after the next Kernel release" which was in August 2020.
Test Steps
-----------
When running the Windows port with configTICK_RATE_HZ 1000 the program runs at roughly half real time speed. 
Tested on Windows 11 24H2 on a 11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz.
Checklist:
----------
- [x ] I have tested my changes. No regression in existing tests.
Related Issue
-----------
#143 and #143 
> Reinstate "Fix inaccurate ticks in windows port"

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Prevent application hangs that occur when a thread calls `prvIsFreeRTOSThread` before initializing the key. This is achieved by adding a call to `prvInitThreadKey()` in `prvIsFreeRTOSThread()` before the key is retrieved.
Test Steps
-----------
Was tested by @denravonska
Checklist:
----------
Related Issue
-----------
#1236 
> Call key creation before checking if a thread is FreeRTOS thread

- portable/ThirdParty/GCC/Posix/port.c
On FreeBSD pthread_once_t is a struct and cast is required. Otherwise there's compilation error:
```
../../mocks/freertos/port.c:261:23: error: expected expression
hSigSetupThread = PTHREAD_ONCE_INIT;
^
```
`PTHREAD_ONCE_INIT` is defined as: `{ PTHREAD_NEEDS_INIT, NULL }` on FreeBSD
Description
-----------
On FreeBSD `pthread_once_t` is a struct containing two elements and compiler complains about it.
Test Steps
-----------
Build demo app for Posix/GCC.
Checklist:
----------
Related Issue
-----------
#1239 
> Fix GCC/Posix port compilation on FreeBSD (#1239)

- portable/ThirdParty/GCC/Posix/port.c
Add instruction to suppress SIGUSR1 in Posix with LLDB debugger (macOS)
Description
-----------
While using the macOS default LLDB debugger, a call to vTaskEndScheduler results in an unhandled SIGUSR1 (aka SIGRESUME) when restoring the scheduler thread's signals with [pthread_sigmask](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1224/files#diff-e52a551c2f42efff2bb76b7f63f1bdd88b6b2d740fe7a66fd684a462201eda4fR342). This crashes the program.
Added instructions in `portable/ThirdParty/GCC/Posix/port.c` to suppress SIGUSR1 to prevent LLDB debugger interference when exiting xPortStartScheduler
Thanks to: @johnboiles for pointing it out in [1224](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1224)
Test Steps
-----------
Tested with this example:
```
#include <FreeRTOS.h>
#include …
```
> Add instruction to suppress SIGUSR1 in Posix with LLDB debugger

- portable/ThirdParty/GCC/Posix/port.c
Assert if `vPortYield` called from a non-FreeRTOS thread
Description
-----------
As requested by @aggarg [here](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/1237#issuecomment-2652827488) I'm adding an assert to obviously crash if `vPortYield` gets called from a non-FreeRTOS thread. This avoids intermittent freezes depending on the state of `pxCurrentTCB` where FreeRTOS may suspend the non-FreeRTOS thread (and never un-suspend it). Instead, with this PR, the program crashes, making the underlying issue more easily findable & fixable.
Test Steps
-----------
Call xTaskCreate outside of a FreeRTOS thread after the scheduler is started. Sometimes this will lead to the calling thread getting suspended forever.
Checklist:
----------
Related Issue
----------- …
> POSIX Simulator: Assert if vPortYield called from a non-FreeRTOS thread

- MISRA.md
- examples/coverity/coverity_misra.config
- queue.c
- tasks.c
- timers.c
Description
-----------
This PR addresses the MISRA C 2012 violations for Kernel release V11.2.0 
The following rules are fixed / suppressed:
1. Rule 1.2 - Language extension `__attribute__` cannot be used. ( suppressed )
2. Rule 14.3 - Controlling expressions shall not be invariant ( suppressed )
3. Rule 17.12 - A function identifier should only be used with either a preceding '&' (address-of operator) or with a parenthesized parameter list  ( Fixed )
4. FORWARD_NULL - This is not a MISRA violation , but a C coding standard, where a NULL pointer should not be dereferenced. This is of high severity, hence a NULL check has been added instead of suppressing it.  
Test Steps
-----------
Run the following steps
```
cmake -B build -S examples/coverity
cd build
cov-build --config …
```
> Fix MISRA violations for Kernel release V11.2.0

- History.txt
Description
-----------
This PR updates the history for FreeRTOS-Kernel V11.2.0 
Test Steps
-----------
NA
Checklist:
----------
- <s>[ ] I have modified and/or added unit-tests to cover the code changes in this Pull Request.</s>
> Add history.txt for release V11.2.0

- queue.c
Fix add overflow check on recursive mutex counter
Description
-----------
There is no overflow check of the recursive mutex counter yet.
If the counter overflows, the mutex will be released on the next call of xQueueGiveMutexRecursive(),
even if the number of calls does not match the number of calls of xQueueTakeMutexRecursive().
This would lead to unpredictable behavior in the application.
Test Steps
-----------
call xQueueTakeMutexRecursive() more than the maximum value of UBaseType_t
Checklist:
----------
Related Issue
-----------
> Fix add overflow check on recursive mutex counter

- portable/GCC/RISC-V/port.c
- portable/IAR/RISC-V/port.c
Description
-----------
Use architecture-dependent `UBaseType_t` instead of fixed type for `ullMachineTimerCompareRegisterBase`. This type is defined to `uint32_t` or `uint64_t` based on `XLEN`, resolving warnings on 32-bit platforms.
Test Steps
-----------
Tested using `RISC-V_RV32_QEMU_VIRT_GCC` demo for both 32-bit and 64-bit.
Checklist:
----------
Related Issue
-----------
Reported by @landretk on the PR FreeRTOS/FreeRTOS-Kernel#1176.
> Use UBaseType_t for ullMachineTimerCompareRegisterBase

- .github/.cSpellWords.txt
- portable/GCC/RISC-V/portASM.S
- portable/GCC/RISC-V/portContext.h
Save the vector context when changing the task
Description
-----------
An approach similar to #1250 has been used:
* Add the storage for the vector context next to the FPU context
* Enable the VPU as part of the task stack preparation
* Use the VS flags and values to avoid saving and restoring the context
* Save the 32 vector registers, `vl`, `vtype`, `vstart` and `vcsr`
* The 32 vector registers are saved/restored according to the configured length
Test Steps
-----------
A separate PR in the FreeRTOS repository will be created. That PR contains an enhanced RegTest that includes the vector registers.
Checklist:
----------
- [ X ] I have tested my changes. No regression in existing tests.
- [ X ] I have modified and/or added unit-tests to cover the code changes in this Pull Request. …
> Add support for Vector context save support on RISC-V

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Hi, after upgrading from V11.1.0 to V11.2.0, we saw the call to `vPortEndScheduler` sometimes return when using the POSIX port. We are only calling `vPortEndScheduler` from FreeRTOS tasks (threads in the POSIX port), so we don't expect the call to actually return.
There seems to be a race between the check whether the thread calling `vPortEndScheduler` is a FreeRTOS thread and the destruction of the thread key. If the thread key is destroyed before the check, the check fails even for FreeRTOS threads. 
Moving the check before the signal to end the scheduler should prevent the race.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, …
> Fix race in POSIX port `vPortEndScheduler`

- .github/workflows/ci.yml
- .github/workflows/formatting.yml
- .github/workflows/kernel-checks.yml
- .github/workflows/unit-tests.yml
- examples/template_configuration/FreeRTOSConfig.h
- include/croutine.h
- portable/MPLAB/PIC32MZ/port.c
Description
-----------
Implements a fix for the issue described on
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1265
Test Steps
-----------
Follow issue information
Checklist:
----------
- [X ] I have tested my changes. No regression in existing tests.
- [ X] I have modified and/or added unit-tests to cover the code changes in this Pull Request.
Related Issue
-----------
[1265](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1265)
> MPLAB PIC32MZ-EF - Adds an assert to catch register overflow (#1265)

- portable/Common/mpu_wrappers_v2.c
fix warnings from "gcc -Wconversion"
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> fix warnings from "gcc -Wconversion"

- include/stack_macros.h
- tasks.c
Fix access to current TCB inside the stack macros in SMP
Description
-----------
The problem is already described [here](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1269).
Checklist:
----------
Related Issue
-----------
[#1269](https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1269)
> FreeRTOS SMP: direct access to current TCB inside stack macros

- include/stack_macros.h
- tasks.c
Description
-----------
This reverts PR 1270. As concluded in the discussion [here](https://forums.freertos.org/t/cortex-a9-port-disable-interrupts-before-writing-to-icc-pmr/22952/14), if `portSET_INTERRUPT_MASK` and `portCLEAR_INTERRUPT_MASK` are implemented correctly to support recursive calls, this change is not needed.
Test Steps
-----------
NA.
Checklist:
----------
Related Issue
-----------
NA.
> Revert PR 1270: Direct access to current TCB inside stack macros

- portable/IAR/RL78/portmacro.h
Description
-----------
Compilation of the ASM file fails when using IAR version 5.10.3. See issue #1277 for more details.
To resolve this, the indentation of ASM macros in the portmacro.h file was adjusted. The IAR assembler only accepts ASM macro definitions that begin at the start of the line; indenting the macro name causes a compilation error.
This behavior was observed with IAR 5.10.3. Earlier versions have not been tested.
Test Steps
-----------
See issue #1277
Checklist:
----------
Related Issue
-----------
Bug #1277
> fix[IAR/RL78 Port] Compilation fails on portasm.s file

- queue.c
- stream_buffer.c
Compiling with clang static code analysis, possible NULL pointer dereference are found. Since configASSERT() can possibly return and continue "normal" operation, the code in queue.c and stream_buffer.c can be adjusted to avoid NULL pointer exceptions.
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> fix possible NULL pointer dereference after call to configASSERT()

- portable/ThirdParty/GCC/Posix/port.c
Description
-----------
Previously, the shared thread key was deleted in `xPortStartScheduler` after scheduler was ended. This created a race condition where `prvThreadKeyDestructor` (responsible for freeing thread-specific heap memory) would not be called if `xPortStartScheduler` deleted the key before the last task deletion, as destructors are not invoked after key deletion (see https://github.com/walac/glibc/blob/master/nptl/pthread_create.c#L145-L150).
Move thread key deletion to process exit to ensure all thread-specific memory is properly freed.
Test Steps
-----------
The LeakSanitzer reports leak without this change for the following program:
```c
#include <FreeRTOS.h>
#include <task.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdio.h>
static StackType_t stack[4096]; …
```
> Delete thread key on process exit

- tasks.c
Description
-----------
Add missing cast to `BaseType_t` when calling `portGET_CORE_ID`.
Test Steps
-----------
Build succeeds.
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1299
> Add missing cast to BaseType_t

- event_groups.c
- include/event_groups.h
- include/mpu_prototypes.h
- portable/Common/mpu_wrappers_v2.c
Description
-----------
This PR does the following:
* Remove `xEventGroupClearBitsFromISR` and `xEventGroupSetBitsFromISR` functions direct mapping to `xTimerPendFunctionCallFromISR` in case the trace facility is feature not set. This should match the current implementation in which the application calling `xEventGroupClearBitsFromISR` without defining the trace macros (i.e. `traceENTER_xEventGroupClearBitsFromISR` is a blank function in this case) will end up calling `xTimerPendFunctionCallFromISR` function directly. This enhances the readability of the code by not guarding the `xEventGroup<Set/Clear>BitsFromISR` functions' declaration and definition based on the trace facility macro (i.e. `configUSE_TRACE_FACILITY`).
* Refactor the guarding macros for `MPU_xEventGroupClearBitsFromISR` …
> event-groups: Fix multiple definitions

- portable/MemMang/heap_4.c
- portable/MemMang/heap_5.c
Change the macro from portMAX_DELAY to SIZE_MAX in order to initialize size_t-type variable correctly.
Description
-----------
From the [topic on forum](https://forums.freertos.org/t/compiler-warning-about-overflow-in-function-vportgetheapstats-from-heap-4-c/23730/4?u=du-yicheng23), I edited the macro from `portMAX_DELAY` to `SIZE_MAX` to initialize xMinSize (size_t-type variable) correctly.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> Change the macro from portMAX_DELAY to SIZE_MAX in order to initialize size_t-type variable correctly

- portable/MSVC-MingW/port.c
Description
-----------
If a user configures the `configASSERT` macro to expand to nothing, a call to the Win32 API `SetWaitableTimer()` doesn't get compiled.
This can happen if, for example, `configASSERT` set defined as `assert` (from assert.h) which expands to nothing when `NDEBUG` is set (common for "release" builds).
This PR has a patch to fix the issue.
Test Steps
-----------
Using the Win32 port, define `configASSERT` as follows:
```
#define configASSERT( x ) ( (void)0 )
```
then the scheduler doesn't "tick" and calls to, fx., `vTaskDelay()` won't return.
Checklist:
----------
> Fix risk of Win32 timer setup call getting ignored

- .github/scripts/kernel_checker.py
- portable/ARMv8M/non_secure/port.c
- portable/GCC/ARM_CM0/port.c
- portable/GCC/ARM_CM23/non_secure/port.c
- portable/GCC/ARM_CM23_NTZ/non_secure/port.c
- portable/GCC/ARM_CM33/non_secure/port.c
- portable/GCC/ARM_CM33_NTZ/non_secure/port.c
- portable/GCC/ARM_CM35P/non_secure/port.c
- portable/GCC/ARM_CM35P_NTZ/non_secure/port.c
- portable/GCC/ARM_CM3_MPU/port.c
- portable/GCC/ARM_CM4_MPU/port.c
- portable/GCC/ARM_CM55/non_secure/port.c
- portable/GCC/ARM_CM55_NTZ/non_secure/port.c
- portable/GCC/ARM_CM85/non_secure/port.c
- portable/GCC/ARM_CM85_NTZ/non_secure/port.c
- portable/IAR/ARM_CM23/non_secure/port.c
- portable/IAR/ARM_CM23_NTZ/non_secure/port.c
- portable/IAR/ARM_CM33/non_secure/port.c
- portable/IAR/ARM_CM33_NTZ/non_secure/port.c
- portable/IAR/ARM_CM35P/non_secure/port.c
- portable/IAR/ARM_CM35P_NTZ/non_secure/port.c
- portable/IAR/ARM_CM4F_MPU/port.c
- portable/IAR/ARM_CM55/non_secure/port.c
- portable/IAR/ARM_CM55_NTZ/non_secure/port.c
- portable/IAR/ARM_CM85/non_secure/port.c
- portable/IAR/ARM_CM85_NTZ/non_secure/port.c
- portable/RVDS/ARM_CM4_MPU/port.c
Description
-----------
- Rename ulStackFrameSize to ulHardwareSavedExceptionFrameSize to reflect the hardware-saved exception frame (8 or 26 words based on FPU/lazy stacking).
- Add comments explaining standard vs extended frames.
- Apply across Cortex-M ports.
- No functional change, improves readability.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
> cortex-M ports: Clarify hardware-saved exception frame size variable

- portable/ThirdParty/GCC/Posix/port.c
Fix: suppress unused-variable warning in GCC/Posix `pxPortInitialiseStack`
Description
-----------
Silences a compiler warning when `configASSERT()` compiles to a no-op by casting `ulStackSize` to `(void)`. No logic or runtime behavior changed.
```
FreeRTOS-Kernel/portable/ThirdParty/GCC/Posix/port.c:218:12: warning:
variable 'ulStackSize' set but not used [-Wunused-but-set-variable]
218 |     size_t ulStackSize;
|            ^
1 warning generated.
```
Test Steps
-----------
- Build with `configASSERT` disabled → compiles cleanly, no warnings
Checklist:
----------
Related Issue
-----------
N/A
> Fix: avoid set but unused variable warning in GCC/Posix pxPortInitialiseStack

- portable/ThirdParty/GCC/RP2040/include/portmacro.h
In C++ 20 the use of increments and decrements on volatiles are deprecated, and gives a warning when compiling for the RP2040. This PR fixes this and makes the code a bit easier to read. 
Related Issue
-----------
#1318 
> RP2040: Fix use of deprecated volatile semantics for C++20 (#1318)
