FreeRTOS/FreeRTOS-Kernel

CONTRIBUTING.md
=> Added CONTRIBUTING

croutine.c
Updates vCoRoutineSchedule() so it returns without doing anything if the co-routine internal data structures have not been initialised.  The internal data structures are initialised when the first co-routine is created.
NOTE: Co-routines are a deprecated feature.  This change was made to close off an old ticket as the source control transitions from SourceForge to Github.
=> Updates vCoRoutineSchedule() so it returns without doing anything if the co-routine internal data structures have not been initialised

portable/ARMv8M/non_secure/port.c, portable/ARMv8M/non_secure/portable/GCC/ARM_CM23/portmacro.h, portable/ARMv8M/non_secure/portable/GCC/ARM_CM23_NTZ/portmacro.h, portable/ARMv8M/non_secure/portable/GCC/ARM_CM33/portmacro.h, portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portmacro.h, portable/ARMv8M/non_secure/portable/IAR/ARM_CM23/portmacro.h, portable/ARMv8M/non_secure/portable/IAR/ARM_CM23_NTZ/portmacro.h, portable/ARMv8M/non_secure/portable/IAR/ARM_CM33/portmacro.h, portable/ARMv8M/non_secure/portable/IAR/ARM_CM33_NTZ/portmacro.h, portable/GCC/ARM_CM23/non_secure/port.c, portable/GCC/ARM_CM23/non_secure/portmacro.h, portable/GCC/ARM_CM23_NTZ/non_secure/port.c, portable/GCC/ARM_CM23_NTZ/non_secure/portmacro.h, portable/GCC/ARM_CM33/non_secure/port.c, portable/GCC/ARM_CM33/non_secure/portmacro.h, portable/GCC/ARM_CM33_NTZ/non_secure/port.c, portable/GCC/ARM_CM33_NTZ/non_secure/portmacro.h, portable/IAR/ARM_CM23/non_secure/port.c, portable/IAR/ARM_CM23/non_secure/portmacro.h, portable/IAR/ARM_CM23_NTZ/non_secure/port.c, portable/IAR/ARM_CM23_NTZ/non_secure/portmacro.h, portable/IAR/ARM_CM33/non_secure/port.c, portable/IAR/ARM_CM33/non_secure/portasm.s, portable/IAR/ARM_CM33/non_secure/portmacro.h, portable/IAR/ARM_CM33_NTZ/non_secure/port.c, portable/IAR/ARM_CM33_NTZ/non_secure/portasm.s, portable/IAR/ARM_CM33_NTZ/non_secure/portmacro.h
Add "Tickless Idle" support for ARMv8M ports
=> Add "Tickless Idle" support for ARMv8M ports

include/FreeRTOS.h, tasks.c
Added TaskNotify index to all trace points.
Description
-----------
Added TaskNotify index to all trace points.
Test Steps
-----------
N/A
Related Issue
-----------
N/A
=> Added TaskNotify index to all trace points.

portable/ARMv8M/non_secure/port.c, portable/GCC/ARM_CM23/non_secure/port.c, portable/GCC/ARM_CM23_NTZ/non_secure/port.c, portable/GCC/ARM_CM33/non_secure/port.c, portable/GCC/ARM_CM33_NTZ/non_secure/port.c, portable/IAR/ARM_CM23/non_secure/port.c, portable/IAR/ARM_CM23_NTZ/non_secure/port.c, portable/IAR/ARM_CM33/non_secure/port.c, portable/IAR/ARM_CM33_NTZ/non_secure/port.c
Description
-----------
If `xTaskCreate` API is used to create a task, the task's stack is allocated on heap using `pvPortMalloc`. This places the task's stack
in the privileged data section, if the heap is placed in the privileged data section.
We use a separate MPU region to grant a task access to its stack. If the task's stack is in the privileged data section, this results in
overlapping MPU regions as privileged data section is already protected using a separate MPU region. ARMv8-M does not allow overlapping MPU regions and this results in a fault. This commit ensures to not use a separate MPU region for the task's stack if it lies within the privileged data section.
Note that if the heap memory is placed in the privileged data section, the `xTaskCreate` API cannot be used to create …
=> Add support for privileged heap to ARMV8-M ports

portable/CCS/ARM_CM3/port.c, portable/GCC/ARM_CM3_MPU/port.c, portable/GCC/ARM_CM4_MPU/port.c, portable/GCC/ARM_CM7/r0p1/port.c, portable/IAR/ARM_CM4F_MPU/port.c, portable/IAR/ARM_CM7/r0p1/port.c, portable/RVDS/ARM_CM4_MPU/port.c, portable/RVDS/ARM_CM7/r0p1/port.c
Update incorrect port in comments.
=> Update incorrect port in comments

README.md
Doc Fix: Uncrustify location
Description
-----------
Specify where the uncrustify config used for this repository is.
Test Steps
-----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/98
=> Doc Fix: Uncrustify location

portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h, portable/ThirdParty/GCC/Xtensa_ESP32/port.c, portable/ThirdParty/GCC/Xtensa_ESP32/portasm.S, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_init.c, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_intr.c, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_vector_defaults.S, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_vectors.S
Description
-----------
Update kernel files with latest changes in ESP-IDF.
These changes are required for updating ESP-IDF to v4.2 release in Amazon FreeRTOS.
Changes required to add support for ESP32-S2 in Amazon FreeRTOS are also added.
=> Update kernel files for ESP32 port

portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h, portable/ThirdParty/GCC/Xtensa_ESP32/port.c, portable/ThirdParty/GCC/Xtensa_ESP32/portasm.S, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_init.c, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_intr.c, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_vector_defaults.S, portable/ThirdParty/GCC/Xtensa_ESP32/xtensa_vectors.S
This reverts commit adbfca54200d9665eb6b94da302b5268616072c0.
Revert "Update ESP32 port files (#92)"
Description
-----------
Reverting this update temporarily.
Test Steps
-----------
Related Issue
-----------
=> Revert "Update ESP32 port files (#92)"

portable/RVDS/ARM7_LPC21xx/portmacro.h, portable/RVDS/ARM_CA9/portmacro.h, portable/RVDS/ARM_CM0/port.c, portable/RVDS/ARM_CM0/portmacro.h, portable/RVDS/ARM_CM3/port.c, portable/RVDS/ARM_CM3/portmacro.h, portable/RVDS/ARM_CM4F/port.c, portable/RVDS/ARM_CM4F/portmacro.h, portable/RVDS/ARM_CM4_MPU/port.c, portable/RVDS/ARM_CM7/r0p1/port.c, portable/RVDS/ARM_CM7/r0p1/portmacro.h
Style: Add uncrustify guards, fix asm
Description
-----------
Add some uncrustify guards around asm sections
make some asm on a single line
=> Style: Add uncrustify guards, fix asm

portable/ThirdParty/GCC/ARC_EM_HS/arc_freertos_exceptions.c, portable/ThirdParty/GCC/ARC_EM_HS/arc_freertos_exceptions.h, portable/ThirdParty/GCC/ARC_EM_HS/arc_support.s, portable/ThirdParty/GCC/ARC_EM_HS/freertos_tls.c, portable/ThirdParty/GCC/ARC_EM_HS/port.c, portable/ThirdParty/GCC/ARC_EM_HS/portmacro.h, portable/ThirdParty/GCC/ARC_v1/arc_freertos_exceptions.c, portable/ThirdParty/GCC/ARC_v1/arc_freertos_exceptions.h, portable/ThirdParty/GCC/ARC_v1/arc_support.s, portable/ThirdParty/GCC/ARC_v1/port.c, portable/ThirdParty/GCC/ARC_v1/portmacro.h
Description
-----------
ARC v1 cores include ARC605, ARC610d, and ARC710d
These code can be built with GNU toolchain or Metaware_mcc toolchain
Also modify ARC port license headers
-------------------
=> Synopsys ARC v1 Port: add support to Synopsys ARC v1 series cores

portable/ThirdParty/GCC/ARM_CM33_TFM/README.md, portable/ThirdParty/GCC/ARM_CM33_TFM/os_wrapper_freertos.c
Title
TF-M integration with FreeRTOS Kernel
Description
-----------
Trusted Firmware M(TF-M) is an open-source project. It provides a reference implementation of PSA for Arm M-profile architecture.
This port adds the support that FreeRTOS applications can call the secure services in Trusted Firmware M(TF-M) through Platform Security Architecture(PSA) API based on the ARM Cortex-M33 platform.
Test Steps
-----------
This port has been tested on ARM Cortex-CM33 based platform.
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS/issues/184
=> TF-M integration with FreeRTOS Kernel

portable/GCC/RISC-V/port.c, portable/GCC/RISC-V/portASM.S
Reverting until we can test on additional RISC-V platforms.
=> Revert "RISC-V: Add RV32E / FPU support for GCC"

CONTRIBUTING.md, History.txt, SECURITY.md, include/queue.h, portable/GCC/AVR32_UC3/exception.S, portable/GCC/AVR32_UC3/port.c, portable/GCC/AVR32_UC3/portmacro.h, portable/GCC/MCF5235/port.c, portable/GCC/MCF5235/portmacro.h, portable/GCC/RX200/port.c, portable/GCC/RX200/portmacro.h, portable/IAR/AVR32_UC3/exception.s82, portable/IAR/AVR32_UC3/port.c, portable/IAR/AVR32_UC3/portmacro.h, portable/IAR/AVR32_UC3/read.c, portable/IAR/AVR32_UC3/write.c, portable/ThirdParty/GCC/ARC_v1/arc_freertos_exceptions.c, portable/ThirdParty/GCC/ARC_v1/arc_freertos_exceptions.h, portable/ThirdParty/GCC/ARC_v1/arc_support.s, portable/ThirdParty/GCC/ARC_v1/port.c, portable/ThirdParty/GCC/ARC_v1/portmacro.h, portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h, portable/ThirdParty/GCC/Xtensa_ESP32/port.c, tasks.c
Fix some broken/redirected URLs
Description
-----------
Some URLs are broken or not using https
=> Fix some broken/redirected URL

History.txt
Description
-----------
See title
Test Steps
-----------
n/a
Related Issue
-----------
n/a
=> Update History.txt for 10.4.2

History.txt
=> Update release date

.github/workflows/ci.yml, .github/workflows/header-checks.yml, include/stdint.readme
Description
-----------
Update branch of c-sdk repo to main from master. Also add missing apostrophe to stdint.readme.
=> Update branch of c-sdk repo to main

History.txt
Fresh History.txt with the changes for V10.4.3
=> Updated History.txt for V10.4.3

.github/scripts/kernel_checker.py
Simply update version number used in header checker. 
=> update version in version checker

include/task.h
=> Fix typo in comment in task.h

.github/scripts/kernel_checker.py, .github/workflows/kernel-checks.yml
Make use of changes from https://github.com/FreeRTOS/FreeRTOS/pull/492.
The header check will fail until the linked PR is merged, considering it uses files added in said PR.
=> incorporate updates from common

.github/scripts/kernel_checker.py, History.txt
Change URL from:
https://github.com/FreeRTOS/FreeRTOS-Kernel/commits/master
to:
https://github.com/FreeRTOS/FreeRTOS-Kernel/commits/main
in history.txt
This change matches a recent name change in the repository.
=> Update URL in history.txt

.github/workflows/auto-release.yml, .github/workflows/kernel-checks.yml
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Update python version to 3.7.10.

portable/RVDS/ARM_CM7/r0p1/port.c
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Replace TABs with spaces

portable/RVDS/ARM_CM4F/port.c, portable/RVDS/ARM_CM4F/portmacro.h, portable/RVDS/ARM_CM4_MPU/port.c, portable/RVDS/ARM_CM7/r0p1/port.c, portable/RVDS/ARM_CM7/r0p1/portmacro.h
Misc coding cleanup
Description
-----------
Misc coding cleanup and typo fixes.
Test Steps
-----------
No steps needed.
Related Issue
-----------
No related issue.
=> Code cleanup

.github/workflows/kernel-checks.yml, tasks.c
Description
-----------
1. Added idle hook to the minimal task
2. uncrustify
=> adding a minimal idle hook to the SMP port

.github/workflows/kernel-checks.yml
Description
-----------
Fixed the CI repo branch to main from smp
=> fixed CI repo branch

.gitmodules
Description
-----------
Adds two new submodules for community and partner supported ports.
=> Add new submodules for port contribution

portable/SDCC/Cygnal/port.c
Description
-----------
Just tidy up the 8051 sdcc port, make the line break aligned.
Test Steps
-----------
Related Issue
-----------
=> Tidy up the 8051 sdcc port

include/stream_buffer.h
Wrong header name corrected in the documentation
Description
-----------
Wrong header name corrected in the documentation
Test Steps
-----------
No test needed
Related Issue
-----------
=> minor fix in stream buffer doc

include/stream_buffer.h
Description
-----------
Change taskYIELD_FROM_ISR to portYIELD_FROM_ISR in docs
=> Change taskYIELD_FROM_ISR to portYIELD_FROM_ISR in docs

History.txt
Description
-----------
This was most probably a result of copying text from word file. 
=> Change hyphen to ASCII character

portable/ThirdParty/KnownIssues.md
Description
-----------
Add a Known Issues file in the Third Party folder
Test Steps
-----------
N/A.
=> Add a Known Issues file in the Third Party folder

include/task.h, tasks.c
Description
-----------
Added additional stack metrics to the task report.
This is a redo of PR #43 that was required because of the original PR age.
=> Feature: Add task top/end of stack to task info report

.github/lexicon.txt, include/message_buffer.h, include/queue.h, include/semphr.h, include/stream_buffer.h, include/timers.h
Description
-----------
Correcting some spell check words that were flagged by my IDE.
=> Clean some spell check words.

portable/GCC/RX100/port.c
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Fix GCC/RX100 function naming error.

include/queue.h
<sub>By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.</sub>
=> Fix description of configQUEUE_REGISTRY_SIZE

History.txt
Description
-----------
Update History.txt to include 10.4.6 changes
=> Update History.txt to include 10.4.6 changes

portable/GCC/RISC-V/portASM.S
Description
-----------
It is still possible to further relax the alignment using linker script, if needed. This make the code backward compatible in the sense that no change in the linker scripts will be needed for previously working projects. 
=> Add alignment for the direct mode handler

portable/GCC/RISC-V/portASM.S
Description
-----------
Test Steps
-----------
Related Issue
-----------
=> Remove exception loop tags.

portable/ThirdParty/GCC/ARM_CM33_TFM/README.md
Description
-----------
This PR updates the README in ARM_CM33_TFM port to align with TF-M v1.5.0 in TF-M integration. 
Test Steps
-----------
This PR has been verified on Arm Musca_b1 board by running OTA client agent with the AWS OTA server. 
Related Issue
-----------
N.A.
=> Update the README to align with TF-M v1.5.0 in TF-M integration

portable/ThirdParty/GCC/Posix/port.c
Format code, and remove implicit tests
Description
-----------
Run uncrustify on the code
Remove implicit tests
Test Steps
-----------
Demo build and run
=> Format code, and remove implicit tests

portable/MemMang/heap_3.c
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>
Minor heap3 modification to use same pointer check as others heap types.
-----------
Test Steps
-----------
Related Issue
-----------
=> Aligned nullptr check for heap3.

.github/scripts/kernel_checker.py
Description
-----------
Remove ThirdParty from core checker in smp branch
=> Remove ThirdParty from core checker in smp branch

portable/ThirdParty/GCC/ARM_CM33_TFM/README.md
Update to TF-M version TF-Mv1.6.0
Description
-----------
This PR updates the README in ARM_CM33_TFM port to align with TF-M v1.6.0 in TF-M integration.
Test Steps
-----------
This PR has been verified on Arm Musca_b1 board by running OTA client agent with the AWS OTA server.
Related Issue
-----------
N.A. 
=> Update to TF-M version TF-Mv1.6.0

.github/workflows/unit-tests.yml
Description
-----------
Fix codecov github actions failures.
Related Issue
-----------
[PR#517](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/517) blocked
=> Update codecov action to v3.1.0

include/task.h
Description
-----------
Update doc comments in task.h
=> Update doc comments in task.h

portable/GCC/ARM_CM55/non_secure/port.c, portable/GCC/ARM_CM55_NTZ/non_secure/port.c, portable/GCC/ARM_CM85/non_secure/port.c, portable/GCC/ARM_CM85_NTZ/non_secure/port.c, portable/IAR/ARM_CM55/non_secure/port.c, portable/IAR/ARM_CM55_NTZ/non_secure/port.c, portable/IAR/ARM_CM85/non_secure/port.c, portable/IAR/ARM_CM85_NTZ/non_secure/port.c
Description
-----------
These were missed when PR #59 was merged.
=> Update Cortex-M55 and Cortex-M85 ports

History.txt, manifest.yml
Bumping version in manifest.yml and adding relevant PRs to the History.txt file
=> Version Change

.github/workflows/kernel-checks.yml, .github/workflows/kernel-demos.yml
Description
-----------
This is needed to be compatible with the refactoring done in this PR - https://github.com/FreeRTOS/FreeRTOS/pull/889
=> Update FreeRTOS/FreeRTOS build checks

.github/pull_request_template.md
Description
-----------
This PR updates the PR template to include a checkbox which users should go through to verify that they have made unit-test modifications to cover the code changes as outlined in the corresponding PR.
Test Steps
-----------
N/A
Related Issue
-----------
N/A
=>  Update PR template to include checkbox for Unit Test related changes

.github/workflows/auto-release.yml
Description
-----------
Updates the auto release script to do the release tag updation in source files before SBOM generation.
Test Steps
-----------
Tested in fork
Checklist:
----------
Related Issue
-----------
=> Generates SBOM after source files are updated with release tag

History.txt
Description
-----------
Correct the misspelled name
=> Correct the misspelled name

History.txt
Description
-----------
Update attribution in History.txt
=> Update attribution in History.txt

README.md
Updated README.md for cross-compilation
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
No issue.
=> Updated README.md for cross-compilation

.github/workflows/kernel-demos.yml
Description
-----------
* Update the GNU ARM demo path to Community-Supported-Demos
Checklist:
----------
=> Update GNU ARM Toolchain demo workflow

.github/scripts/manifest_updater.py, .github/workflows/auto-release.yml, .github/workflows/kernel-demos.yml, portable/Common/mpu_wrappers_v2.c
Description
-----------
Add automation to update version number in manifest.yml. Also, bring required commits from main.
Test Steps
-----------
Run Kernel auto release from forked repository successfully, with updated version number in Manifest.yml file.
Checklist:
----------
=> Update version number in manifest.yml

History.txt
Description
-----------
This PR updates the History.txt file for FreeRTOS+Kernel Release V10.6.1 
Checklist:
----------
=> Update History.txt for V10.6.1

.github/lexicon.txt, event_groups.c, include/event_groups.h, include/queue.h, portable/Common/mpu_wrappers_v2.c, queue.c, tasks.c
Description
-----------
This commit adds runtime checks for function parameters to mpu_wrappers_v2 file. The same checks are performed in the API implementation using asserts.
Test Steps
-----------
Ran the soak tests on STM32H7-NUCLEO board successfully.
Checklist:
----------
=> Add runtime parameter checks

.github/workflows/formatting.yml
Description
-----------
Add the formatting bot action to FreeRTOS-Kernel
Test Steps
-----------
Bot can be seen working in FreeRTOS-Plus-TCP: [Here](https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/1017#issuecomment-1707462829)
Checklist:
----------
Related Issue
-----------
=> Add the formatting bot action to FreeRTOS-Kernel

include/queue.h
Description
-----------
Fix typo in code comments. xQueueSendToToFront -> xQueueSendToFront.
Test Steps
-----------
NA.
Checklist:
----------
=> Fix typo in code comments

tasks.c
Description
-----------
Add more comments for core affinity in `prvSelectHighestPriorityTask` to explain the logic. Forum user feeds back questions about the core select logic for core affinity feature. This PR adapts some the discussion in the comment to help reader understand the logic in this function.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
[Link to forum questions](https://forums.freertos.org/t/smp-question-about-the-function-prvselecthighestprioritytask/17926/7)
=> Add more comment for core affinity in prvSelectHighestPriorityTask

README.md
Description
-----------
Update information on how to raise a pull request in readme, so it is readily available for the user.
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
=> Update pull request information in readme

README.md
Description
-----------
Link to the CONTRIBUTING.md file in this repo, not the online github repo 
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Change hyperlink to CONTRIBUTING.md

.github/workflows/kernel-demos.yml, portable/Common/mpu_wrappers_v2.c
Description
-----------
This PR #[839](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/839) fixes size alignment issue introduced in PR #836 
Test Steps
-----------
Checklist:
----------
=> Backport PR 839 to FreeRTOS-Kernel V10.6.1

portable/Common/mpu_wrappers_v2.c
Description
-----------
This PR fixes size alignment issue introduced in PR#[836](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/836)
Test Steps
-----------
Checklist:
----------
=> Fix size alignment in the integer overflow issue

portable/Common/mpu_wrappers_v2.c
Description
-----------
It was checked using assert earlier.
Test Steps
-----------
Tested using STM32H743Zi demo.
Checklist:
----------
=> Covert object type check to runtime check

.github/workflows/coverity_scan.yml
Since https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/902 is already merged which fixes the same issue as [PR 903](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/903), this PR might require to be updated to have separate steps.
This reverts commit 76f3aa5b05e5c38e423e83eea23f5b34c15d3316.
Checklist:
----------
Related Issue
-----------
=> Revert PR# 903

History.txt
Description
-----------
This PR updates the History.txt file for FreeRTOS-Kernel Release V10.6.2
Checklist:
----------
=> Update History.txt for V10.6.2

portable/Common/mpu_wrappers.c
Description
-----------
Fix prototype of MPU_vTimerSetReloadMode
Checklist:
----------
=> Fix prototype of MPU_vTimerSetReloadMode

History.txt
Description
-----------
This PR updates the History.txt file for FreeRTOS+Kernel V11.0.1
Test Steps
-----------
NA
Checklist:
----------
Related Issue
-----------
=> Update History.txt for V11.0.1

portable/CMakeLists.txt
Apologies i missed this reference in #934, This should fixes broken build
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> RP2040: Fix removal of idle_task_static_memory.c

examples/template_configuration/FreeRTOSConfig.h
Description
-----------
This PR adds ARMv8-M port Specific Configuration definitions in the template configuration file.
Test Steps
-----------
NA
Checklist:
----------
=> Update ARMv8-M config definitions in template file

include/task.h, manifest.yml, portable/ThirdParty/GCC/RP2040/include/freertos_sdk_config.h, portable/ThirdParty/GCC/RP2040/include/portmacro.h, portable/ThirdParty/GCC/RP2040/include/rp2040_config.h, portable/ThirdParty/GCC/RP2040/port.c, portable/ThirdParty/GCC/Xtensa_ESP32/include/FreeRTOSConfig_arch.h, portable/ThirdParty/GCC/Xtensa_ESP32/include/portmacro.h, portable/ThirdParty/GCC/Xtensa_ESP32/port.c
Description
-----------
Update the reported version number on the main branch
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update version number

.github/workflows/auto-release.yml, .github/workflows/ci.yml, .github/workflows/coverity_scan.yml, .github/workflows/git-secrets.yml, .github/workflows/kernel-checks.yml, .github/workflows/kernel-demos.yml, .github/workflows/unit-tests.yml
Description
-----------
Update [actions/checkout](https://github.com/actions/checkout) from using [v3](https://github.com/actions/checkout/releases/tag/v3) to [v4.1.1](https://github.com/actions/checkout/releases/tag/v4.1.1) as it is the most recently released tag
Slight tweak to echo groups in workflow files that are not using the common format.
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update checkout action used in workflow files

portable/ThirdParty/GCC/ARM_TFM/README.md
Description
-----------
This page does not look to
exist anymore which is
failing our link verifier
check.
Test Steps
-----------
Rendered the markdown locally in VS Code and clicked the link
Checklist:
----------
Related Issue
-----------
None - simply noticed the failing check
=> Fix TFM about link

examples/README.md
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Add readme to example directory

History.txt
Description
-----------
Update History.txt for V11.1.0
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
=> Update History.txt for V11.1.0

include/task.h
Description
-----------
Update kernel version v11.1.0+ in tasks.h
Test Steps
-----------
N/A
Checklist:
----------
Related Issue
-----------
=> Update kernel version v11.1.0+ in tasks.h

.github/third_party_tools.md
Update the link to the getting started guide for Code Sonar.
Description
-----------
Update the link to the getting started guide for Code Sonar.
Test Steps
-----------
NA.
Checklist:
----------
Related Issue
-----------
NA.
=> Update link in third_party_tools.md

.github/workflows/unit-tests.yml
Description
-----------
Update upload-artifact GH action's version
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
NA.
=> Update upload-artifact GH action's version

portable/GCC/ARM_CM3/port.c, portable/GCC/ARM_CM3_MPU/port.c, portable/GCC/ARM_CM4F/port.c, portable/GCC/ARM_CM4_MPU/port.c, portable/GCC/ARM_CM7/r0p1/port.c
modernize ARM assembler syntax
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> modernize ARM assembler syntax

examples/coverity/FreeRTOSConfig.h, examples/template_configuration/FreeRTOSConfig.h
Description
-----------
Remove unused config parameters.
Test Steps
-----------
NA.
Checklist:
----------
Related Issue
-----------
https://github.com/FreeRTOS/FreeRTOS-Kernel/issues/1210
=> Remove unused config parameters

.github/workflows/auto-release.yml
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Update artifact path in the backup action
